### ISSUE TITLE
Bug: No such method runtime

### ISSUE THREAD

**Issue by Archanial** [siavash79/PixelXpert#545]
### Describe the issue

Runtime in logs, screen doesn't always wake up on double tap

### Steps to reproduce

Double tap screen
Runtime appears in logs

### Your device setup (Please take some time to give correct information here)

P7P, February update, aosp 2.7, zygisk 1.8.6 (everything up to date)
Related to #502

### Logs

![Screenshot_20230311-161145](https://user-images.githubusercontent.com/37456678/224492205-c60873b3-3585-442c-a4de-181d48cf5cf9.png)

**Comment by Archanial** [comment]
Probably this line
https://github.com/siavash79/AOSPMods/blob/17cdc8c022dc18271114a50bf81ac010f8acb10d/app/src/main/java/sh/siava/AOSPMods/systemui/FingerprintWhileDozing.java#L58

**Comment by EleoXDA** [comment]
> ### Describe the issue
> 
> Runtime in logs, screen doesn't always wake up on double tap
> 
> ### Steps to reproduce
> 
> Double tap screen
> Runtime appears in logs
> 
> ### Expected bahavior
> 
> _No response_
> 
> ### Your device setup (Please take some time to give correct information here)
> 
> P7P, February update, aosp 2.7, zygisk 1.8.6 (everything up to date)
> Related to #502
> 
> 
> ### Logs
> 
> ![Screenshot_20230311-161145](https://user-images.githubusercontent.com/37456678/224492205-c60873b3-3585-442c-a4de-181d48cf5cf9.png)
> 

If you are in magisk CANARY, please switch to stable version and try again

**Comment by Archanial** [comment]
I am using newest stable release of magisk
