### ISSUE TITLE
Feature Request: Hide QS Tile summary text

### ISSUE THREAD

**Issue by devnoname120** [siavash79/PixelXpert#573]
# What's on your mind?

The QS Tile summary text (e.g. on/off) is unnecessary as the Tile color (dark or blue) already shows whether a feature is active or not. I set it to 50% but it's still taking too much room in the grid of QS Tiles.

See below for a screenshot.

![Screenshot_20230415_143402](https://user-images.githubusercontent.com/2824100/232223942-1a41fbcb-9a98-4b03-96d7-3114a2e494d0.png)

Would it be possible to add an option to disable it completely? Thanks!

# Is this feature implemented on any other app/mod/rom? please specify

I think MIUI or a mod (Woobox or CustoMIUIzer) I'm not sure anymore.

**Comment by EleoXDA** [comment]
For some cases it shows degree of brightness/volume/flashlight level. So, it is not redundant. But as you said, you can decrease it. Disabling it will make some functions unusable. And that is a bad User Experience.

**Comment by bruno-mac-douglas** [comment]
Hi, in my case if I change the default style, I have nothing written. Just the icon, no text. Do you have any idea how to sort it out? Cheers

**Comment by EleoXDA** [comment]
> Hi, in my case if I change the default style, I have nothing written. Just the icon, no text. Do you have any idea how to sort it out? Cheers

No. Any signal theme or qs theme are provided AS IS with no support, fix or future proffing

**Comment by EleoXDA** [comment]
> # What's on your mind?
> 
> The QS Tile summary text (e.g. on/off) is unnecessary as the Tile color (dark or blue) already shows whether a feature is active or not. I set it to 50% but it's still taking too much room in the grid of QS Tiles.
> 
> See below for a screenshot.
> 
> ![Screenshot_20230415_143402](https://user-images.githubusercontent.com/2824100/232223942-1a41fbcb-9a98-4b03-96d7-3114a2e494d0.png)
> 
> 
> Would it be possible to add an option to disable it completely? Thanks!
> 
> # Is this feature implemented on any other app/mod/rom? please specify
> 
> I think MIUI or a mod (Woobox or CustoMIUIzer) I'm not sure anymore.
> 

Theoretically it could be possible to make the size 0%... But it could be very problematic if people change it and forget where they did it...

**Comment by EleoXDA** [comment]
> @EleoXDA It would be great to allow to set it to 0%. Imho it should be up to the user to configure things properly. What do you think? 

But then there will be some space left at the bottom and you will say it is not symmetric (like making battery icon 0%), so it is also not the best fix

**Comment by devnoname120** [comment]
@EleoXDA Ah I see so it wouldn't be possible to remove the padding around the text if its size is set to 0%?

**Comment by EleoXDA** [comment]
> @EleoXDA Ah I see so it wouldn't be possible to remove the padding around the text if its size is set to 0%?

Yes. The padding will still be there even if you set text size 0. So you will have a QS text that is slightly over middle

**Comment by EleoXDA** [comment]
I will put this on hold to see if it is possible to get rid of whole text region from QS

**Comment by siavash79** [comment]
It is possible to hide the secondary title.

Do you think you can PR this one too? I'm currently busy with compatibility with PQR3 and 14

**Comment by EleoXDA** [comment]
> It is possible to hide the secondary title.
> 
> Do you think you can PR this one too? I'm currently busy with compatibility with PQR3 and 14

Will it be similar to how battery icon gets removed? I mean the paddings that remain even after removing it

**Comment by bruno-mac-douglas** [comment]
> > Hi, in my case if I change the default style, I have nothing written. Just the icon, no text. Do you have any idea how to sort it out? Cheers
> 
> No. Any signal theme or qs theme are provided AS IS with no support, fix or future proffing

Well ok, but it doesn't explain why he can see the tile text and in my case I have no text

**Comment by EleoXDA** [comment]
> > > Hi, in my case if I change the default style, I have nothing written. Just the icon, no text. Do you have any idea how to sort it out? Cheers
> > 
> > No. Any signal theme or qs theme are provided AS IS with no support, fix or future proffing
> 
> Well ok, but it doesn't explain why he can see the tile text and in my case I have no text 

It means if you use anything other than No3D and default, you will not see text. As described in my previous message that you quoted:
"Any signal theme or qs theme are provided AS IS with no support, fix or future proffing"
So, this is what it is

**Comment by bruno-mac-douglas** [comment]
I have text only with default.
I don't have a No3D option. Just No34D and it doesn't have text either. I'd just like the same result as the poster of this case, but can't find how despite trying many things

**Comment by bruno-mac-douglas** [comment]
> > > > Hi, in my case if I change the default style, I have nothing written. Just the icon, no text. Do you have any idea how to sort it out? Cheers
> > > 
> > > 
> > > No. Any signal theme or qs theme are provided AS IS with no support, fix or future proffing
> > 
> > 
> > Well ok, but it doesn't explain why he can see the tile text and in my case I have no text
> 
> It means if you use anything other than No3D and default, you will not see text. As described in my previous message that you quoted: "Any signal theme or qs theme are provided AS IS with no support, fix or future proffing" So, this is what it is

I have text only with default.
I don't have a No3D option. Just No34D and it doesn't have text either. I'd just like the same result as the poster of this case, but can't find how despite trying many things

**Comment by EleoXDA** [comment]
> > > > > Hi, in my case if I change the default style, I have nothing written. Just the icon, no text. Do you have any idea how to sort it out? Cheers
> > > > 
> > > > 
> > > > No. Any signal theme or qs theme are provided AS IS with no support, fix or future proffing
> > > 
> > > 
> > > Well ok, but it doesn't explain why he can see the tile text and in my case I have no text
> > 
> > 
> > It means if you use anything other than No3D and default, you will not see text. As described in my previous message that you quoted: "Any signal theme or qs theme are provided AS IS with no support, fix or future proffing" So, this is what it is
> 
> I have text only with default. I don't have a No3D option. Just No34D and it doesn't have text either. I'd just like the same result as the poster of this case, but can't find how despite trying many things

then you are using an incompatible custom ROM. Head to README file and read it please. Otherwise open a new bugreport and answer all the questions instead of adding comments on another issue

**Comment by EleoXDA** [comment]
I think you can request this from Iconify as PixelXpert will not move with this direction.
