### ISSUE TITLE
Feature Request: Allow hostnames to be visible to devices connected to android hotspot.

### ISSUE THREAD

**Issue by Spagett1** [siavash79/PixelXpert#679]
Gday, thanks for making this mod.

One issue I have is that when devices are connected to my phone's hotspot(say a laptop and a raspberry pi for example) the hostnames are not exposed, causing me to nmap the network each time to find the devices IP address before ssh'ing, accessing websites over LAN, etc. It would be really great if a toggle to allow this functionality was in the section next to the hide ssid option. 

Is this feature implemented on any other app/mod/rom?
I'm not sure about this, it's the default on most Linux distributions but I have no clue about other Android flavours/ROMS.

**Comment by Spagett1** [comment]
![Screenshot_20230812-000650_Termux~2](https://github.com/siavash79/AOSPMods/assets/77225642/12219c2a-73f7-407c-9c7c-a704ad1cbde8)
An example of this is how nmap in termux does not show the hostnames of connected devices.

Iirc my old Samsung device running stock firmware did have this functionality but I can't be too sure.

**Comment by EleoXDA** [comment]
> Gday, thanks for making this mod.
> 
> One issue I have is that when devices are connected to my phone's hotspot(say a laptop and a raspberry pi for example) the hostnames are not exposed, causing me to nmap the network each time to find the devices IP address before ssh'ing, accessing websites over LAN, etc. It would be really great if a toggle to allow this functionality was in the section next to the hide ssid option.
> 
> Is this feature implemented on any other app/mod/rom? I'm not sure about this, it's the default on most Linux distributions but I have no clue about other Android flavours/ROMS.

Where do you envision to see this information?

**Comment by EleoXDA** [comment]
In settings app? In notifications? Or elsewhere?

**Comment by Spagett1** [comment]
Ideally it would be exposed over nmap/other devices may use it to connect to eachother however the information could be useful as a way to see what devices are connected to the hotspot, I could see this info as being displayed in settings or as a notification "connected devices"
