### ISSUE TITLE
Feature Request: Add "Noisy Notifications" toggle

### ISSUE THREAD

**Issue by usamaiqbal1177** [siavash79/PixelXpert#681]
This feature is already on almost every rom now. It suprresses notification sounds when the screen is on. You can hear the sound of call though.

Adding commits from different roms that I found:

https://github.com/PixelOS-Pixelish/frameworks_base/commit/67e2c468b909181d88545eb3b79aede7a1d7fcf9

https://github.com/Evolution-X/frameworks_base/commit/a8c9fc36564b48a915c31904db42e99fb5ca70c0

https://github.com/PixelExtended/frameworks_base/commit/e430f6e0976f1a2f0e88c4b52e181a828404db87

![IMG_20230814_085233_086](https://github.com/siavash79/AOSPMods/assets/58624914/ae3b1130-6c88-4552-a43d-e240b478a954)

**Comment by EleoXDA** [comment]
We will check it out if it is feasible or not and inform you
