### ISSUE TITLE
[Bug] SystemUI not responding after installing AOSPMods

### ISSUE THREAD

**Issue by BoyWithDanii** [siavash79/PixelXpert#703]
### Describe the issue

System UI not responding

### Steps to reproduce

1. Install module
2. System UI not responding 

### Expected behavior

Work

### Your device setup (Please take some time to give correct information here)

- Google Pixel 6a 
- Android 14 U1B1 (QPR Beta 1)
- September security update
- 26.3
![Screenshot_20231005-090740](https://github.com/siavash79/AOSPMods/assets/58140209/2b678a09-6d30-4ce6-83b8-3011a4e2aa9f)
![Screenshot_20231005-090805](https://github.com/siavash79/AOSPMods/assets/58140209/71d591c2-3d23-437a-86fa-833d1d08172b)
![Screenshot_20231005-090557](https://github.com/siavash79/AOSPMods/assets/58140209/25981449-255e-4dc6-8ca8-137262e7cc2c)
![Screenshot_20231005-090658](https://github.com/siavash79/AOSPMods/assets/58140209/030b94fa-23da-433b-8d5e-106230e6e634)

### Logs

[LSPosed_2023-10-05T09_12_32.098024.zip](https://github.com/siavash79/AOSPMods/files/12813376/LSPosed_2023-10-05T09_12_32.098024.zip)
[LSPosed_2023-10-05T09_12_56.057920.zip](https://github.com/siavash79/AOSPMods/files/12813381/LSPosed_2023-10-05T09_12_56.057920.zip)

**Comment by BoyWithDanii** [comment]
Followed all steps, disabled all modules in magisk and lsposed except AOSPmods and lsposed, I got Pixel Launcher stopped working once, and system UI is not responding each 5 seconds.

[LSPosed_2023-10-05T17_04_44.454004.zip](https://github.com/siavash79/AOSPMods/files/12820040/LSPosed_2023-10-05T17_04_44.454004.zip)
![Screenshot_20231005-170459](https://github.com/siavash79/AOSPMods/assets/58140209/6bac86b1-ed72-4359-8a49-beb160e130af)
![Screenshot_20231005-170318](https://github.com/siavash79/AOSPMods/assets/58140209/cfab6ede-73c4-4e84-921e-f6a70e5705f7)

**Comment by EleoXDA** [comment]
> Followed all steps, disabled all modules in magisk and lsposed except AOSPmods and lsposed, I got Pixel Launcher stopped working once, and system UI is not responding each 5 seconds.
> 
> [LSPosed_2023-10-05T17_04_44.454004.zip](https://github.com/siavash79/AOSPMods/files/12820040/LSPosed_2023-10-05T17_04_44.454004.zip)
> ![Screenshot_20231005-170459](https://github.com/siavash79/AOSPMods/assets/58140209/6bac86b1-ed72-4359-8a49-beb160e130af)
> ![Screenshot_20231005-170318](https://github.com/siavash79/AOSPMods/assets/58140209/cfab6ede-73c4-4e84-921e-f6a70e5705f7)
> 

Please remove all said modules and retry. Your logs still contain other modules

**Comment by EleoXDA** [comment]
Can you still reproduce it with latest canary version?

**Comment by CasperOng** [comment]
I was getting this bug also, worked with the canary release on 14 Oct

What have you done to fix it 😂?
