### ISSUE TITLE
Feature Request: Replace Android 14 back gesture animation with Android 13 animation.

### ISSUE THREAD

**Issue by K3LS0** [siavash79/PixelXpert#706]
It would be great to remove the new bubble icon that displays on Android 14 when using the back gesture. It's so big and obnoxious compared to the old simple arrow animation.

Edit: To clarify, Android 13 version was much cleaner and less intrusive, an option to bring back the A13 animation would be great.

You can see the icon in the image below for reference. (Right hand side)

![Screenshot_20231012-021217](https://github.com/siavash79/AOSPMods/assets/94309910/72d4f308-8ff7-4b4c-817d-5b61969ff678)

**Comment by EleoXDA** [comment]
It is normal size and gesture is quite important to know whether you are going back or using another gesture (e.g. when zooming in out of images, openning hamburger menu and etc). Removal of it is a bad UX. User will accidentally use back gesture and won't even know it

**Comment by K3LS0** [comment]
I should have been clearer; I meant that the Android 13 icon was much cleaner and there should be an option to remove the A14 icon and use the A13 version instead.
