### ISSUE TITLE
[Bug] Pixel 8: High CPU usage on A14 on custom battery symbol - system_ui

### ISSUE THREAD

**Issue by xperia-droid** [siavash79/PixelXpert#709]
### Describe the issue

Changing the custom battery icon to not standard it rises the CPU usage of system ui process to 60 %+. Changing it back to default chills the CPU usage.

### Steps to reproduce

I bought a new Pixel 8 (Android 14, October 2023 security patch) and rooted it directly and installed the AOSP Mods module.
I always had a high battery load since the purchase and the battery was dead after about 5h of screen time .

Today I started looking for the problem and found a very interesting behavior.
Using adb and top I monitored the CPU usage. In doing so, I had about 60-70% CPU usage just from the System UI process and that went down to 20% CPU usage when the display was off.

I disabled the two installed UI mods (AOSP mods and notifcation shade transparancy) and the load from the system UI process went down to 5% when the display was on.
After that I reinstalled both mods and checked again the load of the System UI process, which was still at 5%. Then I started to activate some changes in AOSP mods.

At the exact moment I set a custom battery icon in the AOSP Mods section, the CPU usage went up to ~63% permanently, and when the display was off, it went down to 20%.
When I changed the battery icon to the default setting, the CPU load was immediately only 5%. I tried all the custom battery icons in AOSP mods, the CPU load always stayed at around 60%, only the default setting had the load at a moderate 5% for the CPU.

Furthermore, I set the theme settings to "Pitch Black" next to the default battery icon, which also increased the CPU load to another 5%. With all other options, the CPU load also remained at about 10%. Only with the default settings it stayed at 5% total CPU load.

Screenshots before:
![2023-10-17 02_21_59-](https://github.com/siavash79/AOSPMods/assets/24463981/4c0870fd-27d5-4f35-a743-398909c63b31)
![2023-10-17 02_22_36-Pixel 8](https://github.com/siavash79/AOSPMods/assets/24463981/5925c170-ee61-49e7-941b-651e778eb8d5)

After:
![2023-10-17 02_23_12-](https://github.com/siavash79/AOSPMods/assets/24463981/eaa97bcc-581b-44ff-9e5b-e722284f572e)
![2023-10-17 02_23_23-Pixel 8](https://github.com/siavash79/AOSPMods/assets/24463981/cadeb1c0-0998-48df-97ed-c68b0ff5d73e)

### Expected behavior

Only setting an custom battery icon should not rise up the cpu usage as described.  

### Your device setup (Please take some time to give correct information here)

- Google Pixel 8
- Android 14
- October 2023 (Stock Google ROM)
- Magisk 26.3
- root Apps: 
![2023-10-17 02_31_20-](https://github.com/siavash79/AOSPMods/assets/24463981/ed36a160-dc98-4981-ac8d-f37e532d52cd)
- magisk modules: 
![2023-10-17 02_34_45-](https://github.com/siavash79/AOSPMods/assets/24463981/ce41950d-6423-457e-8bf2-adfcd8dead7c)
- Lsposed Modules:
![2023-10-17 02_38_01-Pixel 8](https://github.com/siavash79/AOSPMods/assets/24463981/aeaf4792-ba0d-4627-a201-05eadb65fe85)

### Logs

I disabled all the modules (magisk and lsposed) as described above and rebooted the phone.
Then I used top to monitor the CPU usage and waited until the usage was low.
![2023-10-17 02_43_55-](https://github.com/siavash79/AOSPMods/assets/24463981/820f87c2-6183-433a-b224-f553e5d48d56)

Afterwards I enabled the custom battery icon again and checked the CPU usage:
![2023-10-17 02_44_37-](https://github.com/siavash79/AOSPMods/assets/24463981/b4e559d2-d251-4b32-bd76-5d75533dc604)

I waited 2 minutes, but the cpu usage stood at 50 - 70 % on system ui proces.

Attached the lsposed logs:
[LSPosed_2023-10-17T02_46_52.383898.zip](https://github.com/siavash79/AOSPMods/files/12923106/LSPosed_2023-10-17T02_46_52.383898.zip)

Changing back to default battery icon settings (forgot it in the details):
![2023-10-17 02_50_12-](https://github.com/siavash79/AOSPMods/assets/24463981/7d5bf913-1e46-4bcf-9c60-77a73b8dc5e8)

**Comment by siavash79** [comment]
I did study you report, and tried to replicate it on my P7.

Here's the result:

The issue comes from "battery charging animation", which is turned on on your device. Obviously, the animation takes a lot of resources to do that kind of animation.
However, one thing to note is that battery charging animation is only active when the device is connected to the cable (and charging). So I don't expect the high CPU usage you spotted would have any effect on your device battery life.

For confirmation, I did successfully reproduce the CPU usage, but after switching to wireless adb, I could confirm that CPU usage drops down once the cable is disconnected from the phone.

You might want to search for other reasons behind battery drainage. As a general idea, the more "mods" you have active on your rom, the higher the chances to reduce your battery life. This also includes PixelXpert
