### ISSUE TITLE
Add Expand/Collapse all buttons doesn't work properly. 

### ISSUE THREAD

**Issue by spookymyo** [siavash79/PixelXpert#710]
### Describe the issue

In the miscellaneous section, under notification options, turning on add expand/collapse all buttons doesn't function properly. The expand button works every time on every notification, but the collapse button works only on some notifications and only some of the time, some notifications aren't collapsed at all. 

### Steps to reproduce

1. Pull down notification tray
2. Click expand button, works as advertised
3. Click collapse button and it works intermittently 

### Expected behavior

When pressing the collapse button, all notifications should collapse. 

### Your device setup (Please take some time to give correct information here)

Google Pixel 6 Pro.
Stock Android 14.
Rooted with magisk 26.3

**Comment by siavash79** [comment]
try scrolling slightly on notification after collapse. it should work as intended

**Comment by EleoXDA** [comment]
@spookymyo please give examples of non-collapsable notifications as we cannot reproduce this issue. This issue has become stale now.
