### ISSUE TITLE
[Bug]  "ignore camera cutout" causes status bar layout inconsistencies

### ISSUE THREAD

**Issue by LollosoSi** [siavash79/PixelXpert#712]
### Describe the issue

Enabling the feature causes 3 weird behaviours: 1) status bar elements are raised. 2) custom status bar height isn't visible (only extremely low values have visible effects) 3) status bar elements in grid layout overlap (clock on the left does this with notifications) and is cut. Also causes system UI ANR

### Steps to reproduce

Enable the feature
Rotate display
Check status bar

### Expected behavior

Layout should stay the same

### Your device setup (Please take some time to give correct information here)

Device: Pixel 7, first public android 14 release with kirisakura kernel
Magisk 26.3
LSposed 1.9.1
This is the only LSposed module
![Multi row system and notifications](https://github.com/siavash79/AOSPMods/assets/24529432/9614d131-662d-4e72-badc-d2c1dd023848) 
![Raised (single row) status bar](https://github.com/siavash79/AOSPMods/assets/24529432/0e68472c-b7e4-4008-9f61-72642ebe96af)

### Logs

[LSPosed_2023-10-19T02_10_34.212453.zip](https://github.com/siavash79/AOSPMods/files/13035163/LSPosed_2023-10-19T02_10_34.212453.zip)

**Comment by EleoXDA** [comment]
Please update to latest LSPosed

**Comment by LollosoSi** [comment]
Updated to LSPosed 1.9.2. Problem is not fixed

**Comment by gzyguo** [comment]
I tried set bar height to 50%, all visual issue gone for now.

**Comment by LollosoSi** [comment]
Seems fixed with the latest version

Il dom 5 nov 2023, 16:37 gzyguo ***@***.***> ha scritto:
