### ISSUE TITLE
Bring back hide navbar

### ISSUE THREAD

**Issue by Dialgatrainer02** [siavash79/PixelXpert#715]
What's on your mind?
Bring back the removed setting to hide the navbar please 

Is this feature implemented on any other app/mod/rom? please specify
Aosp mods 3.00

Is the removal because of the deprecation of the overlay if so is there a way to manually install it?

**Comment by Dialgatrainer02** [comment]
I got the rro from the old version and placed that in the right dir it's working as a temp fix but please could navbar be kept in support.

**Comment by robotfishe** [comment]
> I got the rro from the old version and placed that in the right dir it's working as a temp fix but please could navbar be kept in support.

Can you explain this a bit more? Would really like to be able to bring back this feature, but the old versions of AOSP Mods stopped working on recent Android 14 beta.

**Comment by EleoXDA** [comment]
> > I got the rro from the old version and placed that in the right dir it's working as a temp fix but please could navbar be kept in support.
> 
> Can you explain this a bit more? Would really like to be able to bring back this feature, but the old versions of AOSP Mods stopped working on recent Android 14 beta.

just use literally any other module for that. iconify, hidenavbar, dans magic things... lots of them are available and we NO LONGER support this

**Comment by EleoXDA** [comment]
> I got the rro from the old version and placed that in the right dir it's working as a temp fix but please could navbar be kept in support.

no
