### ISSUE TITLE
Trafic monitor doesn't work

### ISSUE THREAD

**Issue by Fefedu973** [siavash79/PixelXpert#717]
### Describe the issue

Trafic monitor doesn't work in the status bar and in the Qs (in the status bar it appears for one second and then leave)

### Steps to reproduce

1 try to enable trafic monitor
2 it doesn't work 

### Expected behavior

It should appears

### Your device setup (Please take some time to give correct information here)

- Google pixel 8 pro
- Android 14
- build UD1A.230803.041
- magisk 26.3
- 
![Screenshot_20231024-133040](https://github.com/siavash79/PixelXpert/assets/80718477/43ddc9d9-c7a7-41f3-9243-4139e96dbe4e)
- 
![Screenshot_20231024-133118](https://github.com/siavash79/PixelXpert/assets/80718477/53ac93f1-438f-432c-9bc8-9186e04e888f)
- lsposed 1.9.2
- 
![Screenshot_20231024-133204](https://github.com/siavash79/PixelXpert/assets/80718477/9a89257f-3aa6-4a62-869c-605776448326)

### Logs

After reproducing the issue as you said I went in lsposed and the log file was empty (I cleaned the logs before reproducing the issue)
![Screenshot_20231024-133511](https://github.com/siavash79/PixelXpert/assets/80718477/348fc979-2e9f-466e-b139-7d4100cfefd8)

**Comment by siavash79** [comment]
try reducing the traffic threshold of network monitor

**Comment by Fefedu973** [comment]
> try reducing the traffic threshold of network monitor

Ok thanks it morks
