### ISSUE TITLE
[Bug] 3 Button Navigation Button Order Borked

### ISSUE THREAD

**Issue by adrianmmiller** [siavash79/PixelXpert#719]
### Describe the issue

doesnt work since i changed to PixelXpert (fresh module install)

### Steps to reproduce

Same as always, i change the back and recent buttons, but they now do NOT change on screen, though the module claims they are set correctly.

Same OS version: A13 Derpfest

Screenshot after many reboots....

![Screenshot_20231025-223330_Pixel_Xpert 1](https://github.com/siavash79/PixelXpert/assets/123215709/ea63aa66-260e-45c8-8a70-9d6a4cc0665e)

### Expected behavior

THe button order should change

### Your device setup (Please take some time to give correct information here)

- Google Pixel 6 Pro
- A13 (Derpfest - long time user)
- Offical October Security Patch
- Magisk Alpha 26301 (second to latest, the latest Alpha HAS borks - some mount points were removed - im a long time tester and senior level)
- Same root apps and modules as always used, none that would interact.

**Comment by adrianmmiller** [comment]
found issue in ROM

**Comment by adrianmmiller** [comment]
please see updated comment above, also tested on previous version

dont ask me why this occurs....

**Comment by EleoXDA** [comment]
See compatibility in readme. Only stock pixel firmware is supported
