### ISSUE TITLE
Feature Request: Restore the ability to hide the navbar

### ISSUE THREAD

**Issue by EyeCantCU** [siavash79/PixelXpert#720]
What's on your mind?

I was curious if there are plans to restore the option to hide the navbar/gesture pill. It was a very useful feature as it increased overall screen real estate (especially while typing).

Is this feature implemented on any other app/mod/rom? please specify

It's been a part of AOSPMods for the last couple years or so I've used it. Speaking of which, I really appreciate the work that has gone into this project. It's made Pixel stock significantly more usable

**Comment by V3semir** [comment]
I was really disappointed to see the feature gone. Any reason for it being removed?

**Comment by kvn1351** [comment]
Same.

Custom icon shapes for the launcher was also removed :/

It's quite sad. The old version works on 14 but it's just a matter of time I suppose.
