### ISSUE TITLE
Aap Lock

### ISSUE THREAD

**Issue by moditjain9777** [siavash79/PixelXpert#721]
What's on your mind?
Is it possible to include app lock in the pixelxpert mods. I am using  pixel 7 pro and missing that one feature.

Is this feature implemented on any other app/mod/rom? please specify
I have seen this app lock in mostly all custom roms.

**Comment by EleoXDA** [comment]
There are many 3rd party apps available for that.

The main xposed rule is:
If you can find an app that does it, you don't need xposed method for that
