### ISSUE TITLE
[Bug] LineageOS 13, Non-Pixel phone.  Latest update crashes constantly and resets settings.  Some don't work.

### ISSUE THREAD

**Issue by EkriirkE** [siavash79/PixelXpert#723]
### Describe the issue

New update crashes SystemUI on open, and every time you click any option within.  It always comes back to where it left off but you can to endure 1 soft reboot each operation.

### Steps to reproduce

Sep 1 update of Lineage/Android13 on a OnePlus 7 phone

I updated to the new version of ~~AOSP Mods~~ Pixel Xpert a couple days ago.  All my AOSP customisations were gone, so I had to do everything all over again.

Launch app.
SystemUI crashes.
Click a section
SystemUI crashes.
Change an option
SystemUI crashes.
etc.

Changes seem to work, but it is a bit cumbersome.  Dashed battery icon no longer works, it shows full circle instead.  Colourful option no longer works.

Home screen randomly loses wallpaper, but lock screen is steady.  
Home screen/Trebuchet constantly loses icon shape setting (I keep it on rounded rectangle but it will reset to default (circle) every day, sometimes several times a day)

### Expected behavior

No crashes, or UI restarts except when applying settings.  Unrelated home/trebuchet options left untouched

### Your device setup (Please take some time to give correct information here)

OnePlus 7ro, LineageOS 13 September 01 patch
Magisk 26300
~~AOSP~~PixelXpert 3.1.0
LSposed Zygisk 1.9.2

**Comment by EleoXDA** [comment]
As you mentioned your ROM is incompatible. We can't fix issues on custom ROMs. Only stock pixel firmware
