### ISSUE TITLE
Colorize notification background based on app accent color

### ISSUE THREAD

**Issue by nhanntt0401** [siavash79/PixelXpert#730]
Hi Developer,

Could you help add the option to colorize the notification background based on the app accent color (e.g green for whatapps, blue for message app, purple for viber...)? This will make the notification center more vivid and easer to follow.

**Comment by EleoXDA** [comment]
PixelXpert is mainly for changes in function rather than theming and beautifying. You should request it in [Iconify](https://github.com/Mahmud0808/Iconify)
