### ISSUE TITLE
Feature Request: Add auto-brightness setting to QQS.

### ISSUE THREAD

**Issue by gentslava** [siavash79/PixelXpert#731]
It would be nice to have this option in QQS.
Also, due to the lack of auto-brightness in QQS and its presence in QS, the brightness adjustment panel flickers. It changes in size - it looks weird.
![Screenshot_20231106-102713_Chrome](https://github.com/siavash79/PixelXpert/assets/14369958/3df4304b-61c2-446c-8795-57ff9130c944)
![Screenshot_20231106-102721_Chrome](https://github.com/siavash79/PixelXpert/assets/14369958/2c229e39-1ad2-4f98-8dc4-63e4e51b678e)
![Screenshot_20231106-102736_Chrome](https://github.com/siavash79/PixelXpert/assets/14369958/1da6ae11-0785-453a-aef8-e703c572d61b)

**Comment by EleoXDA** [comment]
this is not for stock pixel firmware. If you want autobrightness button, there are apps in playstore like quick settings app by Simone Sestito
