### ISSUE TITLE
[Bug] "Allow screen recording from protected content" breaks screen recording on Android 13

### ISSUE THREAD

**Issue by purgnoop** [siavash79/PixelXpert#733]
### Describe the issue

when enabled, the "allow screen recording from protected content" setting breaks screen recording completely when enabled

### Steps to reproduce

1. Enable the option in PixelXpert
2. Attempt to start screen recording from qs tile.
3. Screen recording will fail.

### Expected behavior

expected screen recording to start

### Your device setup (Please take some time to give correct information here)

Google Pixel 7a (Lynx)
Stock September patch  Android 13 TQ3A.230901.001
Google Play System Update 1 October
Magisk 26.3
Magisk modules
![Screenshot_20231107-105741](https://github.com/siavash79/PixelXpert/assets/78469485/136116f6-ef69-4e4a-b1fe-574919976107)

Root access apps
![Screenshot_20231107-105313](https://github.com/siavash79/PixelXpert/assets/78469485/4a78e037-ec8c-4def-9370-390feb77ebfe)

Lsposed 1.9.2(7024)
Lsposed modules 
![Screenshot_20231107-105607](https://github.com/siavash79/PixelXpert/assets/78469485/f7c3b6b1-d0a5-48be-a4f9-d19d71a1a884)

Additional
This seems related, can provide a proper logcat if needed
![Screenshot_20231107-102003](https://github.com/siavash79/PixelXpert/assets/78469485/e44f4293-f14b-421f-b612-070fd72c9406)

### Logs

[LSPosed_2023-11-07T12_31_59.583923.zip](https://github.com/siavash79/PixelXpert/files/13274448/LSPosed_2023-11-07T12_31_59.583923.zip)
Nothing showed after I cleared logs, but here they are

**Comment by EleoXDA** [comment]
Please recheck. Firstly remove all modules from magisk and lsposed. Then reboot. Then check again please. If fails, please report lsposed logs with no other modules present

**Comment by EleoXDA** [comment]
BTW repainter doesn't work good on A14 and causes lots of troubles. I advise you to remove it
