### ISSUE TITLE
[Bug] About the hidden functions of navigation bar

### ISSUE THREAD

**Issue by fuzhengqu** [siavash79/PixelXpert#737]
### Describe the issue

The first time I used Pixel Xpert, I found that there was no option to turn off the navigation bar in the navigation bar settings. But I used another AOSP mods, which provides this function. The interface looks very similar to pixel xpert. Is this also developed by you? If so, why does pixel xpert not provide this option? There is another problem. When the hidden navigation bar function is turned on, the two buttons under the keyboard also disappear at the same time. What I want is to just make the navigation bar disappear without touching the keyboard.

### Steps to reproduce

The first time I used Pixel Xpert, I found that there was no option to turn off the navigation bar in the navigation bar settings. But I used another AOSP mods, which provides this function. The interface looks very similar to pixel xpert. Is this also developed by you? If so, why does pixel xpert not provide this option? There is another problem. When the hidden navigation bar function is turned on, the two buttons under the keyboard also disappear at the same time. What I want is to just make the navigation bar disappear without touching the keyboard.

### Your device setup (Please take some time to give correct information here)

Pixel5 android 14

**Comment by EleoXDA** [comment]
AOSPMods is old name of PixelXpert.

Those were discontinued. Thanks Google
