### ISSUE TITLE
SystemUi Crash[Bug] 

### ISSUE THREAD

**Issue by gautambishnoi** [siavash79/PixelXpert#738]
### Describe the issue

Crashing on crDroid Rom

### Steps to reproduce

1: Install version3.00 or 3.1
2: reboot
3: As soon as root permission is granted systemui Crashes.
4: Pauseing the AospMod/PixelXpert app makes the system stable again.
5: uninstalling and rebooting removes the issue.

### Your device setup (Please take some time to give correct information here)

-Android 13
-CrDroid Rom
-Magisk (Latest)
-LSposed

**Comment by EleoXDA** [comment]
Crdroid not even supported. Read ReadMe file
