### ISSUE TITLE
Date format (left/right of clock text) seems to not support spaces, punctuation as expected/useful?

### ISSUE THREAD

**Issue by stilez** [siavash79/PixelXpert#739]
### Describe the issue

$G<format> seems to not actually support spaces and punct. properly (if it does I cant find a way to do it)

## Spaces and punctuation within body of string cause misformatting

Set a custom text say left of date

$GEddMM -> "Tue14Nov"  so it basically works

But

$GE dd/MM
$G"E dd/MM"
$GE_dd/MM
$GE\ dd\/MM

all fail to produce the expected output.  The date formatting fails and I get literal text `Tue dd/MM` or similar not the actual date.

There seems no way to put spaces or punctuation such as `Tue 14 Nov` or `Mon, 14/11`, Ive tried numerous combinations which should work with Java date format, but none do. 

This probably isn't device dependent as this will be pure java handling of the input string within the sw.  Tested with latest 3.1.0, LSPosed 1.92. Im guessing will either reproduce or not, or else there is extra formatting info that I couldnt find when googling Java DateFormat.  If there is a way, then "Google DateFormat" as suggested isn't finding it, since that links to example strings that just contain literal spaces/punctuation, not any kind of escaped or hex alternative.

## Spaces at start or end of string are ignored

Would be very useful if leading/trailing spaces not cut, so that extra spacing can be added, eg between "Tue 14/11" on left and the time, or between the time and "2023-11-14" on the right.  Allowing leading/trailing spaces would allow the status display to output such as left text + clock `Tue 14/11  HH:mm` correctly.

If those spaces are wrongly inserted, I think the user will spot and remove them, so there's no need to trim/strip in sw.

### Expected behavior

See above

### Your device setup (Please take some time to give correct information here)

See above, but suspect extremely likely not relevant.

### Logs

No log.

Issue is in text processing logic, where a formatting of a string isnt as expected.  
It's not the kind of issue that will create a bug report.

**Comment by EleoXDA** [comment]
Wrong. You need to separate them

E.g. $GMMM $Gdd will give you "Nov 16"
