### ISSUE TITLE
Features request.

### ISSUE THREAD

**Issue by UniverseCodex01** [siavash79/PixelXpert#740]
What's on your mind?

😑Lock screen:

1) A feature that allows the users to hide completely the lock screen status bar.

😐Notifications:

1) A feature that allows the users to configure notifications expand, for example: All notifications will be collapsed, All notifications will be expanded or Expand top notification.

Is this feature implemented on any other app/mod/rom? please specify

😑1) Feature was implemented on Spark OS     13.5 if I remember correctly but it's not an usual feature.

😐1) Idk if the feature was previously implemented on other app/mod/rom.

Note:

Thanks so much for your mod, it's very useful, personally, I really hate the AOSP lock screen but with your module I can reduce it.

**Comment by EleoXDA** [comment]
1. use iconify
2. already available

**Comment by UniverseCodex01** [comment]
> 1. use iconify
> 2. already available

Here's the second option available?

**Comment by UniverseCodex01** [comment]
> > 1. use iconify
> > 2. already available
> 
> Here's the second option available?

Iconify doesn't have any type of features related to auto expand of notifications or hide of lock screen status bar.

**Comment by UniverseCodex01** [comment]
> 1. use iconify
> 2. already available

Thanks so much, iconify it's also a great module. 😊👍 But I can't found the option to customise auto expand of notifications.

**Comment by EleoXDA** [comment]
> > 1. use iconify
> > 2. already available
> 
> Here's the second option available?

Collapsing and expanding all notifications is already available. You can also expand/collapse one by one

**Comment by EleoXDA** [comment]
> > 1. use iconify
> > 2. already available
> 
> Thanks so much, iconify it's also a great module. 😊👍 But I can't found the option to customise auto expand of notifications.

You can also directly open pin/password screen without getting to lockscreen notifications/clock page with PixelXpert.

For more information PLEASE check wiki page in our repository
