### ISSUE TITLE
Remove screen on/off animation

### ISSUE THREAD

**Issue by gzyguo** [siavash79/PixelXpert#743]
What's on your mind?
I use color inversion as dark theme but the screen off animation flash screen full of white(under inversion) before screen on/off, 

Is this feature implemented on any other app/mod/rom? please specify
Remove the animation, and make the screen black even under color inversion.

**Comment by EleoXDA** [comment]
Use dark mode instead of color inversion. This request makes no sense. Instead, you can just disable animations overall.
