### ISSUE TITLE
[FEATURE REQUEST] AOD/ambient display active when charging

### ISSUE THREAD

**Issue by b02860de585071a2** [siavash79/PixelXpert#744]
A feature I miss from my Samsung devices is the ability to show charging information on the AOD/ambient display, even when AOD itself is (globally) disabled. 

Currently, PixelXpert allows the user to show the ambient display with a tap or lift, as well as showing charging information on the lock screen. 

I would like to be able to toggle a setting to extend that functionality, which would show charging information on the ambient display (when the device is plugged in/wirelessly charging). This would not require enabling AOD 24/7 :)

Is this feature implemented on any other app/mod/rom? please specify

OneUI 5+

**Comment by EleoXDA** [comment]
Is this feature implemented on any open source custom ROM/app/mod?

**Comment by b02860de585071a2** [comment]
> Is this feature implemented on any **open source** custom ROM/app/mod?

It's been quite some time since I've been involved in the Android modding scene, so I can't give a useful answer to this. 

I vaguely remember it being a feature in a ROM I ran on my Nexus 5X (or 6P?) back in the day, but again I realize that's not helpful as a developer.

**Comment by donjamal** [comment]
Would be even better to also have schedule for aod

**Comment by ziddey** [comment]
May vary for other phones, but on the pixel 7, secure setting `doze_always_on` controls this. Currently using tasker to enable when charging (power event any).

**Comment by b02860de585071a2** [comment]
Works perfectly on canary 311+, thank you!

**Comment by ziddey** [comment]
pixel7 a14qpr2, it seems to only show the fingerprint icon until I toggle AOD on and back off in android settings. Need to do this every boot.
