### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Den555By** [siavash79/PixelXpert#745]
1.Light theme is not working properly in the system(not matching colors to the light mode of the system), sometimes it won't turn on. As you can see in the screenshot, the bottom of the notification panel is still black. The clock app also uses a dark theme so you need to add a setting for this app too.
2.Ability to hide Google search bar, change the date format in the "most important" widget, movement across the screen.
3.Ability to completely remove the application menu and instead use only the list of applications on the home screen.
4.Battery style is not working
5.Ability to remove the exclamation mark of the mobile network when it is not enabled.

**Comment by Den555By** [comment]
1.The clock app also uses a dark theme so you need to add a setting there too
![Screenshot_20231201-165315_Pixel_Xpert 1](https://github.com/siavash79/PixelXpert/assets/41540074/e428b4c4-c631-491d-b311-1191c4470dcf)

**Comment by EleoXDA** [comment]
Only stock pixel firmware supported. Read ReadMe file

**Comment by Den555By** [comment]
Just had to install the module for magisk and not for lsposed as here in the downloads, so it didn't work. But new features (not the bugs I described) would be nice to add please!

**Comment by EleoXDA** [comment]
This is not planned. Please stop editing the feature request. This is only for stock pixel firmware.
