### ISSUE TITLE
[Bug] Disable fingerprint when screen off does not work, if AOD (Always On Display) is enabled

### ISSUE THREAD

**Issue by Senliast** [siavash79/PixelXpert#746]
### Describe the issue

When turing off option "Allow fingerprint when screen disabled" under "Miscelanious", and the AOD is enabled - the fingerprint icon on the AOD (its fingerprint under display) will turn into a lock icon but will continue to react to finger and wake / unlock the phone.

### Steps to reproduce

1. Turn off "Allow fingerprint when screen disabled" under "Miscelanious".
2. Enable Always On Display.
3. Setup fingerprint unlock.
4. Lock the phone.
5. Put finger onto the fingerprint sensor.

### Expected behavior

The fingerprint should not react and not wake or unlock the phone.

### Your device setup (Please take some time to give correct information here)

- POCO F2 Pro (but with AOSP ROM)
- PixelExperience TQ3A.230901.001.B1 PixelExperience_Plus_lmi-13.0-20230927-1336-OFFICIAL
- Android 13
- Magisk 26.4
- LSPosed 1.9.2 (7024)
- LSPosed modules: UpdateLocker
- Magisk modules: SQLite3

### Logs

[LSPosed_2023-12-02T15_47_14.548450.zip](https://github.com/siavash79/PixelXpert/files/13536574/LSPosed_2023-12-02T15_47_14.548450.zip)

**Comment by EleoXDA** [comment]
Allow fingerprint when screen disabled is for devices that have capacitive fingerprint scanners. not for in-display ones

**Comment by EleoXDA** [comment]
also, read ReadMe file to see which ROMs are supported.

NONE of the custom ROMs are supported. This mod is ONLY for PIXEL STOCK FIRMWARE. As name dictates, PixelXpert
