### ISSUE TITLE
[FEATURE REQUEST] Bring back 2 button navigation or alternative 

### ISSUE THREAD

**Issue by lnp5131** [siavash79/PixelXpert#753]
What's on your mind?
2 button navigation was first introduced in Pixel 2 on Android 8 then it left when Android 12 released. It featured a back button and a home button with the gestures swiping from side to side would switch apps like it does with the current one and swiping up shows the app switcher menu. Tapping the home button would go to home like in the 3 button navigation. I believe it brought the best of both navigation systems. The gestures for bringing up the app switcher menu requires you to hold which bars people from swapping away from 3 button while the side to side gesture for switching apps is incredibly useful. 

Is this feature implemented on any other app/mod/rom? please specify
Android 8-11 Pixel stock ROM

**Comment by EleoXDA** [comment]
this was failure. Even on the eyes of Google. It literally had lesser of both 3-button and gesture navigation

**Comment by EleoXDA** [comment]
> Would it be possible to tap the pill to go to home and modify the gesture for the app switcher to not have the hold delay?

Try and see. I dont understand what you need exactly.

**Comment by lnp5131** [comment]
> > Would it be possible to tap the pill to go to home and modify the gesture for the app switcher to not have the hold delay?
> 
> Try and see. I dont understand what you need exactly.

I meant as a replacement or addition to its current state. As of right now it looks like this

Swipe up - home
Hold and swipe up - app switcher

I'm looking for

Tap pill - home
Swipe up - app switcher

As of the latest Android beta, tapping the pill does nothing.

**Comment by EleoXDA** [comment]
> > > Would it be possible to tap the pill to go to home and modify the gesture for the app switcher to not have the hold delay?
> > 
> > 
> > Try and see. I dont understand what you need exactly.
> 
> I meant as a replacement or addition to its current state. As of right now it looks like this
> 
> Swipe up - home Hold and swipe up - app switcher
> 
> I'm looking for
> 
> Tap pill - home Swipe up - app switcher
> 
> As of the latest Android beta, tapping the pill does nothing.

It wouldn't. Pill is for GESTURE. Not tap. Tap is obsolete and unfunctional. It was years ago when there was tap/double tap/long tap options. They are now replaced with gestures.
