### ISSUE TITLE
Feature Request: ability to set custom system UI fonts

### ISSUE THREAD

**Issue by squeaktoy** [siavash79/PixelXpert#755]
What's on your mind?
I would like to be able to set a custom system UI font.
This is a really useful and helpful feature from AOSPMods that seems to be missing in PixelXpert. I noticed when upgrading to PixelXpert that I cannot read comfortably anymore because I don't have my custom font anymore, so I was forced to downgrade back to AOSPMods.

Is this feature implemented on any other app/mod/rom? please specify
AOSPMods

**Comment by siavash79** [comment]
It's not planned anymore

**Comment by EleoXDA** [comment]
Just use any CFI or OMF magisk module zip with any custom font you have in mind

**Comment by squeaktoy** [comment]
And no, changing font size/DPI in settings is not a good fix because
it changes the proportions and doesn't look right to me
