### ISSUE TITLE
Feature Request: All frequency bands for mobile hotspot in all regions

### ISSUE THREAD

**Issue by bzz11g** [siavash79/PixelXpert#758]
Please add an option to unblock Internet distribution in the 5 GHz and 6 GHz frequency range for all regions
Settings > Network & Internet > Hotspot & tethering > Wi-Fi hotspot > Speed & compatibility
![photo_2023-12-11_21-50-48](https://github.com/siavash79/PixelXpert/assets/1549909/0264bd5a-52a8-4c91-9873-b72692c7594e)

Is this feature implemented on any other app/mod/rom? please specify
as some say this feature is available in almost all Chinese phones, even the cheapest ones, but unfortunately I can't check this because I only have a Pixel6 and stock firmware

Thank you!

**Comment by siavash79** [comment]
I might be _totally_ wrong, but what I've seen leads to native codes, and if it's so, I'm not able to mod it
