### ISSUE TITLE
App startup crash

### ISSUE THREAD

**Issue by bigjackwww** [siavash79/PixelXpert#759]
### Describe the issue

App startup crash and force close

### Steps to reproduce

App does not open it of latest pixelXpert stable 3.2.0 
As for the version before it 3.1.0, it opens, but after a few seconds I receive a message of force close of app

### Your device setup (Please take some time to give correct information here)

Mi 9 lite/ Mi CC9
Lineageos 20 
android 13 
Security patch of android 5 december 2023
magisk 26.4 
LSPosed 1.9.2

**Comment by EleoXDA** [comment]
Please read ReadMe file to see which ROMs are supported
