### ISSUE TITLE
Feature request: Charging info in Quick Settings

### ISSUE THREAD

**Issue by ServerBBQ** [siavash79/PixelXpert#761]
I think it would be a great idea to have an option to show charging info in quick settings just like how you can have the charging info on the lock screen.

It could probably look something like this:
<img src="https://github.com/siavash79/PixelXpert/assets/76498501/c948cbd0-b987-4f4f-a9a4-c7c55fc66842" alt="" width="200"/>

**Comment by EleoXDA** [comment]
I dont think it is even possible to implement a textbox in that region

**Comment by siavash79** [comment]
Might be possible. Let's see
