### ISSUE TITLE
Hide navbar not working [Bug] 

### ISSUE THREAD

**Issue by robotfishe** [siavash79/PixelXpert#762]
### Describe the issue

Hide navbar option doesn't work; navbar remains visible. Changing to gesture navigation mode in system settings sometimes works (pill is hidden), but then it comes back after using any fullscreen app.

### Steps to reproduce

Install latest canary build, select hide navbar

### Expected behavior

Navbar should be hidden

### Your device setup (Please take some time to give correct information here)

Pixel Fold
Android 14 QPR 2 beta

### Logs

I see this over and over in the logs, with nothing relevant above it:

[ 2023-12-18T02:18:55.287        0:   915:  2266 E/LSPosedService  ] performReceive: 
DeadSystemException: The system died; earlier logs will point to the root cause

**Comment by EleoXDA** [comment]
Which app version are you using?

**Comment by robotfishe** [comment]
> Which app version are you using?

I've tried canary 310, 313, and 314.

**Comment by EleoXDA** [comment]
Do you see navbar region with navbar pill?

Please recreate your report with filling all the information in bugreport. You have missed many points that are important for troubleshooting

When you create the new bugreport with all the information, provide also a screenshot with what you observe with and without the option. Also be sure to disable all the other modules in magisk AND xposed before creating correct bugreport (as already written there)
