### ISSUE TITLE
"Always Expand notifications" 

### ISSUE THREAD

**Issue by StuartJAtkinson** [siavash79/PixelXpert#764]
I'm trying to be calm but Android 13 seems to have removed all notification functionality unless you press the expand arrow... On every notification...
This is horrifically poor design I see years ago a mod package called Gravity Box had a fix to "Always Expand notifications". This seems necessary on a basic level I can't believe the lack of comments about it. Maybe it's just the PixelExperience? Needs to be undone to allow notifications to be notifications rather than a strange header with no information.

**Comment by EleoXDA** [comment]
Not sure whether we will continue adding stuff to A13

**Comment by siavash79** [comment]
Expand notifications is already added in the latest canaries
