### ISSUE TITLE
Feature Request: Splitting Internet Tile Into Seaparate Data and Wifi Toggle Tiles

### ISSUE THREAD

**Issue by EgoGone** [siavash79/PixelXpert#765]
What's on your mind?
If possible, please add back the ability to split the Internet tile back into separate Wifi and Data tiles.

Is this feature implemented on any other app/mod/rom? please specify
This was present in AOSP 2.4.1 I believe. This is also the primary functionality of the app Better Internet Tiles, but that app is more clunky and keeps giving superuser notifications throughout the day.

**Comment by EleoXDA** [comment]
> What's on your mind? If possible, please add back the ability to split the Internet tile back into separate Wifi and Data tiles.
> 
> Is this feature implemented on any other app/mod/rom? please specify This was present in AOSP 2.4.1 I believe. This is also the primary functionality of the app Better Internet Tiles, but that app is more clunky and keeps giving superuser notifications throughout the day.

use BetterInterntetTiles app.
