### ISSUE TITLE
Feature Request: Show icon app on statusbar when notification headsup

### ISSUE THREAD

**Issue by fajarpicisan** [siavash79/PixelXpert#766]
I'm using POS right now, when i using awaken a14,
I see the icon app appear next to the application name when it's getting headsup notification
Idk that's feature of awaken or not, but i interested to bring it on.

Sorry for my bad english 🙏

**Comment by EleoXDA** [comment]
not possible unless you remove dual statusbar

**Comment by fajarpicisan** [comment]
Never used dual statusbar sir 🙏

**Comment by EleoXDA** [comment]
> Never used dual statusbar sir 🙏

then it is your ROM incompatibility issue
