### ISSUE TITLE
Feature Request : Hide QS on secure lockscreen

### ISSUE THREAD

**Issue by DylanAkp** [siavash79/PixelXpert#767]
What's on your mind?
The idea is to be able to disable quicksettings on lockscreen
For example, you won't be able to put airplane mode if the device is locked

Is this feature implemented on any other app/mod/rom? please specify
Haven't seen any app or mod
But seen CrDroid has the feature

**Comment by EleoXDA** [comment]
you basically should not hand your device to unknown people. even with "secure" lockscreen a person can easily force power down your device, boot in recovery, wipe it and sell it to someone else.

So dont overestimate the power of "secure" lockscreen, as when you sometimes need a quick toggle in qs, it will bite you back.

P.S. You can use Iconify by @Mahmud0808 that has that function as far as I recall.

**Comment by DylanAkp** [comment]
Yes, it's not a "perfect security" and doesn't allow you to hand your device to anyone, we agree on that.

Thanks for the tip, I will check Iconify
