### ISSUE TITLE
Feature Request : Please add an option to increase qs tile size (not talking about label one) (im taking about the qs tile which is for example wifi button, bluetooth button etc)

### ISSUE THREAD

**Issue by parasgargexx20** [siavash79/PixelXpert#768]
Please add an option to increase qs tile size (not talking about label one) (im taking about the qs tile which is for example wifi button, bluetooth button etc). (This feature exist in iconify)

**Comment by parasgargexx20** [comment]
![Screenshot_20231224-230704_Iconify](https://github.com/siavash79/PixelXpert/assets/102552831/8388e49a-b66f-497d-abeb-feb86d6a9ccb)

**Comment by EleoXDA** [comment]
Use Iconify. Why have two mods with same tweaks?
