### ISSUE TITLE
Google Dialer 

### ISSUE THREAD

**Issue by bigjackwww** [siavash79/PixelXpert#769]
### Describe the issue

Call recorder announcement no longer work

### Steps to reproduce

Call recorder announcement no longer work on google dialer version 120.0.585477676

### Your device setup (Please take some time to give correct information here)

lineageOS 20
android 13
december 2023
magisk 26.4
LSposed 1.9.2
pixelxpert canary-316

**Comment by EleoXDA** [comment]
Lineage not supported. Please read ReadMe file
