### ISSUE TITLE
Feature Request : Can u add a feature to disable all mods/overlays just like iconify so its easier for users to disable any accidentally applied mod which they might have forgot about

### ISSUE THREAD

**Issue by parasgargexx20** [siavash79/PixelXpert#770]
Can u add a feature to disable all mods/overlays just like iconify so its easier for users to disable any accidentally applied mod which they might have forgot about.

![IMG_20231225_112542_149](https://github.com/siavash79/PixelXpert/assets/102552831/52e5134b-814c-4299-9f0b-8648e392c8e7)

**Comment by EleoXDA** [comment]
You can reset module from 3dot menu
