### ISSUE TITLE
Battery Drain on Android 13 (Arrow OS) [Bug] 

### ISSUE THREAD

**Issue by ROLAQOSTA** [siavash79/PixelXpert#771]
### Describe the issue

Significant Battery Drain after upgrading to "pixel expert" 

### Steps to reproduce

![Screenshot_20231225-163655_Franco_Kernel_Manager](https://github.com/siavash79/PixelXpert/assets/34136176/64511dc4-ffef-4c38-ac92-675189773d28)

For some reason, Pixel Expert causes com.android.systemui to consume a lot of CPU power causing significant Battery drain.
Never experienced this while I used "AOSP" mods

### Expected behavior

System UI isn't supposed to consistently consume above 10% of my CPU power.

### Your device setup (Please take some time to give correct information here)

![Screenshot_20231225-164314_Settings](https://github.com/siavash79/PixelXpert/assets/34136176/38aaff69-957a-4b03-ac71-1889ed3ce107)

here

**Comment by EleoXDA** [comment]
You need to read ReadMe
