### ISSUE TITLE
Feature request: change the temperature ($T) status bar option colour depending on choosen temperature similar to the battery icon colours 

### ISSUE THREAD

**Issue by FurhadTheNerd** [siavash79/PixelXpert#772]
What's on your mind?
same as the title!
the could be a great addition for me and other people depending on their usage
I don't charge my phone when the battery is above 35c, when the readings on my status bar start to flash or turn red? this will be my warning sign

Is this feature implemented on any other app/mod/rom? please specify
probably not, I'm unaware

**Comment by EleoXDA** [comment]
You can write a script for Automagic or Tasker. This way you will not depend on visual clue
