### ISSUE TITLE
[Bug] Right margin spacing for status bar broken maybe???

### ISSUE THREAD

**Issue by neomoth** [siavash79/PixelXpert#773]
### Describe the issue

After messing with the padding for the status bar, the battery percentage is now seemingly more left than it should be when comparing to the dropdown menu when padding option set to default

### Steps to reproduce

1. Tamper with status bar padding
2. Attempt to reset it
3. It remains a tad bit to the left anyways

### Expected behavior

The rightmost status bar margin should match that of the dropdown menu

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7a
- Android 14
- Latest security update on December 5th 2023
- Magisk version 26.4
- Apps with root access:
-> Termux
-> YouTube ReVanced Manager
-> PixelXpert
- Installed Magisk/Zygisk Modules:
-> PixelXpert v3.2.0
-> Universal SafetyNet Fix v2.3.1-MOD_3.0
-> LSPosed v1.9.2 (7024)
- LSPosed version: (see above)
- LSPosed Modules: N/A

### Logs

[LSPosed_2023-12-26T10_59_36.639516.zip](https://github.com/siavash79/PixelXpert/files/13772494/LSPosed_2023-12-26T10_59_36.639516.zip)
Seemingly no issues in the log but you cen see the padding issue visually here:
![Screenshot_20231226-110209](https://github.com/siavash79/PixelXpert/assets/69372252/feba2873-3dea-4e85-ac50-0f55c050d6df)
![Screenshot_20231226-110226](https://github.com/siavash79/PixelXpert/assets/69372252/328d161b-0fb6-48c8-a21a-680ca76b5661)
![Untitled2_20231226110638](https://github.com/siavash79/PixelXpert/assets/69372252/0679eec6-8afc-4732-9484-4ff0ea62608e)

**Comment by EleoXDA** [comment]
Depends whether you adjusted padding on STATUSBAR page or QUICK SETTINGS PANEL page. I am definitely sure there is no margin option on latter. So, no. They shouldn't match

**Comment by EleoXDA** [comment]
Wait. You mean it is still not working after setting it back to default?

**Comment by neomoth** [comment]
Yeah even after setting to default the margin is still messed up

**Comment by neomoth** [comment]
In fact, setting it to full min/max actually moves the right side left more (100.5%) as opposed to 100%, though neither align it back to where it should normally line up

**Comment by neomoth** [comment]
Here's a photo ot that occuring: 
![Untitled4_20231226125209](https://github.com/siavash79/PixelXpert/assets/69372252/7f22aa86-215b-4f62-bc78-329ead9fc3a4)

**Comment by EleoXDA** [comment]
As far as I know, -0.5 and 100.5 should be stock values

**Comment by neomoth** [comment]
Well something is causing the spacing to be off. If there's something you can change to fix it or allow for it to move more to the right that would be greatly appreciated

**Comment by EleoXDA** [comment]
Well. First thing first, qs view is completely different from the statusbar. Secondly, you can see that this effect doesn't come from pixelXpert if you just reset app settings or even turn off PixelXpert and reboot. 

You can still add this as a feature request, but this would be probably denied because as I put above, statusbar view is completely different of quick settings panel.

And lastly, before home statusbar shifts to qs statusbar, you get qs toggles - so there is no direct passage from home statusbar to qs statusbar that would look weird
