### ISSUE TITLE
Feature Request: Ability to remove search bar from home screen

### ISSUE THREAD

**Issue by toddhow** [siavash79/PixelXpert#774]
The non-removable search bar on the stock launcher has bothered me since I got my phone is there a way that it could be removed with PixelXpert?

![Screenshot_20231228-184702.png](https://github.com/siavash79/PixelXpert/assets/35154979/5a1ee3f9-8cc0-43df-b90a-138577f9bec8)

**Comment by EleoXDA** [comment]
Use pixel launcher mods by KieronQuinn
