### ISSUE TITLE
System UI crash when disabling airplane mode

### ISSUE THREAD

**Issue by Thebear375** [siavash79/PixelXpert#777]
### Describe the issue

So I had disable modules and boot into safe mode. After rebooting from safe mode device is in airplane mode, if I try to disable airplane mode by any method, system UI immediately crashes and screen goes black. This is the 3rd time this has happened after having to boot into safe mode.i cannot get out of airplane mode.

### Steps to reproduce

Had to disable magisk mods in safe mode. When rebooting back to system after modules are disabled from safe mode, tapping airplane mode toggle in qs tiles, enabling data thru qs tiles or settings, or Bluetooth thru qs tile or settings causes immediate system UI crash and black screen. Only way to boot back up is in safe mode and this just is an infinite loop. I have to wipe device and start fresh.

### Expected behavior

After booting into safe mode to disable modules and rebooting into system, I should be able to disable airplane mode and have all functions working.

### Your device setup (Please take some time to give correct information here)

Google pixel 6 pro Android 14 December patch
Magisk 26.4 stable
Lsposed 1.9.2(7055) Zygisk
I know I have a bunch of magisk modules, they are shown in the screenshots. Lsposed log has a big system UI error from PixelXpert that I believe is the cause.
![Screenshot_20240103-015503](https://github.com/siavash79/PixelXpert/assets/30216228/66b676c1-eb7a-41a6-a420-cb6195635896)
![Screenshot_20240103-015529](https://github.com/siavash79/PixelXpert/assets/30216228/b35d0893-fb21-4069-a023-d2b993351967)
![Screenshot_20240103-015534](https://github.com/siavash79/PixelXpert/assets/30216228/5f416f61-f014-492e-b165-af0606d47b5e)
Lsposed modules are PixelXpert, Iconify, and DarQ.

### Logs

All modules were disabled after booting into safe mode. This is the only lsposed log I have as I can't catch the issue because of system UI crash loop. If this isn't the issue, I will have to investigate further, but I hope you can take a look and see what is causing that error from PixelXpert. Thanks.
[LSPosed_2024-01-03T01_43_14.276139.zip](https://github.com/siavash79/PixelXpert/files/13816403/LSPosed_2024-01-03T01_43_14.276139.zip)

**Comment by EleoXDA** [comment]
I am also on pixel 6 December update and have no such issue with PixelXpert. I am definitely sure it is not related to PixelXpert. And if you are using Iconify on Dec patch, hopefully you know that it is NOT compatible fully with it and causes bootloop when you change ANYTHING in QS styling. So, reset your Iconify and disable all the mods related to QS there and all will be fine.

**Comment by Thebear375** [comment]
Iconify isn't the issue. I haven't touched qs tiles at all in Iconify. The only way I can get this to happen is if I need to disable all modules and boot into safe mode. If that happens, this issue has come up 3 times where I had to wipe my device. Only error in log is from PixelXpert and it has to do with system UI. Now I'm not blaming this module, but could you at least take a look at the error that PixelXpert is causing in lsposed. 
If I could trigger the need to boot into safe mode and have the issue happen where system UI crashes didn't make the device unusable, I could figure it out myself. Unfortunately this isn't possible and I'm left with having to wipe my phone everytime.

**Comment by EleoXDA** [comment]
> Iconify isn't the issue. I haven't touched qs tiles at all in Iconify. The only way I can get this to happen is if I need to disable all modules and boot into safe mode. If that happens, this issue has come up 3 times where I had to wipe my device. Only error in log is from PixelXpert and it has to do with system UI. Now I'm not blaming this module, but could you at least take a look at the error that PixelXpert is causing in lsposed. If I could trigger the need to boot into safe mode and have the issue happen where system UI crashes didn't make the device unusable, I could figure it out myself. Unfortunately this isn't possible and I'm left with having to wipe my phone everytime.

1. You dont need to wipe anything. Booting to safe mode and disabling module afterwards is easy and doesnt require any wiping.
2. The logs you present include 11 magisk modules. Some are even not a14 compatible. I dont even know how many LSPosed modules. Disable all (magisk and xposed modules). Remove all other than PX, reboot. Enable PX (in magisk and lsposed). Reboot. Reproduce and send logs.

**Comment by Thebear375** [comment]
All other modules disabled. Link to new lsposed logs after system UI crash with PixelXpert only module installed. https://drive.google.com/file/d/1RknFSXOk4CwT7VVJEKEGBsiCFB4bj1zM/view?usp=drivesdk

**Comment by EleoXDA** [comment]
> All other modules disabled. Link to new lsposed logs after system UI crash with PixelXpert only module installed. https://drive.google.com/file/d/1RknFSXOk4CwT7VVJEKEGBsiCFB4bj1zM/view?usp=drivesdk

![image](https://github.com/siavash79/PixelXpert/assets/27622683/073c4b0c-b35b-4334-953c-b1b5acaec88c)

Please make it at least public or accessible with link

**Comment by Thebear375** [comment]
Sorry, it should be available now. https://drive.google.com/file/d/1RknFSXOk4CwT7VVJEKEGBsiCFB4bj1zM/view?usp=drivesdk
