### ISSUE TITLE
A14 lock screen left right corner shortcut toggled on, add changeing icon background color

### ISSUE THREAD

**Issue by Lokikikihaha** [siavash79/PixelXpert#778]
As in original A14, when the lock screen left right shortcut icon being toggled on, the short icon background color will change from black to theme colour users set, but once applied PixelXperrt, this function cannot be customized, please add this feature. Thank you so much Siavash79.

**Comment by EleoXDA** [comment]
Please show screenshots with your explanation. It is hard to understand what you mean

**Comment by Lokikikihaha** [comment]
![Screenshot_20240104-160051](https://github.com/siavash79/PixelXpert/assets/137397303/bc8dbf05-9ce3-472e-a2b0-da0905e7f318)
This is the screencap when I disable pixel xpert, I toggled on silent mode on lock screen , the button turn red

![Screenshot_20240104-155714](https://github.com/siavash79/PixelXpert/assets/137397303/37f5bc8e-090b-4f4f-9e8c-538a59466a42)

This is the screencap when I disable pixel xpert, I toggled off silent mode on lock screen , the button turn black again

But when I enable Pixel xpert, no matter silent mode toggled on or off , the icon stay like this, apologize for my poor English presentation 🙏, and thanks once again

**Comment by EleoXDA** [comment]
Which ROM is it? Which android version? Which security patch date?

**Comment by Lokikikihaha** [comment]
A14 , with latest security patch (12/2023), official rom (magisk + lsposed only)

**Comment by Lokikikihaha** [comment]
Thank you so much 😊
