### ISSUE TITLE
[Feature] My feature request and wish list

### ISSUE THREAD

**Issue by srt54558** [siavash79/PixelXpert#781]
Hello dear PixelXpert developers!
First off, I want to say how great the app is! I love it!

Now, the only problems I encountered is that sometimes when I swipe down QS, it stutters. The same when I unlock the phone with my fingerprint while touching the phone once to show AOD. It just stutters and hangs for a split second. Also on the Lockscreen, the detailed charging information is not shown or the text is too long to be shown, but on AOD the information is displayed.

Now to my Feature wishlist, because I don't want to spam the project with multiple feature requests:
-Material you Quick Access icons on the Lockscreen
-Material you fingerprint icon on LS
-Change background color of shortcuts on LS and fingerprint icon
-On QS show seconds when the QS is expanded and shows the clock bigger
-Ability to disable the estimated time till the battery runs out, shown on expanded QS
-Make the Android build number text wider (e.g. have the width to do edit button for the tiles) when a custom text is applied
-Custom Turn off menu options like "reboot to bootloader" or "activate flashlight"
-Tap punch hole camera to launch app or flashlight
-Show AOD on single tap, and Lockscreen on double tap (like on Samsung) (I have AOD disabled)
-Double Tap on/off button for custom action (such as opening Google wallet to pay (but only do this if the phone is unlocked of course))
-Show network activities next to the wifi icon only on expanded QS panel
-100 (or let the user choose) volume steps
-Custom DHCP and DNS server (or a DNS pihole or traffic analyser) that runs on the hotspot IP and can adjust some settings (It does indeed work with Servers Ultimate Pro, but I always have to change the IP address because every reboot changes it)
-Hotspot Mac address filtering
-Tile for enabling/disable data transfer on the USB port, so the phone can safely be used on public changing cables (like USB condom, but implemented)
-Setting a display refresh rate for certain apps
-Setting max charging Speed and max charging percentage 

Is this feature implemented on any other app/mod/rom? please specify
I have a Google Pixel 8 Pro and I'm on the January update of android 14 stable. Besides PixelXpert I have Iconify,  Pixel launcher mods, AFWall+, VPNHotspot, ACC and some more

I hope that are not too many requests. Not all have to be implemented, but this is just a wishlist

**Comment by EleoXDA** [comment]
Most features are either theming (PixelXpert is not interested in theming) or possible with 3rd party app (golden rule of xposed is - you don't use xposed when you can yse a 3rd party app)

**Comment by srt54558** [comment]
> Most features are either theming (PixelXpert is not interested in theming) or possible with 3rd party app (golden rule of xposed is - you don't use xposed when you can yse a 3rd party app)

Okay sorry,
Here are the important features (for me), that are not that design related and are not available in 3rd party apps.

-On QS show seconds when the QS is expanded and shows the clock bigger
-Ability to disable the estimated time till the battery runs out, shown on expanded QS
-Make the Android build number text wider (e.g. have the width to do edit button for the tiles) when a custom text is applied
-Custom Turn off menu options like "reboot to bootloader" or "activate flashlight"
-Show AOD on single tap, and Lockscreen on double tap (like on Samsung) (I have AOD disabled)
-Double Tap on/off button for custom action (such as opening Google wallet to pay (but only do this if the phone is unlocked of course))
-Show network activities next to the wifi icon only on expanded QS panel
-Hotspot Mac address filtering
-Tile for enabling/disable data transfer on the USB port, so the phone can safely be used on public changing cables (like USB condom, but implemented)

**Comment by EleoXDA** [comment]
> -On QS show seconds when the QS is expanded and shows the clock bigger

Enable show seconds. It is already available on a14

> -Ability to disable the estimated time till the battery runs out, shown on expanded QS

It is Android Intelligence related. It is automatic, not manual.

> -Make the Android build number text wider (e.g. have the width to do edit button for the tiles) when a custom text is applied

There is only some space available. Not possible to expand without wrecking other parts of QS.

> -Custom Turn off menu options like "reboot to bootloader" or "activate flashlight"

You don't need flashlight toggle in power menu when you already have so many shortcuts for it. 

> -Show AOD on single tap, and Lockscreen on double tap (like on Samsung) (I have AOD disabled)

I sensed you come from Samsung from your request of "flashlight" in power menu. But AOSP is not OneUI. AOD is shown on if it is enabled. As it is supposed to. If you mean ambient display, that is already possible.

> -Double Tap on/off button for custom action (such as opening Google wallet to pay (but only do this if the phone is unlocked of course))

Power button cannot be remapped. It is a security risk!

> -Show network activities next to the wifi icon only on expanded QS panel

You already can see it in statusbar

> -Hotspot Mac address filtering

This is possible with 3rd party app

> -Tile for enabling/disable data transfer on the USB port, so the phone can safely be used on public changing cables (like USB condom, but implemented)

You already have it automatically disabled. You can enable it from notifications


All in all, no. AOSP is not OneUI

**Comment by srt54558** [comment]
>  
> > -On QS show seconds when the QS is expanded and shows the clock bigger
> 
> Enable show seconds. It is already available on a14
Where can I find the setting? I cannot find it

> > -Ability to disable the estimated time till the battery runs out, shown on expanded QS
> 
> It is Android Intelligence related. It is automatic, not manual.
Okay sorry

> > -Make the Android build number text wider (e.g. have the width to do edit button for the tiles) when a custom text is applied
> 
> There is only some space available. Not possible to expand without wrecking other parts of QS.
Okay didn't know, sorry

> > -Custom Turn off menu options like "reboot to bootloader" or "activate flashlight"
> 
> You don't need flashlight toggle in power menu when you already have so many shortcuts for it. 
You're right, but that was an example, rebooting to bootloader or recovery would be cool tho

> > -Show AOD on single tap, and Lockscreen on double tap (like on Samsung) (I have AOD disabled)
> 
> I sensed you come from Samsung from your request of "flashlight" in power menu. But AOSP is not OneUI. AOD is shown on if it is enabled. As it is supposed to. If you mean ambient display, that is already possible.
Yes ambient display, sorry. How can I set it up? I want single tap for ambient display and double tap for Lockscreen. I don't come from Samsung, but my dad has it and I'd love this feature 

> > -Hotspot Mac address filtering
> 
> This is possible with 3rd party app
Got the name?

> > -Tile for enabling/disable data transfer on the USB port, so the phone can safely be used on public changing cables (like USB condom, but implemented)
> 
> You already have it automatically disabled. You can enable it from notifications

Oh I thought malicious code can still be executed. Well looks like I'm wrong

**Comment by srt54558** [comment]
> >  
> >  -On QS show seconds when the QS is expanded and shows the clock bigger
> > 
> Enable show seconds. It is already available on a14
 Where can I find the setting? I cannot find it

> >  -Ability to disable the estimated time till the battery runs out, shown on expanded QS
> > 
>  It is Android Intelligence related. It is automatic, not manual.
Okay sorry

> > > -Make the Android build number text wider (e.g. have the width to do edit button for the tiles) when a custom text is applied
> > 
> > There is only some space available. Not possible to expand without wrecking other parts of QS.
> Okay didn't know, sorry
> 
> > > -Custom Turn off menu options like "reboot to bootloader" or "activate flashlight"
> > 
> > You don't need flashlight toggle in power menu when you already have so many shortcuts for it. 
> You're right, but that was an example, rebooting to bootloader or recovery would be cool tho
> 
> > > -Show AOD on single tap, and Lockscreen on double tap (like on Samsung) (I have AOD disabled)
> > 
> > I sensed you come from Samsung from your request of "flashlight" in power menu. But AOSP is not OneUI. AOD is shown on if it is enabled. As it is supposed to. If you mean ambient display, that is already possible.
> Yes ambient display, sorry. How can I set it up? I want single tap for ambient display and double tap for Lockscreen. I don't come from Samsung, but my dad has it and I'd love this feature 
> 
> > > -Hotspot Mac address filtering
> > 
> > This is possible with 3rd party app
> Got the name?
> 
> > > -Tile for enabling/disable data transfer on the USB port, so the phone can safely be used on public changing cables (like USB condom, but implemented)
> > 
> > You already have it automatically disabled. You can enable it from notifications
> 
> Oh I thought malicious code can still be executed. Well looks like I'm wrong

**Comment by EleoXDA** [comment]
> > > -On QS show seconds when the QS is expanded and shows the clock bigger
> >
> > Enable show seconds. It is already available on a14
> 
> Where can I find the setting? I cannot find it


You need to read wiki:
https://github.com/siavash79/PixelXpert/wiki/PixelXpert-Wiki


> > > > -Show AOD on single tap, and Lockscreen on double tap (like on Samsung) (I have AOD disabled)
> > > 
> > > I sensed you come from Samsung from your request of "flashlight" in power menu. But AOSP is not OneUI. AOD is shown on if it is enabled. As it is supposed to. If you mean ambient display, that is already possible.
> 
> Yes ambient display, sorry. How can I set it up? I want single tap for ambient display and double tap for Lockscreen. I don't come from Samsung, but my dad has it and I'd love this feature
> 

You need to read wiki:
https://github.com/siavash79/PixelXpert/wiki/PixelXpert-Wiki
 
> > > > -Custom Turn off menu options like "reboot to bootloader" or "activate flashlight"
> > > 
> > > 
> > > You don't need flashlight toggle in power menu when you already have so many shortcuts for it.
> 
> You're right, but that was an example, rebooting to bootloader or recovery would be cool tho
> 

Pixel devices do not have recovery on stock firmware. You can reboot to recovery with a key combination instead.

**Comment by srt54558** [comment]
> > > > -On QS show seconds when the QS is expanded and shows the clock bigger
> > >
> > > Enable show seconds. It is already available on a14
> > 
> > Where can I find the setting? I cannot find it
> 
> 
> You need to read wiki:
> https://github.com/siavash79/PixelXpert/wiki/PixelXpert-Wiki
> 
> 
> > > > > -Show AOD on single tap, and Lockscreen on double tap (like on Samsung) (I have AOD disabled)
> > > > 
> > > > I sensed you come from Samsung from your request of "flashlight" in power menu. But AOSP is not OneUI. AOD is shown on if it is enabled. As it is supposed to. If you mean ambient display, that is already possible.
> > 
> > Yes ambient display, sorry. How can I set it up? I want single tap for ambient display and double tap for Lockscreen. I don't come from Samsung, but my dad has it and I'd love this feature
> > 
> 
> You need to read wiki:
> https://github.com/siavash79/PixelXpert/wiki/PixelXpert-Wiki
>  
> > > > > -Custom Turn off menu options like "reboot to bootloader" or "activate flashlight"
> > > > 
> > > > 
> > > > You don't need flashlight toggle in power menu when you already have so many shortcuts for it.
> > 
> > You're right, but that was an example, rebooting to bootloader or recovery would be cool tho
> > 
> 
> Pixel devices do not have recovery on stock firmware. You can reboot to recovery with a key combination instead.

I read the wiki, and tried the thing again and now it works. Last time it tried it didn't. Well then all my questions I was curious about and I wished came mostly true or I learned why they can't be implemented! Thank you ALOT for taking your time and informing me!!!
