### ISSUE TITLE
[Bug] New stable update (v3.3.0) unset default launcher

### ISSUE THREAD

**Issue by superbats** [siavash79/PixelXpert#783]
### Describe the issue

Must select launcher on each boot after update 

### Steps to reproduce

Go from v3.2.0 to v3.3.0

### Expected behavior

Boot completes without the need to select launcher

### Your device setup (Please take some time to give correct information here)

Google Pixel 8 Pro
Android 14, January update
LSposed v1.9.2

### Logs

[LSPosed_2024-01-17T10_19_04.943126.zip](https://github.com/siavash79/PixelXpert/files/13965109/LSPosed_2024-01-17T10_19_04.943126.zip)

**Comment by siavash79** [comment]
Should be something else. I can't link it to PX
