### ISSUE TITLE
[Bug] [CRITICAL] Latest update breaks root access, breaks status bar, launcher and soft-bricks phone.

### ISSUE THREAD

**Issue by Samg381** [siavash79/PixelXpert#785]
### Describe the issue

Today was not a good day. I started the morning by receiving a notification that an update to PixelXPert was available, which I chose to download and install. After rebooting, I immediately noticed root access has never happened during a routine reboot, as I have OTA updates explicitly disabled. So, after spending a nervewracking hour re-rooting my phone and finally rebooting it, I was prompted to re-authenticate PixelXPert as root, which I did. Immediately, I noticed that my status bar icons were screwed up (multi-row icons were enabled, and could not be disabled), which prompted me to disable PixelXPert and reboot. When my phone rebooted, I was greeted with a completely blank screen. The only thing that appeared was a power menu (which looked like it was from Android KitKat, horrifically) when I held the power button. Subsequent reboots did not clear the issue, which essentially soft-bricked my phone. Despite the black screen, ADB was working (thank god), and I was able to re-enable PixelXPert, which finally cleared the black screen. I am now stuck with PixelXPert installed (which I am now treating as malware) and would like to know how to safely uninstall it without further damaging my device.

### Steps to reproduce

Update PixelXpert, reboot phone.

### Expected behavior

App should have updated without disabling root access and soft-bricking phone.

### Your device setup (Please take some time to give correct information here)

Pixel 8 Pro. January security update. Latest Magisk as of this writing.

**Comment by EleoXDA** [comment]
The fact that after disabling PX your phone got screwed says something wrong with your device rather than with PX as we have lots of testers using it  on Jan update on pixel devices.

My suggestion:
Prepare a bugreport point by point as we requested with the template in GitHub. It is for your sake so that we can help you. Otherwise you can omit it but then we would have to disregard your report as well.

**Comment by EleoXDA** [comment]
The bug you described in the title ends up somehow only when you DISABLE mod. So I would suggest you to rewrite the bugreport and as I wrote above, give more information about your device setup so that we could help you

**Comment by siavash79** [comment]
What described can't be related to PX.
What to know is that PX does not change anything in the system. So, once the module is disabled in magisk, things will get to the state as if it was never present

Also, the module is fully open source and all of what it does is publicly available on this repo without any hidden codes kept anywhere else. This is done for multiple reasons, including full transparency. So it can't be called malware in any sense

I'd suggest studying the logs to find out the real causes of the issues described

Cheers

**Comment by EleoXDA** [comment]
Guy is just panicking and looking for a person to show with a finger

**Comment by Samg381** [comment]
> Guy is just panicking and looking for a person to show with a finger

What does this even mean? Think before you speak.

**Comment by EleoXDA** [comment]
> > Guy is just panicking and looking for a person to show with a finger
> 
> What does this even mean? Your lack of insight is further evidence this project doesn't care about it's users' devices. Think before you speak.

Be my guest. Check the code and find anything malicious as you said. This is definitely problem with your setup. Acknowledging it will make it easier for you to fix it.
