### ISSUE TITLE
[Feature request] Music visualizer on lockscreen

### ISSUE THREAD

**Issue by Senliast** [siavash79/PixelXpert#787]
What's on your mind?
A graphic visualization (jumping columns) of music on lockscreen. Example: 
![EP1Cr](https://github.com/siavash79/PixelXpert/assets/23285435/53e689a6-ec27-461c-b838-a7225e4f836e)

Is this feature implemented on any other app/mod/rom? please specify
Yes, GravityBox module, crDroid ROM.

**Comment by EleoXDA** [comment]
There is NO functional gain of such a feature.
