### ISSUE TITLE
[Bug] System crash

### ISSUE THREAD

**Issue by duramato** [siavash79/PixelXpert#788]
### Describe the issue

When enabling PixelXpert with Shamiko also enabled the system settings and UI crash.

### Steps to reproduce

1. Disable all Magisk modules apart from necessary ones (Zygisk and LSposed)
2. Enable PixelXpert
3. Enable Shamiko
4. Reboot
5. Crash

### Your device setup (Please take some time to give correct information here)

- OnePlus 8
- Evolution X ROM - Android 14
- APatch 0.8.5
- LSPosed 1.9.2
- PixelXpert canary-327
- Zygisk Next V4-0.9.4, Zygisk - Sui v13.5.1, Zygisk-detach v1.10.1, Shamiko v0.7.4, Zygisk - LSPosed, OpenEUICC v01, MMRL Install Tools v4.3.2

### Logs

[LSPosed_2024-01-21T20_34_07.729299.zip](https://github.com/siavash79/PixelXpert/files/14002777/LSPosed_2024-01-21T20_34_07.729299.zip)

**Comment by EleoXDA** [comment]
Please read ReadMe before reporting. There is compatibility section where you will find answer why your CUSTOM ROM is not responding as requested

**Comment by duramato** [comment]
The rom used is an ASOP ROM and PixelXpert normally works in it.

As described on my op, it only stops working when used in conjunction with Shamiko, meaning, there's some incompatible between the two magisk modules.

**Comment by EleoXDA** [comment]
It deliberately says "do not report any bugs if you are on a custom ROM". Report to shamiko devs instead.

Stock pixel firmware users have no problems using shamiko and PX
