### ISSUE TITLE
[Bug] Quick settings tile count settings

### ISSUE THREAD

**Issue by alabotski** [siavash79/PixelXpert#789]
### Describe the issue

App crases when I try open "Quick settings tile count settings"

### Steps to reproduce

1. Quick settings panel
2. Quick settings tile count settings

### Your device setup (Please take some time to give correct information here)

Google Pixel 7 Pro
Android 14
Kitsune Mask 26.4-kitsune-2
Lsposed 1.92
PixelXpert 3.3.0 (also reproduced on lasts canary)
[Screenshot_20240122-062936](https://github.com/siavash79/PixelXpert/assets/439337/e6717e26-3131-49f4-92ee-289300d62d4b)

### Logs

[crash-sh-siava-pixelxpert-22_01-06-28-24_725.zip](https://github.com/siavash79/PixelXpert/files/14005497/crash-sh-siava-pixelxpert-22_01-06-28-24_725.zip)

**Comment by EleoXDA** [comment]
Update to latest stable (3.3.1) and switch to standard magisk. I think there are issues with kitsune especially with sulist. Maybe @Mahmud0808 can give more information regarding sulist issue

**Comment by Mahmud0808** [comment]
Doesn't look like an issue due to Kitsune. Backup your PX settings, then clear app data and check again if you can open that page.

**Comment by EleoXDA** [comment]
This page @Mahmud0808 ? Seems ok

![Screenshot_20240122-125534](https://github.com/siavash79/PixelXpert/assets/27622683/26ba816d-e187-4850-aaf1-4a4fb5e6ed3f)

**Comment by Mahmud0808** [comment]
@alabotski Try the latest [v3.3.1](https://github.com/siavash79/PixelXpert/releases/tag/v3.3.1) and let us know.

**Comment by alabotski** [comment]
@Mahmud0808 
After update all good
