### ISSUE TITLE
[Bug] Charging info is zero or not shown

### ISSUE THREAD

**Issue by LollosoSi** [siavash79/PixelXpert#790]
### Describe the issue

Charging info either on lock screen or quick settings is shown as zero (on the QS panel, even if not charging) or not shown at all in the latest experimental builds

### Steps to reproduce

1. Enable the option under the lock screen and QS panel section
2. Data is not shown or unavailable

Used to work some weeks ago

### Your device setup (Please take some time to give correct information here)

Pixel 7 running lineage 20 microg
LSposed 1.9.2
PixelXpert canary 327

### Logs

[LSPosed_2024-01-23T13_40_33.794822.zip](https://github.com/siavash79/PixelXpert/files/14024098/LSPosed_2024-01-23T13_40_33.794822.zip)

**Comment by EleoXDA** [comment]
First things first, ALWAYS read documentation. They are ReadMe and Wiki in this repo. After reading those, you will understand what is wrong with your report
