### ISSUE TITLE
Combine 4g and signal in a single icon

### ISSUE THREAD

**Issue by maicol07** [siavash79/PixelXpert#791]
Combine network indicator and signal strength in the same icon. i.e.:
https://static.vecteezy.com/system/resources/previews/006/308/978/original/signal-strength-indicator-set-mobile-phone-bar-status-icon-no-signal-symbol-4g-and-5g-network-connection-level-sign-isolated-on-white-illustration-for-web-app-design-interface-free-vector.jpg

Is this feature implemented on any other app/mod/rom? I think an old version of PixelXpert, when it was called AOSPMods, did this

**Comment by EleoXDA** [comment]
It is no longer compatible with latest changes in AOSP code
