### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ybanks87** [siavash79/PixelXpert#792]
### Describe the issue

Can't use navigation bar gesture to return home screen

### Steps to reproduce

hello,

Even after i disabled the option to hide the taskbar,
When the rotation of the screen is enabled, navigation gesture doesn't respond without any crash.
I need to click on LSposed notification to go on Pixel Xpert module to restart the System UI
This thing happen only when i rotate the screen

### Your device setup (Please take some time to give correct information here)

Google pixel 7 pro, android 14 UQ1A.240105.004, Stock Rom, Magisk just updated this morning to 27.0, modules activated Zygisk LSposed / Play integrity fix / Pixel Xpert, Lsposed version 1.9.2. Only Pixel Xpert on Lsposed modules canary-329

**Comment by EleoXDA** [comment]
Could not be reproduced. Please reopen issue when you have lsposed logs while replicating issue
