### ISSUE TITLE
[Bug] Stable version's `updateJson` value in `module.prop` points to canary version

### ISSUE THREAD

**Issue by blackwind** [siavash79/PixelXpert#793]
### Describe the issue

Magisk Manager presents updates to the canary version when stable is installed.

### Steps to reproduce

1. Install stable version of Pixel Xpert.
2. Observe canary updates are offered through Magisk Manager.

### Expected behavior

Magisk Manager should present updates for the currently installed release channel.

### Your device setup (Please take some time to give correct information here)

N/A

**Comment by siavash79** [comment]
Apparently it has been ongoing since the first PX. I fixed it a few days ago and will reflect on the next release
