### ISSUE TITLE
Feature Request: Option to skip confirmation and hide cancel/confirmation buttons when using face unlock on Pixel 8/8 Pro

### ISSUE THREAD

**Issue by diegonogaretti** [siavash79/PixelXpert#794]
What's on your mind?

> Please add an option to hide the confirmation and cancel buttons and automate confirmation in the biometrics unlock popup when using face unlock.
> Currently, using fingerprint doesn't require any confirmation, face unlock shouldn't too, it would be way seamless just like fingerprint and also cooler.
> On top of this, if someone manages to steal your phone and unlock via face unlock, confirmation wouldn't add any security improvement.

Is this feature implemented on any other app/mod/rom? please specify
> No

**Comment by EleoXDA** [comment]
I think this was already made using a 3rd party app. And if there is already a 3rd party app, no need for xposed. Please search to find it.

**Comment by diegonogaretti** [comment]
Hi

Did a search and these buttons can be overridden by apps, it's up to the devs.
No apps root or not allow customization.

Please really consider this, would make face unlock way seamless and the UI way more streamlined across all apps.

**Comment by EleoXDA** [comment]
> Hi
> 
> Did a search and these buttons can be overridden by apps, it's up to the devs.
> No apps root or not allow customization.
> 
> Please really consider this, would make face unlock way seamless and the UI way more streamlined across all apps.

Try this
https://www.reddit.com/r/GooglePixel/s/8MEn4YsBD4

**Comment by diegonogaretti** [comment]
Yes, I know about this one.
My request is for biometrics popup in apps as stated above your comment.
