### ISSUE TITLE
[Bug] Empty option for keyboard space

### ISSUE THREAD

**Issue by marcpinet** [siavash79/PixelXpert#795]
### Describe the issue

"Keyboard space for gestures" section is empty

### Steps to reproduce

Just go to Navigation Bar > Gesture Navigation > Scroll at the bottom 

![Screenshot_20240206-110113~2](https://github.com/siavash79/PixelXpert/assets/52708150/c3ec6d40-2f87-4eab-8c43-94486229c7fd)
![Screenshot_20240206-110531~2](https://github.com/siavash79/PixelXpert/assets/52708150/04d8776c-18d5-4841-8801-0a509ba71861)

### Expected behavior

An option to maybe disable the space between bottom of the screen and keyboard (+ the default padding at the pill location)

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7
- Stock Firmware 
- Android 14 240205 (February 2024 Update)
- Magisk v27.0
- PixelXpert v3.3.1

**Comment by EleoXDA** [comment]
It will be empty. Use other alternatives like Dan Magic things.

The menu will be removed completely

**Comment by marcpinet** [comment]
> It will be empty. Use other alternatives like Dan Magic things.
> 
> The menu will be removed completely

Dan Magic?

**Comment by kaoneko** [comment]
I'm sure @EleoXDA means _Dan **Magisk** things_:
https://t.me/danmgk/
https://github.com/Magisk-Modules-Alt-Repo/HideNavBar

**Comment by marcpinet** [comment]
> I'm sure @EleoXDA means _Dan **Magisk** things_: https://t.me/danmgk/ https://github.com/Magisk-Modules-Alt-Repo/HideNavBar

Yes, but I finally went for [Iconify](https://github.com/Mahmud0808/Iconify) which does the job perfectly
