### ISSUE TITLE
[Bug]  Settings app crashing

### ISSUE THREAD

**Issue by mikhailfluffy** [siavash79/PixelXpert#796]
### Describe the issue

Settings app crashed

### Steps to reproduce

My ROM: Project Elixir Android 14(ROM pixel-like)
Device codename: grus

I can't open settgins app. 
P.S. I understand what I can turn off setting app in LSposed, but after restarting it turning on again.

### Expected behavior

I want to open my settings without crash.

### Your device setup (Please take some time to give correct information here)

Device: Xiaomi Mi 9 SE (grus)
ROM: Project elixir A14
LSposed, Magisk v27

**Comment by EleoXDA** [comment]
Read Readme file before reporting please. It has Compatibility section that you should check out before installing on a unsupported Custom ROM
