### ISSUE TITLE
[Bug] Only system and settings app are connected 

### ISSUE THREAD

**Issue by Xerxes-2** [siavash79/PixelXpert#800]
### Describe the issue

Only android and settings app are connected in the PixelXpert Connected packages, causing most of the features not working.

### Steps to reproduce

1. Install KernelSU (Magisk not installed).
2. Install PixelXpert in KSU manager and reboot (If install LSPosed at the same time, the system UI would crash maybe because KSU doesn't ask or grant root to PixelXpert)
3. Manually grant root to PixelXpert in KSU manager.
4. Install ZygiskNext and LSPosed-zygisk in KSU manager, reboot.
5. Open LSPosed manager and select recommended app for PixelXpert, reboot.
6. Open PixelXpert and see packages not connected.

### Expected behavior

most packages are connected

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7 Pro (GE2AE)
- Android 14 (UQ1A.240205.002)
- Security Patch: 5 Feb 2024
- KernelSU 0.7.6 (11458)
- Root apps: see screenshot 
<img src="https://github.com/siavash79/PixelXpert/assets/35587143/898a0eb5-b3b3-467a-b56d-0d726dbbbdb0" alt="Screenshot_20240219-173218" width="50%" height="auto">

- Modules: see screenshot 
<img src="https://github.com/siavash79/PixelXpert/assets/35587143/e968ba02-adc8-4ab3-93f8-1ba4780b6cc0" alt="Screenshot_20240219-173258" width="50%" height="auto">

- LSPosed  1.9.2 (7024)
- LSPosed modules: see screenshot 
<img src="https://github.com/siavash79/PixelXpert/assets/35587143/71a32170-0491-4af7-8ff1-644999108b43" alt="Screenshot_20240219-173418" width="50%" height="auto">

### Logs

[LSPosed_2024-02-19T17_20_56.383897.zip](https://github.com/siavash79/PixelXpert/files/14327388/LSPosed_2024-02-19T17_20_56.383897.zip)

**Comment by siavash79** [comment]
try canary 332 and let me know the result

**Comment by Xerxes-2** [comment]
> try canary 332 and let me know the result

Did not work
