### ISSUE TITLE
"Recents" buttons stops working after long uptime with swapped position

### ISSUE THREAD

**Issue by Jake-Jensen** [siavash79/PixelXpert#805]
### Describe the issue

Between a variable amount of time of hours to days without restarting the SYSTEM UI or rebooting, the recents button in 3 button navigation mode will fail to do anything at all. This does not occur if PE is not installed / active. 

### Steps to reproduce

1. Install PE
2. Set navigation bar -> 3 button nav -> Modify order -> Recents to anywhere but stock
3. Wait. It'll happen eventually. 

### Expected behavior

It to work like a recents button. 

### Your device setup (Please take some time to give correct information here)

Google Pixel 6 Pro
Android 14, UQ1A.240205.002
Magisk 27000
LSPosed 7024
PE Canary 337

### Logs

This particular time took at least 71 hours to trigger, so I'm not posting logs until I can reproduce this consistently.

**Comment by EleoXDA** [comment]
Please follow report procedure correctly. You forgot sharing logs.

BTW there was some problems with magisk 27. Try with older magisk
