### ISSUE TITLE
Feature Request: Change Brightness by swiping Status Bar

### ISSUE THREAD

**Issue by k1llerk3ks** [siavash79/PixelXpert#806]
### What's on your mind?
I have used other Roms, especially HavocOS before. They have had the Feature included, where you could swipe the Status bar to change the brightness of the screen. Left = Dark, Right = Bright

I am deeply missing this, this was so handy!

### Is this feature implemented on any other app/mod/rom? please specify
I can only remember of HavocOS, it worked really well in all of their Roms i have used.
I have used Xposed Edge to get this behaviour and it worked somewhat. I was just not as reliable as with Havoc.

I think many people besides me will enjoy this Feature.

**Comment by EleoXDA** [comment]
It was already denied once before in previous requests. Please check old requests before openning a new one.

Reason - no need for additional touch listener especially when we already have bar in qqs
