### ISSUE TITLE
[Bug] Pixel 7 A14 March feature update says "ROM not supported"

### ISSUE THREAD

**Issue by 103sbavert** [siavash79/PixelXpert#807]
### Describe the issue

When I open Pixel Xpert, I am greeted with a message dialog that says that my ROM which is the stock ROM with root on my Pixel 7, is not supported.

### Steps to reproduce

* Install the module on a Pixel 7 running rooted March Feature Drop firmware
* Open the Pixel Xpert app
* See the message

### Expected behavior

The message doesn't appear

### Your device setup (Please take some time to give correct information here)

Google Pixel 7
Android 14
March 2024 Update
Magisk 27.0
![Screenshot_20240305-090709](https://github.com/siavash79/PixelXpert/assets/65838896/eb0e9736-9e81-42f0-a7fd-ac838873e22a)
![Screenshot_20240305-090745](https://github.com/siavash79/PixelXpert/assets/65838896/4cc41314-8824-4334-923c-d55cd0db7068)
![Screenshot_20240305-090808](https://github.com/siavash79/PixelXpert/assets/65838896/4ebbfd3f-4656-4917-94fa-8fef3d72f7a2)
![Screenshot_20240305-090820](https://github.com/siavash79/PixelXpert/assets/65838896/faa584d7-4dc2-4f48-8c99-52ec997b5532)

### Logs

[LSPosed_2024-03-05T09_09_56.161846.zip](https://github.com/siavash79/PixelXpert/files/14490022/LSPosed_2024-03-05T09_09_56.161846.zip)

**Comment by Jnss98b** [comment]
Also got the same message on my pixel fold running stock March 2024 update as well on magisk v27. Doesn't seem to have any problem usage wise but still a concern nonetheless

![image](https://github.com/siavash79/PixelXpert/assets/24306400/bf5dc969-058f-4d2b-83fb-1eda598d196b)

**Comment by EleoXDA** [comment]
Check again with latest canary
