### ISSUE TITLE
Inverted colors on QS Flashlight Brightness slider tile

### ISSUE THREAD

**Issue by pauverblom** [siavash79/PixelXpert#809]
### Describe the issue

The flashlight slider has incorrect coloring when enabled. It should ideally be full green when the flashlight is on and at a 100% and a darker green when it is at 0% but not turned off

### Steps to reproduce

1. Install Pixel Xpert 3.3.2 (336)
2. Enable Brightness Leveled Flashlight Tile

Inverted colors:

![Screenshot_20240306-082414](https://github.com/siavash79/PixelXpert/assets/47112988/2285912c-8e48-4c6d-ac28-b133ff7ea8a1)

Should be full light green:

![Screenshot_20240306-082417](https://github.com/siavash79/PixelXpert/assets/47112988/5306fb9e-2fc8-4330-bd16-0fd0fbbbeb85)

### Expected behavior

As mentioned, the colors should be inverted. Clearer green when fully on and darker green when fully off

### Your device setup (Please take some time to give correct information here)

- Google Pixel 8 Pro
- Android 14
- February 24 security update
- Apps with root access:

![Screenshot_20240306-083240](https://github.com/siavash79/PixelXpert/assets/47112988/42c444bd-8cd0-473f-8b5b-154bc21fbce0)

- Magisk modules:

![Screenshot_20240306-083345](https://github.com/siavash79/PixelXpert/assets/47112988/bc8e9088-18ac-4ed5-aef1-c4909454beaa)

- Lsposed 1.9.2 (7024)
- Lsposed Modules:

![Screenshot_20240306-083508](https://github.com/siavash79/PixelXpert/assets/47112988/e51fc448-ef55-4a17-9d21-663fe1494f53)

### Logs

[LSPosed_2024-03-06T08_36_12.602911.zip](https://github.com/siavash79/PixelXpert/files/14506336/LSPosed_2024-03-06T08_36_12.602911.zip)

**Comment by EleoXDA** [comment]
The behavior is correct. The overlay shows how much of flashlight is enabled
