### ISSUE TITLE
Feature request: Noisy notifications toggle

### ISSUE THREAD

**Issue by yunusarkan** [siavash79/PixelXpert#810]
**What's on your mind?**
This feature is makes phone notifications silent while screen is on so you don't get annoyed by sound or vibrations while looking at the screen, but you get the advantage of getting alerted by sound or vibration when screen off. 

**Is this feature implemented on any other app/mod/rom? please specify**
This feature is recent on most feature packed roms like crdroid, bliss, ghostos, alphadroid, evolutionx etc. But not on simple roms that i like to use for example aospa, arrow etc. this is why i am asking for this featue. Here is an ss from ghostos for reference;

![Screenshot_20240307-023634_Settings~2.png](https://github.com/siavash79/PixelXpert/assets/74573031/4042fd4b-16a9-40bc-8679-062fe3cc76ca)

Thanks.

**Comment by EleoXDA** [comment]
it was already denied in previous feature requests:
https://github.com/siavash79/PixelXpert/issues/681

PLEASE READ PREVIOUSLY DENIED REQUEST BEFORE OPENNING A NEW ONE. THANKS.
