### ISSUE TITLE
[Bug] PixelXpert causes soft bootloop after switching to KSU

### ISSUE THREAD

**Issue by TQMatvey** [siavash79/PixelXpert#812]
### Describe the issue

i switched from magisk to KSU, flashed PixelXpert and now i have a soft bootloop with a black screen

### Steps to reproduce

honestly... idk
1. had magisk installed with few modules and pixelxpert stable, all worked fine
2. removed all modules and uninstalled magisk
3. rebooted once, all good and works
4. flashed KSU
5. flashed zygisk-next 
6. rebooted
7. flashed lsposed-zygisk canary (same as before)
8. flashed PixelXpert
9. rebooted
10. enabled PixelXpert in lsposed
11. rebooted
12. soft bootloop with black screen in between

### Expected behavior

it should've just booted and worked fine, maybe settings messed up or idk?(

### Your device setup (Please take some time to give correct information here)

- Google Pixel 8
- Android 14 Stable March
- AP1A.240305.019.A1
- KernelSU 0.9.0
- Kernel Flasher, LSPosed, material files, shell, termux
- PIF, Youtube revanced, zygisk lsposed, zygisk-detach for youtube revaced (not used currently), Zygisk Next stable
- LSPosed 1.9.2 (7058) - Zygisk
- PIxel launcher double tap to sleep, PixelXpert

### Logs

[pixpert.log](https://github.com/siavash79/PixelXpert/files/14630173/pixpert.log)
![image](https://github.com/siavash79/PixelXpert/assets/77576395/e4453e9f-86b8-45c2-9b96-3a48121cd294)

**Comment by siavash79** [comment]
On KSU you should grant root to PX manually beforehand by installing APK first
