### ISSUE TITLE
[Bug] jittery qs panel pulldown animation after applying light theme 

### ISSUE THREAD

**Issue by fabianlawrence** [siavash79/PixelXpert#813]
### Describe the issue

The qs panel pulldown animation after applying light theming is stuttering, especially when media player is showing.

### Steps to reproduce

1. Apply light theme in qs panel and power menu
2. Play with the qs panel pulldown
3. Try playing music to show media player and do step 2

### Expected behavior

No stuttering or jittery animation is expected

### Your device setup (Please take some time to give correct information here)

Google pixel 7 pro
Android 14 March update
Magisk v27
Lsposed v1.9.2
Pixel xpert tried latest stable and canary builds
Using these modules-
       Unlimited backup (not pixelify gphotos)
       Bcr basic call recorder
       Play integrity fix
       Charging limiter 85% for pixel 6 pro

### Logs

Sorry I don't know how to do this :(

**Comment by siavash79** [comment]
That's normal.
Every time the QS is rendered all the colors have to be re-painted on it, and it takes time with xposed. this can't be fixed
