### ISSUE TITLE
Add option to make long press of power button work while the device is unlocked

### ISSUE THREAD

**Issue by woliver99** [siavash79/PixelXpert#814]
I just want to be able to make it so I can rebind the hold power button to the flashlight toggle and have it work at any time since I don't need to have a whole button dedicated to turning off the phone when there is an option in the notification bar.

The code seems to be all there it just looks like you have to make an option to have it work while the screen is on:

I have found where it would need to be changed and I would do it myself but I don't know how to build Magisk modules.

it would need to be changed at line 129 inside of: `PixelXpert/app/src/main/java/sh/siava/pixelxpert/modpacks/android/ScreenOffKeys.java`

Thanks for taking the time to look at my request.

**Comment by EleoXDA** [comment]
You already have "long press power button for torch" in "while screen is off..." section inside Miscellaneous menu

**Comment by woliver99** [comment]
Yes i know it exists already for while the screen is off i just want to work while the screen is on
