### ISSUE TITLE
Network Monitor - Largest between up/down

### ISSUE THREAD

**Issue by andrevmatos** [siavash79/PixelXpert#819]
What's on your mind?

Several ROMs (e.g. Derpfest) have this network monitor indicator in the status bar, where it shows only the largest between upload/download, with an arrow to indicate the direction (up if upload is larger than download, down otherwise).

Is this feature implemented on any other app/mod/rom? please specify
Derpfest and crDroid at least implements this. I think this is pretty common between custom ROMs.

**Comment by EleoXDA** [comment]
> What's on your mind?
> 
> Several ROMs (e.g. Derpfest) have this network monitor indicator in the status bar, where it shows only the largest between upload/download, with an arrow to indicate the direction (up if upload is larger than download, down otherwise).
> 
> Is this feature implemented on any other app/mod/rom? please specify
> Derpfest and crDroid at least implements this. I think this is pretty common between custom ROMs.

You basically want to add an arrow to the combined upload/download indicator that is already present? What is the use of it? What if you have both upload and download? The arrow should update direction every second?

**Comment by andrevmatos** [comment]
Combined afaiu sums the rate of download and upload, right?
This suggestion is for an option which shows the largest of either in the moment, and their respective arrow

**Comment by EleoXDA** [comment]
You should rather show both if you want to see separate speed
