### ISSUE TITLE
Vertical status bar items padding

### ISSUE THREAD

**Issue by maicol07** [siavash79/PixelXpert#821]
What's on your mind?
Adding a setting like the horizontal padding of the status bar but that works vertically.

Is this feature implemented on any other app/mod/rom? please specify
I don't know

**Comment by dbekoscke** [comment]
What a coincidence.  I was just looking into if there was any way to adjust (lower) the status bar text vertically.

I using a status bar height of 60% on my P8 Pro, and the status bar text is way high up at the very top of the screen.  I'd love to be able to lower it vertically to be more in line with the camera hole punch.

**Comment by gygabyte017** [comment]
I would also love to allow negative horizontal padding, since on my P8 I see a huge empty space where the screen begins to curve, and maybe the icons may be moved 5mm toward the edges to allow more icons to be displayed before hitting the camera hole!

**Comment by siavash79** [comment]
after many, many reconsiderations....... not planned
