### ISSUE TITLE
Bootloop when using KernelSU + ZygiskNEXT + LSposed [Bug] 

### ISSUE THREAD

**Issue by Oga-net** [siavash79/PixelXpert#824]
### Describe the issue

Pixel 8 pro bootloop when on Stock with KernelSU + ZygiskNEXT + LSposed . The phone Boot but when you unlock it, bootloop.

### Steps to reproduce

1. Flash latest april Build from google android 14
2. Flash Kernel SU
3. Flash ZygiskNext
4. Flash LSposed
5. Install Pixel Expert
6. Reboot
7. Unlock phone 
8. Bootloop

### Expected behavior

Booting normaly 

### Your device setup (Please take some time to give correct information here)

- Google pixel 8 pro 
- Latest april update
- Kernel SU  latest
- Zygisk Next latest
- Lsposed latest
- PixelExpert stable / Canary same behaviour

**Comment by EleoXDA** [comment]
Before installing module you need to extract apk from zip. Install it. Grant root. Then flash module.

This is the way to do it with latest updates to kernelsu

**Comment by Zooandbio4me** [comment]
So, unfortunately, I had a very similar encounter, for future reference, I wasn't able to get safe mode or any other type of module disabling, tried just flashing init.boot, no love, ended up having to go aaaalll the damn way back :( haha.  But in any case, just wondering if by chance there was something else I could have done??

**Comment by Zooandbio4me** [comment]
> yes, you should have rebooted in safe mode. If not, flash a stock kernel without root. Simple as that

Oh I did. Forced safe mode in every way anyone on the Internet has described.

**Comment by EleoXDA** [comment]
> > yes, you should have rebooted in safe mode. If not, flash a stock kernel without root. Simple as that
> 
> Oh I did. Forced safe mode in every way anyone on the Internet has described.

That isnt as easy to reproduce. You need to be able to do that before rooting and installing xposed. Otherwise you will have to "go aaaalll the damn way back :( "

**Comment by Zooandbio4me** [comment]
Lol fair enough, it's actually So it's actually zygisk, if you don't change the hook settings in kernelsu, it will bootloop. It warns and everything!! This is aaaaalll the way back, since there's no recovery... Can you imagine doing it say 1 of a few days vacation with no computer???

**Comment by EleoXDA** [comment]
> Lol fair enough, it's actually So it's actually zygisk, if you don't change the hook settings in kernelsu, it will bootloop. It warns and everything!! This is aaaaalll the way back, since there's no recovery... Can you imagine doing it say 1 of a few days vacation with no computer???

I wouldn't install anything before going on a vacation whilst knowing I will have no access to PC. This is your fault. I am closing this now as this is WAAAY off topic!
