### ISSUE TITLE
Sha we support Mgaisk module?

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [siavash79/PixelXpert#827]
l'd love your project very much, but I have a question about support Mgaisk
Have we had any plan to made it? And thanks for your reply!

**Comment by mingaldrichgan** [comment]
This _is_ a Magisk module...

**Comment by xiaoyueyoqwq** [comment]
> This _is_ a Magisk module...

Oh sorry, I saw Xposed only :-P
