### ISSUE TITLE
Taskbar padding issue [Bug] 

### ISSUE THREAD

**Issue by alyalbalushi** [siavash79/PixelXpert#828]
### Describe the issue

Taskber on when accessing recent application is padded on the left side

### Steps to reproduce

1. swipe up to access recent application
![Screenshot_20240414-141806](https://github.com/siavash79/PixelXpert/assets/103504438/dd282f06-bf00-4d7f-a777-5d0dc4b0c4b3)

### Expected behavior

For better looking feature it should taskbar should aligned in the center

### Your device setup (Please take some time to give correct information here)

Google pixel 8 pro

Android 15 beta 1

April, 2024

**Comment by EleoXDA** [comment]
Confirmed

**Comment by siavash79** [comment]
This is most likely an issue with android 15. We'll wait for the next betas to decide
