### ISSUE TITLE
Feature Request:  Add a option to show bluetooth device battery status on status bar

### ISSUE THREAD

**Issue by ShahzebQureshi** [siavash79/PixelXpert#831]
What's on your mind?

Status bar modification which show bluetooth battery health alongside bluetooth icon 

Is this feature implemented on any other app/mod/rom? please specify

Yes, Implemented on Lineage OS

**Comment by siavash79** [comment]
This feature isn't useful anymore since nowadays you've got more than one device connected to bt like the watch and headphone and other stuff 

For that, Google has invented a launcher widget that shows all battery infos you need. Look under settings services widgets

**Comment by cirnoe** [comment]
> This feature isn't useful anymore since nowadays you've got more than one device connected to bt like the watch and headphone and other stuff
> 
> For that, Google has invented a launcher widget that shows all battery infos you need. Look under settings services widgets

I have never had more than one Bluetooth device connected at the same time

**Comment by EleoXDA** [comment]
> I have never had more than one Bluetooth device connected at the same time. Pretty sure a lot of people can relate

Then you can try to add it. But since there is already a widget, a statusbar icon is useless
