### ISSUE TITLE
Request to show the default battery percentage and not with other battery estimates

### ISSUE THREAD

**Issue by Marlonleon2023** [siavash79/PixelXpert#834]
What do you have in mind? that you can activate the default battery percentage Is this feature implemented in any other app/mod/rom? Please specify Yes, they are implemented in several roms but in the rom I have they are not and the battery percentage does not want to appear

**Comment by Marlonleon2023** [comment]
I would really appreciate it if you implemented it.

**Comment by EleoXDA** [comment]
Please read ReadMe file to understand that this mod is ONLY interested in PIXEL STOCK FIRMWARE.

If you have a problem with custom ROM, please change it or report to Developer of the custom ROM.
