### ISSUE TITLE
Taskbar Mode 

### ISSUE THREAD

**Issue by JDKamalakar** [siavash79/PixelXpert#836]
What's on your mind?

Instead of using AOSP Taskbar use of Pixel exclusive taskbar that is integrated with Pixel Launcher.

Benefits: Better App suggestions, Better Look, Better Performance, Allows Pixel's App Drawer Access including it's powerful search.

Is this feature implemented on any other app/mod/rom? please specify
Yes in base Pixel Stock Rom if you change DP To 600 or if you use pixel fold.

Note: If you want working video just tell me I have the video. 
![Screenshot_20240424-155357](https://github.com/siavash79/PixelXpert/assets/101495154/7162b4b7-b072-4da5-9b78-d6d8870910ab)
![Screenshot_20240424-155352](https://github.com/siavash79/PixelXpert/assets/101495154/473ff652-611e-4ccf-b53b-e146018f4842)

**Comment by EleoXDA** [comment]
Is this a bugreport? A feature request? A 3rd party app that you are trying to advertise? What is it?

**Comment by JDKamalakar** [comment]
Feature Request, No it's not 3rd party app advertising. 
I am just making a feature request so that users can have pixels default taskbar instead of the current taskbar with only limited features.

**Comment by EleoXDA** [comment]
They are the same. You get the same taskbar on PixelXpert as you have increased dpi to 600

**Comment by JDKamalakar** [comment]
No it's not you can clearly see the screenshot.

**Comment by EleoXDA** [comment]
> No it's not you can clearly see the screenshot.

It is same.
+ you can also have recent apps instead of standard apps in list
