### ISSUE TITLE
Allow notifications on lockscreen while using face unlock with skip lockscreen 

### ISSUE THREAD

**Issue by Cr0vis** [siavash79/PixelXpert#837]
What's on your mind? 
When using face unlock with skip lockscreen, notifications aren't shown. Seems counterintuitive when you just wanna see  notifs without unlocking

![Screenshot_20240424-112431.png](https://github.com/siavash79/PixelXpert/assets/99766020/7b2f3be7-6ce9-4938-b04e-f3a2cae10e5d)

Is this feature implemented on any other app/mod/rom? please specify
Nope

**Comment by siavash79** [comment]
There's no point in showing notifications when once you look at them the screen gets unlocked immediately. Google did it right already
