### ISSUE TITLE
[Bug] Pixel Fold incompatibility

### ISSUE THREAD

**Issue by drake-lol** [siavash79/PixelXpert#838]
### Describe the issue

When I open PixelXpert, I am greeted with a message saying that my device/firmware is incompatible despite being on a pixel with stock firmware. As far as I'm aware, the only issue that seems to arise from this is the quick settings tile count causing there to be lag when either unfolding/folding, or when I change my screen orientation.

### Steps to reproduce

1. Open PixelXpert
2. Read incompatibility message
3. Change tile count rows/columns, etc.
4. Change orientation or fold/unfold
5. Phone hangs for a couple seconds

### Expected behavior

Pixel fold should be compatible

### Your device setup (Please take some time to give correct information here)

1. Google Pixel Fold
2. Android 14 (Build AP1A.240405.002.A1)
3. April 5th, 2024
4. 27.0
5. 
![Screenshot_20240429-134811](https://github.com/siavash79/PixelXpert/assets/70350894/d4c1770f-bafa-48b0-a8dd-b7e5ad27b143)
6.
![Screenshot_20240429-134818](https://github.com/siavash79/PixelXpert/assets/70350894/58698581-7233-4f24-92f3-1f4e5a75b8e6)
7.
![Screenshot_20240429-134829](https://github.com/siavash79/PixelXpert/assets/70350894/991e6ef4-8bfc-42fb-8e72-ad334b3fcef4)

**Comment by EleoXDA** [comment]
Hanging for seconds is normal.

And since QPR2 sources are not yet out, we cannot call it fully compatible
