### ISSUE TITLE
6GHZ Hotspot

### ISSUE THREAD

**Issue by MonkeySaint** [siavash79/PixelXpert#842]
What's on your mind?

There is an option to enable wifi 6ghz hotspots on pixel phones but it's disabled by default in the USA and Canada. It would be nice if you could make it so it can be enabled on any device. I have found that in some parts of the us 5GHZ is also disabled which is extremely annoying when trying to share my network to my laptop.

![Screenshot_20240523-104108](https://github.com/siavash79/PixelXpert/assets/62266035/9ca261c5-b77f-4795-ba48-ce39f91c6594)

Is this feature implemented on any other app/mod/rom? please specify

I have not seen this in any other roms or modules and couldn't find anyone who did it.

**Comment by EleoXDA** [comment]
We do not have access to 6Ghz to test it. If you can find a 3rd party app or a module, please link it

**Comment by MonkeySaint** [comment]
I couldn't but I also cannot access 5GHZ in alot of places. I assume it's the same check. I have searched for some modules to do it before and never found any.
