### ISSUE TITLE
[Bug] Auto-generate missing themed icons not working

### ISSUE THREAD

**Issue by TGSAN** [siavash79/PixelXpert#843]
### Describe the issue

Auto-generate missing themed icons is not working on Android 15 (AP31.240426.023)

### Steps to reproduce

enable option in canary 360

### Your device setup (Please take some time to give correct information here)

Google Pixel 7 Pro
Android 15 Beta (AP31.240426.023)
2024/5/5

**Comment by EleoXDA** [comment]
Please do not leave Logs empty

**Comment by TGSAN** [comment]
It works after reboot device.
