### ISSUE TITLE
Feature Request: Adding more lock screen clock themes

### ISSUE THREAD

**Issue by RevealedSoulEven** [siavash79/PixelXpert#844]
What's on your mind?
Like google provide very few lockscreen designs, can we somehow add more designs to it? If yes please add some samples in the app and also if we could add our own custom lockscreen clock themes in any way like XML or whatever google uses, so it would be nice for us to customise these things too. And same feature can be used for other UI of the phone too.

Is this feature implemented on any other app/mod/rom? please specify
Few roms like EvolutionX and cherishOS have option to modify that lockscreen clocks even it's not directly from the google wallpapers app or the home screen but from the phone settings. But they also don't have the custom made importing system.
I hope if you can try adding few examples so that we can create PR and add more for the users.

Thank you

**Comment by EleoXDA** [comment]
Try using Iconify
