### ISSUE TITLE
"Force AOD while charging" only takes effect under specific conditions

### ISSUE THREAD

**Issue by b02860de585071a2** [siavash79/PixelXpert#846]
### Describe the issue

When "force AOD while charging" is enabled, it will not take effect unless SystemUI is restarted *WHILE CHARGING*. Restarting SystemUI/the device without a power source  has no effect.

### Steps to reproduce

1. Enable "force AOD while charging"
2. Restart SystemUI (or device) while on battery
3. Plug in device, see no change in behavior
4. Restart SystemUI again while still connected to power
5. Observe expected behavior

### Expected behavior

AOD should not require a SystemUI restart while actively charging.

### Your device setup (Please take some time to give correct information here)

I have tested and replicated this behavior on stock Android 13 and 14, as well as LineageOS (currently using) and a handful of AOSP-based ROMs. 

I understand that custom ROMs are not technically supported, I just want to provide more context. Clean flashing the latest stock A14 does not fix the bug (I tried).

- Pixel 8 Pro (husky)
- Stock Android 14 (AP1A.240505.005) -or- LineageOS 21 (AP1A.240505.005)
- Magisk: 27.0
- Root apps: see attached
- Magisk modules: see attached
- LSPosed: currently v. 1.9.3_mod from [this fork](https://github.com/mywalkb/LSPosed_mod), the bug also occurs on 1.9.2 of [the now-archived original](https://github.com/LSPosed/LSPosed)
- LSPosed modules: see attached

![magisk-1](https://github.com/siavash79/PixelXpert/assets/96025485/193a69c4-5149-422a-bdc2-9a2bf1d62dc2)
![magisk-2](https://github.com/siavash79/PixelXpert/assets/96025485/828f708f-0fa2-468e-9c88-14d6037db7d6)
![magisk-3](https://github.com/siavash79/PixelXpert/assets/96025485/00dd1d7c-17ea-47be-88b8-fa63c8269c49)
![lsposed](https://github.com/siavash79/PixelXpert/assets/96025485/50ef5236-775f-40c7-b083-c23053bccf29)

### Logs

I rebooted, confirmed the unwanted behavior, restarted SystemUI (still unwanted behavior), then began charging and restarted SystemUI again (correct behavior). 

[LSPosed_2024-05-30T16_36_44.071326.zip](https://github.com/user-attachments/files/15506491/LSPosed_2024-05-30T16_36_44.071326.zip)

**Comment by b02860de585071a2** [comment]
For what it's worth, I have tried resetting PixelXpert to defaults and *only* enabling the "force AOD while charging" option. 

This had no effect, so I do not believe it's an interaction with any other setting. Maybe this helps save some debugging time.

**Comment by siavash79** [comment]
Bug report from custom ROM is not acceptable. Closing

**Comment by b02860de585071a2** [comment]
> Bug report from custom ROM is not acceptable. Closing

Again, this occurs on stock Android 14 as well. I flashed back to it last week and confirmed the same behavior.

Do I really have to flash back again and reopen?

**Comment by b02860de585071a2** [comment]
I have time tonight. 

Here are logs from a completely fresh clean flash of A14 (AP1A.240505.005) on the same P8P, done with full factory images. Device was factory reset and stock firmware flashed on BOTH slots prior to this. 

Logs captured with literally nothing installed, besides Magisk + the required modules to run PixelXpert. Exact same issue.

Magisk 27.0
LSPosed 1.9.2
PixelXpert canary 360

[LSPosed_2024-06-02T22_34_43.385079.zip](https://github.com/user-attachments/files/15528843/LSPosed_2024-06-02T22_34_43.385079.zip)

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
