### ISSUE TITLE
[Bug] Loss of functionality in canary-363 for long press torch feature

### ISSUE THREAD

**Issue by bdr99** [siavash79/PixelXpert#847]
### Describe the issue

Cannot achieve the same behavior that was possible from canary-323 to canary-362 (see below).

### Steps to reproduce

From **canary-323** to **canary-362**, the "Long press Power button for torch" feature (when the screen is on) worked like this:
- When the power button is long pressed with the screen on...
  - If the torch is on, turn it off.
  - If the torch is off, perform the default action (open the power menu).

In **canary-363**, if we set the "Long press power button" action to "Toggle torch", which seems to be the closest equivalent to the setting that existed in previous versions, it works like this instead:
- When the power button is long pressed with the screen on...
  - If the torch is on, turn it off.
  - If the torch is off, turn it on.

There seems to be no way to achieve the previous functionality of performing the default action when the torch is already off.

Steps to reproduce
1. In Miscellaneous -> Remap physical buttons, under "While screen is on", set "Long press power button" to "Toggle torch".
2. With the screen on and the torch off, long press the power button.

### Expected behavior

There should be a way to configure a long press to turn off the torch if it is on, but otherwise perform the default long press action, as was possible in all versions from canary-323 to canary-362.

### Your device setup (Please take some time to give correct information here)

- Google Pixel 8 Pro - Stock firmware
- Android 14
- April 2024 security patch
- Magisk 27.0
- Apps with root access: Better Internet Tiles, Pixel Xpert, ReVanced Manager, Shell, Solid Explorer, Swift Backup
- Magisk modules: LSPosed 1.9.2, Pixel Xpert canary-363
- LSPosed version: 1.9.2
- LSPosed modules: Pixel Xpert canary-363

### Logs

[LSPosed_2024-06-05T23_33_38.905911.zip](https://github.com/user-attachments/files/15601002/LSPosed_2024-06-05T23_33_38.905911.zip)

**Comment by EleoXDA** [comment]
That is intended. You literally enabled "TOGGLE TORCH" when "WHILE SCREEN IS ON" for power button?

What else did you expect?

**Comment by bdr99** [comment]
@EleoXDA I agree that the current behavior matches the description of the setting. That wasn't my issue.

I just expected to be able to recreate the old behavior through some other combination of settings. I didn't expect to lose functionality when upgrading to canary-363.

**Comment by gygabyte017** [comment]
@bdr99 it keeps working for me, even if I set any action on long power button press on screen on, if the torch is on that action is overridden by the action "power torch off".

**Comment by EleoXDA** [comment]
> @EleoXDA I agree that the current behavior matches the description of the setting. That wasn't my issue.
> 
> My issue is just that something that was possible in canary-362 is no longer possible in canary-363. I expected to be able to recreate the old behavior through some other combination of settings.

Then your description is wrong. You reported it as bug, but should have been a feature request, as this is not a bug _per se_
