### ISSUE TITLE
Remove call record announcement not working in canary 365 [Bug] 

### ISSUE THREAD

**Issue by kinsey6** [siavash79/PixelXpert#848]
### Describe the issue

Title describes issue. 

### Steps to reproduce

Ive toggle switch, FC both apps. Rebooted with same result

### Expected behavior

Silence call record announcment

### Your device setup (Please take some time to give correct information here)

Google Pixel 8 pro 
Magisk 27.0
![Screenshot_20240610-110331](https://github.com/siavash79/PixelXpert/assets/49046721/2186f8c1-3b0d-4221-8bf1-271f9a809876)
![Screenshot_20240610-110354](https://github.com/siavash79/PixelXpert/assets/49046721/b5f04e70-4925-43bb-97e3-0ba4286d6e7b)

**Comment by siavash79** [comment]
I'm actively using it without any problems. Make sure everything is okay in hooks tab

**Comment by EleoXDA** [comment]
@kinsey6 can you check again please?

**Comment by kinsey6** [comment]
I reverted back to stock before checking if it was working

**Comment by EleoXDA** [comment]
> I reverted back to stock before checking if it was working

So you were not using stock pixel firmware?

**Comment by kinsey6** [comment]
> > I reverted back to stock before checking if it was working
> 
> So you were not using stock pixel firmware?

Ops wrong term, I unrooted and relocked my BL.
