### ISSUE TITLE
[Bug] System UI crashing after reboot 

### ISSUE THREAD

**Issue by selfmusing** [siavash79/PixelXpert#850]
### Describe the issue

SystemUI crashes 4-5 times in a row as soon as my device boots after flashing the module...

### Steps to reproduce

1. Flash PixelXpert Canary Module
2. Reboot
3. SystemUI crash on lockscreen 5-6 times 
4. Then it gets normal , but PixelXpert modifications gets reverted.

### Expected behavior

It was working fine for me a few weeks ago with this same setup , I have no idea what happened wrong,,

### Your device setup (Please take some time to give correct information here)

Redmi Note 7 Pro - Xiaomi
Android !4 QPR2
JUNE sec patch , 2024
Apps with superuser acces : PixelXpert , MT Manager, SystemUI, Android System, App Manager, Logcat Reader, LSPosed Manager , Shell, Termux
Kernelsu version- 11880 
![Screenshot_20240611-182345_KernelSU](https://github.com/siavash79/PixelXpert/assets/109387456/953f04a2-6c9d-46cd-959e-620d71ab216a)
![Screenshot_20240611-182343_KernelSU](https://github.com/siavash79/PixelXpert/assets/109387456/beaee849-560a-415a-8d9f-9d7d96743e1d)
![Screenshot_20240611-182339_KernelSU](https://github.com/siavash79/PixelXpert/assets/109387456/900114ef-e89c-4992-9733-04f7639f1b86)
![Screenshot_20240611-182336_KernelSU](https://github.com/siavash79/PixelXpert/assets/109387456/b9ee98e0-1620-4a86-b7b1-e18e638c9159)

LSPOSED INFO : 
![Screenshot_20240611-182638_LSPosed 1](https://github.com/siavash79/PixelXpert/assets/109387456/089599c0-bd61-4704-b329-17b8bd7a5f78)

![Screenshot_20240611-182634_LSPosed 1](https://github.com/siavash79/PixelXpert/assets/109387456/c9bea6ff-5e6f-4005-affa-06655acff5d2)
![Screenshot_20240611-182632_LSPosed 1](https://github.com/siavash79/PixelXpert/assets/109387456/8ce121eb-046d-49db-840a-9738027c6672)

### Logs

[logcat.txt](https://github.com/user-attachments/files/15788136/logcat.txt)
CRASH LOGCAT !!

**Comment by selfmusing** [comment]
> We only support google pixel devices with stock pixel firmware

So, it's a common issue after A14 QPR2 Update ?
Coz everything was working fine before...👀

**Comment by barsikus007** [comment]
same on my pixel 7 pro after QPR2 with latest stable release of pixelxpert and kernelsu

**Comment by selfmusing** [comment]
> same on my pixel 7 pro after june AP2A update with latest stable release of pixelxpert and kernelsu

Damn 💀

**Comment by barsikus007** [comment]
oh, nvm
I switched to canary build and saw prompt about "Umount modules by default" thing
