### ISSUE TITLE
Brightness Changes when sliding Status bar [Bug] 

### ISSUE THREAD

**Issue by gnomiik** [siavash79/PixelXpert#851]
### Describe the issue

Brightness Changes when sliding Status bar even when this feature is disabled in settings

### Steps to reproduce

To reproduce you must enable  "Show brightness slider on QQS Panel". Then after some time (not always immediately) start swiping the status bar and the brightness will change. 

### Expected behavior

The brightness should not change when swiping the status bar

### Your device setup (Please take some time to give correct information here)

This happens in Android 12, 13, and 14. This bug exists on all devices.

**Comment by EleoXDA** [comment]
We only support google pixel devices with stock pixel firmware

**Comment by gnomiik** [comment]
This should not be closed. This is happening on pixel phone with stock firmware.
