### ISSUE TITLE
Hide Statusbar Clock in homescreen

### ISSUE THREAD

**Issue by jorgedasilva91** [siavash79/PixelXpert#852]
Would it be possible to add a function to hide the clock in the status bar when the home screen is shown?

I can do this with a shell script by detect current activity (home screen) and change icon_blacklist by adding "clock"

SBI=$(settings get secure icon_blacklist)
settings put secure icon_blacklist "${SBI},clock"

It would be interesting
Thank you

**Comment by EleoXDA** [comment]
We do not use pixel launcher in team. All of us use 3rd party apps. If you can, do a PR and we can check code afterwards

**Comment by siavash79** [comment]
We did have such a request before. It's not planned because it doesn't make sense to hide it only because custom roms do so. No added value can be assumed
