### ISSUE TITLE
[Bug] Status bar always displays 4 notification icons + dot, unregarding of maximum number setting

### ISSUE THREAD

**Issue by gygabyte017** [siavash79/PixelXpert#853]
### Describe the issue

Whatever value I put under "maximum number of notification icons, I always see maximum 4 icons + dot when there are more than 4 (see screenshot)

### Steps to reproduce

Set any number N different from 4 or empty, and wait until there are more than N icons to see that status bar always displays 4 notification icons + dot unregarding of N.

### Expected behavior

To see a maximum number of notification icons as determined by the corresponding setting

### Your device setup (Please take some time to give correct information here)

- Google Pixel 8
- 14
- AP2A.240605.024
- 27.0
- Logcat Reader, MiXplorer, Nova Launcher, Pixel Xpert, Shell, SSHelper, Swift Backup, Termux, zygisk-detach
- Pixel Expert (canary-367), Play Integrity Fix (v15.9.9), YouTube ReVanced eXtended (v19.20.34), Zygisk - LSPosed (v1.9.3 mod 7244), zygisk-detach (v1.16.1)
- v1.9.3 mod 7244

- Only Pixel Xpert

### Logs

![Screenshot_20240616-182548](https://github.com/siavash79/PixelXpert/assets/13131569/89339af4-a5ec-47d6-8d33-fc9cb40a495b)
[PixelXpert_Config.zip](https://github.com/user-attachments/files/15859082/PixelXpert_Config.zip)
[LSPosed_2024-06-16T22_04_16.360559.zip](https://github.com/user-attachments/files/15859705/LSPosed_2024-06-16T22_04_16.360559.zip)

**Comment by EleoXDA** [comment]
You need to use LSposed_mod instead of standard one:
http://github.com/mywalkb/lsposed_mod

**Comment by gygabyte017** [comment]
Thank you very much, done that, updated issue description and also uploaded LSposed logs (the issue still applies!)

**Comment by EleoXDA** [comment]
I noticed that you are still on android 14. It could be that with newer canary versions Android 14 compatibility is broken. Try to move back to a version which this was working still. We will not be maintaining old versions on canary versions anymore.
