### ISSUE TITLE
Hide system icons (include clock) in the status bar

### ISSUE THREAD

**Issue by tooadstool** [siavash79/PixelXpert#855]
Hide system icons (include clock) in the status bar，like PixelExperience

![20240625194825](https://github.com/siavash79/PixelXpert/assets/26811405/1b700abb-15bb-4fcb-a9fb-9be8cb09851a)
![20240625194837](https://github.com/siavash79/PixelXpert/assets/26811405/c30c29c0-66f7-4258-bdf5-cccf339bf056)

**Comment by EleoXDA** [comment]
read wiki on our repo about SystemUI Tuner

**Comment by tooadstool** [comment]
> read wiki on our repo about SystemUI Tuner

i get it now, thank you.
