### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Den555By** [siavash79/PixelXpert#856]
I'm using that mod on Xiaomi Redmi Note 9S, PixelOS, Android 14. Although in app displayed message it is not compatible, it seems to work really well.
So, i want to suggest some features.
1. Highlight brightness indicator in notifications panel white color on light theme, and black on dark theme.
2.  Ability to hide Google Search in bottom of home screen and hide  widget "The Most Important Thing"(i believe it called some like that)on top of the home screen.
3. Ability to choose use app menu or just have all apps on desk(just like MIUI).

**Comment by EleoXDA** [comment]
Good job. Now read ReadMe file to understand this MOD is made only for pixel devices with stock pixel firmware
