### ISSUE TITLE
[Bug] SystemUI keep restarting in Canary-371

### ISSUE THREAD

**Issue by improbir** [siavash79/PixelXpert#857]
### Describe the issue

systemui keep restarting as soon as device boots to lock screen.

### Steps to reproduce

upto canary-361 everything seems fine. The problem arises in canary-362 

### Expected behavior

Device should normally boot right after updating the canary modules instead of that it just crashing my systemui at lock screen.

### Your device setup (Please take some time to give correct information here)

Realme XT
PixelOS 14 May security patch
Magisk 27.1

### Logs

[logs.txt](https://github.com/user-attachments/files/16045185/logs.txt)

**Comment by improbir** [comment]
all the problems started from here :- https://github.com/siavash79/PixelXpert/commit/3709edd798fd8530c908bcc12d758c8525c478a1

**Comment by improbir** [comment]
06-30 20:44:35.351  4812  4812 E AndroidRuntime: FATAL EXCEPTION: main
06-30 20:44:35.351  4812  4812 E AndroidRuntime: Process: com.android.systemui, PID: 4812
06-30 20:44:35.351  4812  4812 E AndroidRuntime: java.lang.ClassCastException: com.android.systemui.settings.brightness.BrightnessSliderView cannot be cast to android.widget.FrameLayout
06-30 20:44:35.351  4812  4812 E AndroidRuntime: 	at sh.siava.pixelxpert.modpacks.systemui.BrightnessSlider$3.lambda$afterHookedMethod$2$sh-siava-pixelxpert-modpacks-systemui-BrightnessSlider$3(BrightnessSlider.java:182)
06-30 20:44:35.351  4812  4812 E AndroidRuntime: 	at sh.siava.pixelxpert.modpacks.systemui.BrightnessSlider$3$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
06-30 20:44:35.351  4812  4812 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
06-30 20:44:35.351  4812  4812 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-30 20:44:35.351  4812  4812 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
06-30 20:44:35.351  4812  4812 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
06-30 20:44:35.351  4812  4812 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8501)
06-30 20:44:35.351  4812  4812 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-30 20:44:35.351  4812  4812 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
06-30 20:44:35.351  4812  4812 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by xDARKxDEVILx** [comment]
I have the same issue too, if i try anything after canary 360 ( maybe 361 works as the author says i haven't tried it yet) the screen keeps restarting and after a while it fails to load the changes that was done to it and allows me to use my phone 
When i go to pixelxprt in connected packages i get that SystemUI is disconnected and I can't get it to work 
I tried the latest stable version too and it has the same issue 

I am using a Xiaomi mi 9t with an Android 13 rom called project elixir

**Comment by EleoXDA** [comment]
Perfect! Now read the README file that says this is ONLY COMPATIBLE WITH STOCK PIXEL FIRMWARE ON GOOGLE PIXEL DEVICES!

**Comment by EleoXDA** [comment]
And PLEASE, NEVER install ANY app or module WITHOUT reading documentation. This is an open-source app and we are NOT responsible for whatever happens on your devices. In next version we may very well brick devices which install this module on non-compatible firmware!
