### ISSUE TITLE
3.4.0 App crashes when pressing Lockscreen

### ISSUE THREAD

**Issue by Entree3k** [siavash79/PixelXpert#859]
Whenever I press the tab for lockscreen the app closes out. Every other tab works fine just lockscreen causes a crash. I have tried reinstalling

**Comment by EleoXDA** [comment]
see README page for compatibility

**Comment by Entree3k** [comment]
My device is fully compatible based on the Readme

**Comment by EleoXDA** [comment]
Then obviously you did NOT open a BUGREPORT issue. Because your issue contains NO debuggable information

**Comment by EleoXDA** [comment]
> My device is fully compatible based on the Readme

![Screenshot_20240702-182909.png](https://github.com/siavash79/PixelXpert/assets/27622683/a88ad28c-ced0-420e-8c69-a7df28557378)

If you fail to provide required INFO for BUGREPORT then we cannot help you
