### ISSUE TITLE
[Bug] Force Closes When Pressing Lockscreen Tab

### ISSUE THREAD

**Issue by Entree3k** [siavash79/PixelXpert#860]
### Describe the issue

The app force closes when pressing lockscreen tab

### Steps to reproduce

1. Open the app
2. Press lock screen tab
3. That is it the app should force close

### Expected behavior

I should be able to open the lockscreen tab

### Your device setup (Please take some time to give correct information here)

Google Pixel 5a
Android version 14
Stock Android Security update date Oct 5, 2023
Magisk version 27.0
List of apps that have been granted root access
     Adaway
     Pixel Xpert
     Shizuku
     Swift Backup
     Themer
List of your magisk modules and versions
     Google Photos Unlimited Backup 1.0
     Pixel Xpert 3.4.0
     Systemles Hosts 1.0
     Themer 1.2.3-Rev1-B1
     Zygisk - LSPosed 1.9.2
LSposed version 1.9.2 (7024)

**Comment by EleoXDA** [comment]
You forgot Logs from LSPosed

**Comment by Entree3k** [comment]
[log.txt](https://github.com/user-attachments/files/16075221/log.txt)

**Comment by EleoXDA** [comment]
> [log.txt](https://github.com/user-attachments/files/16075221/log.txt)



> [log.txt](https://github.com/user-attachments/files/16075221/log.txt)

wrong again. re-read the description to see which logs you should have sent. Create a new bugreport with everything inside

**Comment by Entree3k** [comment]
Hold on there buck·a·roo I got you
[log.txt](https://github.com/user-attachments/files/16090216/log.txt)

**Comment by EleoXDA** [comment]
> Hold on there buck·a·roo I got you [log.txt](https://github.com/user-attachments/files/16090216/log.txt)

NO! It should be the zip file generated by LSPosed! And use correct LSPosed version! Yours is old

**Comment by Entree3k** [comment]
You seem a little tense

**Comment by Entree3k** [comment]
You seem a little tense, also best friend based on the github repository my LSposed is the most recent version

**Comment by EleoXDA** [comment]
> Also best friend based on the github repository my LSposed is the most recent version

you are wrong. lsposed has not been updated for a while. so you should use LSPosed_mod. Not the original LSPosed

**Comment by Entree3k** [comment]
If it hasn't been updated in a while and I said based on the github repository I have the most recent version that's not being wrong

**Comment by EleoXDA** [comment]
> If it hasn't been updated in a while and I said based on the github repository I have the most recent version that's not being wrong

Ok. Your setup is wrong. You either update it or not be able to use app. Bye
