### ISSUE TITLE
depth effect wallpaper clock opacity and wallpaper position [Bug] 

### ISSUE THREAD

**Issue by panmeek** [siavash79/PixelXpert#861]
### Describe the issue

Clock is always visible (slightly transparent but still visible) despite having the wallpaper foreground opacity set to 255. The lockscreen wallpaper position changes after applying the effect or the wallpaper gets extended by the AI.

### Steps to reproduce

1. Activate the depth effect wallpaper.
2. Set the wallpaper foreground opacity to 255.
3. Restart SystemUI.
4. Check the lockscreen.

### Expected behavior

The clock should appear completely behind an object of the wallpaper (be completely invisible behind it) and the wallpaper position shouldn't change.

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7
- Android 14
- July security patch
- Magisk 27.0
- Pixel Xpert
- Pixel Xpert 3.4.0, Play Integrity Fix v16.5, Systemless Hosts 1.0, Zygisk - LSPosed v1.9.3_mod
- LSPosed v1.9.3_mod
- Pixel Xpert 3.4.0

### Logs

----part 1 start----
[ 2024-07-03T01:29:15.436     1000:  1399:  1399 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2024-07-03T01:29:15.499     1000:  1399:  1399 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2024-07-03T01:29:19.046    10251:  2110:  2110 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2024-07-03T01:29:19.136    10251:  2110:  2110 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2024-07-03T01:29:19.236    10291:  2128:  2128 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2024-07-03T01:29:19.312    10291:  2128:  2128 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2024-07-03T01:29:19.593    10291:  2128:  2128 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-03T01:29:19.593    10291:  2128:  2128 I/LSPosed-Bridge  ] PixelXpert Records: 42
[ 2024-07-03T01:29:19.614     1000:  1399:  1806 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-03T01:29:19.614     1000:  1399:  1806 I/LSPosed-Bridge  ] PixelXpert Records: 42
[ 2024-07-03T01:29:19.616    10251:  2110:  2110 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-03T01:29:19.619    10251:  2110:  2110 I/LSPosed-Bridge  ] PixelXpert Records: 42
[ 2024-07-03T01:29:19.762     1001:  2371:  2371 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2024-07-03T01:29:19.849     1000:  2382:  2382 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2024-07-03T01:29:19.849     1001:  2371:  2371 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2024-07-03T01:29:19.950     1001:  2371:  2371 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-03T01:29:19.951     1001:  2371:  2371 I/LSPosed-Bridge  ] PixelXpert Records: 42
[ 2024-07-03T01:29:19.996     1000:  2382:  2382 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2024-07-03T01:29:20.082     1000:  2382:  2382 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-03T01:29:20.082     1000:  2382:  2382 I/LSPosed-Bridge  ] PixelXpert Records: 42
[ 2024-07-03T01:29:20.474    10252:  2794:  2794 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2024-07-03T01:29:20.535    10252:  2794:  2794 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2024-07-03T01:29:20.580    10252:  2794:  2794 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-03T01:29:20.581    10252:  2794:  2794 I/LSPosed-Bridge  ] PixelXpert Records: 42
[ 2024-07-03T01:29:20.739     1000:  1399:  1399 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-03T01:29:20.740     1000:  1399:  1399 I/LSPosed-Bridge  ] PixelXpert Records: 42
[ 2024-07-03T01:29:20.911     1000:  1399:  1399 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-03T01:29:20.912     1000:  1399:  1399 I/LSPosed-Bridge  ] PixelXpert Records: 42
[ 2024-07-03T01:29:22.100    10133:  3193:  3193 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2024-07-03T01:29:22.184    10133:  3193:  3193 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2024-07-03T01:29:22.401    10133:  3193:  3193 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-03T01:29:22.407    10133:  3193:  3193 I/LSPosed-Bridge  ] PixelXpert Records: 42
[ 2024-07-03T01:29:46.866    10251:  8318:  8318 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2024-07-03T01:29:46.947    10251:  8318:  8318 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2024-07-03T01:29:47.046    10251:  8318:  8318 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-03T01:29:47.058    10251:  8318:  8318 I/LSPosed-Bridge  ] PixelXpert Records: 42

**Comment by EleoXDA** [comment]
Wrong logs. Reread the bugreport description to know which logs you should have sent. 

Try to readjust wallpaper dim effect and see whether it works.
