### ISSUE TITLE
[Bug] Incomplete white QS theme

### ISSUE THREAD

**Issue by Eggmanplant** [siavash79/PixelXpert#862]
### Describe the issue

The white QS theme is incomplete

### Steps to reproduce

1. Enable the white QS theme
2. Look. The Edit Tiles menu's text is unreadable, and the brightness slider is still black when sliding.

### Your device setup (Please take some time to give correct information here)

- Google Pixel 7a Android 15 Beta 3.1 - KernelSU 1.0.0 - PixelXpert 3.4.0 - LSPosed 1.9.3_mod - Sui 13.5.1 - ReZygisk 2be1ccc - Magical OverlayFS 3.2.2 - NoStorageRestrict 0.5.0 (LSPosed) - Classic Power Menu 1.7.2 (LSPosed)

### Logs

----part 1 start----
[ 2024-07-07T09:43:01.479     1000:  1629:  1629 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2024-07-07T09:43:01.536     1000:  1629:  1629 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2024-07-07T09:43:07.698    10246:  2417:  2417 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2024-07-07T09:43:08.013    10551:  2482:  2482 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk
[ 2024-07-07T09:43:08.052    10246:  2417:  2417 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2024-07-07T09:43:08.083    10551:  2482:  2482 I/LSPosed-Bridge  ]   Loading class sh.siava.pixelxpert.XPEntry
[ 2024-07-07T09:43:08.326    10551:  2482:  2482 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-07T09:43:08.327    10551:  2482:  2482 I/LSPosed-Bridge  ] PixelXpert Records: 150
[ 2024-07-07T09:43:08.379     1000:  1629:  2070 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-07T09:43:08.380     1000:  1629:  2070 I/LSPosed-Bridge  ] PixelXpert Records: 150
[ 2024-07-07T09:43:08.380     1000:  1629:  1629 I/LSPosed-Bridge  ] PixelXpert Version: 3.4.0
[ 2024-07-07T09:43:08.381     1000:  1629:  1629 I/LSPosed-Bridge  ] PixelXpert Records: 150
[ 2024-07-07T09:43:08.406     1000:  2715:  2715 I/LSPosed-Bridge  ] Loading legacy module sh.siava.pixelxpert from /system/priv-app/PixelXpert/PixelXpert.apk

**Comment by EleoXDA** [comment]
Not that important. It is a very low key issue

**Comment by Eggmanplant** [comment]
But it's very annoying for me

**Comment by siavash79** [comment]
With android interface switching to compose, even to the current level was extremely tricky. I'm not planning to go any further on this

**Comment by EleoXDA** [comment]
> But it's very annoying for me

code is open source. if you find it annoying, then you can also spend some time to fix it ;)

**Comment by Eggmanplant** [comment]
Yeah, I fixed some isssues in some project myself. But the white QS overlay seems to be proprietary.
