### ISSUE TITLE
Com.android.settings permanently non-responding

### ISSUE THREAD

**Issue by HarriBuh** [siavash79/PixelXpert#863]
Not sure whether this is a bug and whether it causes any bugs, but "com.android.settings" is always non-respoding according to the app. App version doesn't matter.

![Screenshot_20240714-092635.png](https://github.com/user-attachments/assets/139af1d6-0a5c-438f-9458-1a7d2bacb3a2)

Google Pixel 7
Android 14
Rooted with Magisk (canary 27004)

**Comment by EleoXDA** [comment]
It is not that vital. Whenever you open the settings app and recheck this value, it will respond. When app is killed or terminated, it will not respond. Das ist die Lebensregel :)

**Comment by EleoXDA** [comment]
Did you check to open the settings app and then rerun this?

**Comment by EleoXDA** [comment]
> > Did you check to open the settings app and then rerun this?
> 
> It works that way. So in addition to your explanation before, I take it that this is just a "little" bug (it still doesn't work as intended though), with no negative consequences.

It is not bug. It is how android is intended to work. Settings mods start working ONLY when settings app is running. and once it is open, the mods also run. If it is not open, there is nothing to mod. Simple.
