### ISSUE TITLE
Does this work on android 14 (one UI) (I have a samsung s23)?

### ISSUE THREAD

**Issue by Luca-Girotti** [siavash79/PixelXpert#865]
Thanks in advanced!

**Comment by gqqnbig** [comment]
No, it doesn't work, at least for status bar tweaks such as network monitor.

**Comment by EleoXDA** [comment]
It definitely does not work on ONE UI! Please at least read ReadMe file before writinh a new post @Luca-Girotti

**Comment by gqqnbig** [comment]
@EleoXDA  To be honest, the README only says "Any custom ROM is not tested". As regualar users, we don't know differences from Pixel to One UI, which may be quite obvious to Android developers.

**Comment by EleoXDA** [comment]
> @EleoXDA  To be honest, the README only says "Any custom ROM is not tested". As regualar users, we don't know differences from Pixel to One UI, which may be quite obvious to Android developers nevertheless.

Is it clearer now @Luca-Girotti @gqqnbig 

![Screenshot_20240731-180250.png](https://github.com/user-attachments/assets/af834878-8f83-4c08-a5d7-3bd5aea1dd1e)

**Comment by gqqnbig** [comment]
Thank you for the updates!
