### ISSUE TITLE
[BUG] App screws up my phone

### ISSUE THREAD

**Issue by HarriBuh** [siavash79/PixelXpert#867]
I know, the title is garbage, but I'm very annoyed by the negative leftovers from this app after I

1.  Reset

2. Deactivated the app

My phone won't accept any unlocking option any more (neither Face- nor Fingerprint unlock) and will occasionally restart itself.

I verified by doing the steps above to make sure PixelXpert shouldn't at least theoretically mess with my phone any more. I even deinstalled the module completely and the bugs still occured.

Since nothing crashed, I couldn't collect any logs so far.

What should I do?

Pixel 7
Android 14
Magisk (latest)
PixelXpert 3.4.0

**Comment by EleoXDA** [comment]
What about LSPosed?

> I know, the title is garbage, but I'm very annoyed by the negative leftovers from this app after I
> 
> 1. Reset
> 2. Deactivated the app
> 
> My phone won't accept any unlocking option any more (neither Face- nor Fingerprint unlock) and will occasionally restart itself.
> 
> I verified by doing the steps above to make sure PixelXpert shouldn't at least theoretically mess with my phone any more. I even deinstalled the module completely and the bugs still occured.
> 
> Since nothing crashed, I couldn't collect any logs so far.
> 
> What should I do?
> 
> Pixel 7 Android 14 Magisk (latest) PixelXpert 3.4.0

**Comment by EleoXDA** [comment]
Did you really read ReadMe file?

**Comment by EleoXDA** [comment]
It is pretty much straightforward that you did not follow steps correctly, as this is being used by thousands of users with no issue on 14+ Android version. Since your report is missing ALL the answers to questions regarding bugreport, I will close this bugreport and will ask you to open a new one, where you follow the guidelines

**Comment by EleoXDA** [comment]
> Yes, LSPosed is properly installed on my devices and running perfectly well. If you could specify your question more, maybe I could provide you with more info.

You most probably are using standard LSPosed. Not the LSPosed_mod that supports Android 14+. Read ReadMe file

**Comment by EleoXDA** [comment]
So, this is the end of discussion in this report. Feel free to open a new one and fill all the necessary details for troubleshooting - otherwise we are wasting each other's time.
