### ISSUE TITLE
[Bug] Fingerprint on AOD is delayed

### ISSUE THREAD

**Issue by MrMcFlyy** [siavash79/PixelXpert#868]
### Describe the issue

Unlock with Fingerprint on AOD is delayed

### Steps to reproduce

1. Lock Phone
2. On AOD press Fingerprint Sensor
3. Wait 3-4 Seconds
4. Use Phone

### Expected behavior

Shouldn't have the waiting time of 3-4 seconds inbetween

### Your device setup (Please take some time to give correct information here)

- Google Pixel 8
- Android 15 Beta 4 (AP31.240617.009)
- 5th July 2024
- Magisk 27001
- Adaway, Call Recorder, FolderSync, Nova Launcher, Pixel Xpert, [SharedUID] Shell, Solid Explorer, Swift Backup
- Call Recorder SKVALEX (2.3.0), Pixel Xpert Canary-375, Play Integrity Fix 16.6, Systemless Hosts, Zygisk LSPosed 7303
- Zygisk LSPosed 7303
- Pixel Xpert Canary-375

### Logs

[M0O8C2~9.LOG](https://github.com/user-attachments/files/16361966/M0O8C2.9.LOG)
[VM8D4C~Q.LOG](https://github.com/user-attachments/files/16361967/VM8D4C.Q.LOG)

**Comment by MrMcFlyy** [comment]
Here you can see a video

https://github.com/user-attachments/assets/f7fcd3dc-1b26-4a81-9da1-d1236e6e4e7b

**Comment by EleoXDA** [comment]
any lsposed modules other than pixelxpert?

**Comment by MrMcFlyy** [comment]
> False logs. Please provide what was requested from lsposed. Which lsposed apl version do you use? hopefully lsposed_mod

Sorry, my fault. This one is the right zip. I tried both canary and stable version of lsposed_mod, both are the same result. Log is with canary 7303.

> any lsposed modules other than pixelxpert?

No, just pixelxpert.

**Comment by MrMcFlyy** [comment]
[LSPosed_2024-07-24T14_35_21.283973.zip](https://github.com/user-attachments/files/16362293/LSPosed_2024-07-24T14_35_21.283973.zip)

**Comment by MrMcFlyy** [comment]
I did some more observations which might help: when an event (e.g. notification or charging) on AOD occured, it unlocks immediately when pressing the FP sensor. Or when i lift it up first. Looks like it is only then ready to unlock fast.

When the phone is just laying around and i try to unlock, it takes 3 seconds to realize the fingerprint button is pressed.

Possibly FP Sensor is disabled when in a state of deep sleep.

**Comment by siavash79** [comment]
Good report, wrong place. You might wanna report it to Google
