### ISSUE TITLE
system ui modifications not working on V3.4.0+

### ISSUE THREAD

**Issue by tilse** [siavash79/PixelXpert#869]
### Describe the issue

the system ui package doesn't respond, so none of the related modifications work

### Steps to reproduce

it works with the system ui package on the previous version, but not on 3.4.0 or canary with A14 and Magisk 27. it tries to check for kernelSU and doesn't find it so i think it doesn't fallback to Magisk properly. i didn't test with kernelSU though.
![Screenshot_20240725-205215_Pixel Xpert](https://github.com/user-attachments/assets/0318da66-9541-490b-a4ab-39907f77a977)

### Your device setup (Please take some time to give correct information here)

xiaomi poco x4 gt
PixelOS custom rom
Android OS version: 14.0
Security patch: FEB 05, 2024
Magisk 27.0
![Screenshot_20240725-205758_Settings](https://github.com/user-attachments/assets/d8417c19-13f5-403d-b964-84bd597a6834)
![Screenshot_20240725-205905_Settings](https://github.com/user-attachments/assets/4d2dc4f7-83a6-4610-8060-e37f331d6d80)

**Comment by EleoXDA** [comment]
Perfect report! Would have been much more perfect if you read the ReadMe file where we say no custom ROM is supported

**Comment by tilse** [comment]
well considering it is working on 3.2.2, it seems like a regression that shouldn't only affect custom roms

**Comment by EleoXDA** [comment]
It does. sorry to hear, but this only works and is adapted to stock pixel firmware on google pixel devices until mentioned otherwise
