### ISSUE TITLE
Colored backgroud in custom before and after clock text

### ISSUE THREAD

**Issue by rexackermann** [siavash79/PixelXpert#874]
What's on your mind?

Look at the clock in the status bar: a backgroud color in the clock.
![Screenshot from 2024-08-09 00-56-51](https://github.com/user-attachments/assets/2eca265e-3a57-4265-9add-fa85bd52c5ba)
It would be nice to see it.

Is this feature implemented on any other app/mod/rom? please specify
I found it in [crdroid 10.5 gsi](https://github.com/naz664/crDroid_gsi/releases/tag/v2024.05.15)

**Comment by EleoXDA** [comment]
use iconify. this is more theming related rather than function. and btw pixelxpert is ONLY supported on google pixel devices with stock pixel firmware. no other firmware is supported.
