### ISSUE TITLE
[Bug] KernelSU cannot add module

### ISSUE THREAD

**Issue by DYSBRT** [siavash79/PixelXpert#875]
### Describe the issue

There is no response when pressing the volume up button when adding a module.

### Steps to reproduce

I used KernelSU to add this module. When it came to "Do you wish to continue?", pressing the volume up and volume down buttons had no effect, so the module could not be added.
![Screenshot_20240813-203301](https://github.com/user-attachments/assets/0e06f051-cca5-4674-814d-6e30667529fa)

### Your device setup (Please take some time to give correct information here)

The device used is pixel 6 pro, and the Android security update is June 5, 2024, Android 14.
![share_2662477423046367130](https://github.com/user-attachments/assets/ec9e6468-937a-4ee5-8d76-91895354a39f)
![share_6777861422397050545](https://github.com/user-attachments/assets/a6959dd7-b9a0-4eb5-93c9-e74411a07c0b)

**Comment by EleoXDA** [comment]
not bug of pixelxpert

**Comment by palexdev** [comment]
Yes bug of pixelexpert
Just remove the thing
It was much better to just install without confirm

**Comment by EleoXDA** [comment]
> Yes bug of pixelexpert Just remove the thing It was much better to just install without confirm

no. it works fine with stock pixel firmware

**Comment by DavidBerdik** [comment]
> no. it works fine with stock pixel firmware

I am on stock Pixel firmware and unfortunately, it does not work fine.

**Comment by EleoXDA** [comment]
> > no. it works fine with stock pixel firmware
> 
> I am on stock Pixel firmware and unfortunately, it does not work fine.

works fine in stock pixel firmware with pixel devices
