### ISSUE TITLE
[Bug] Lockscreen Customisations not Working Properly

### ISSUE THREAD

**Issue by Bxans** [siavash79/PixelXpert#877]
### Describe the issue

Im new to rooting android devices and have rpoted my samsung s24 ultra. Im having a problem with the lockscreen modifications, they seem to work when systemui restarts but then it restarts over and over until my changes that i have made revert back to default.

### Steps to reproduce

These are the modules I have installed

### Expected behavior

It not restarting when changes are applied

### Your device setup (Please take some time to give correct information here)

-samsung s24 ultra
-android 14 (ui 6.1)
-1st August 2024
-magisk 27007
- granted root access to:
![Screenshot_20240828_181542](https://github.com/user-attachments/assets/838f0019-6219-44b7-aa61-1f937c4f9091)
-Magisk modules:
![Screenshot_20240828_180748](https://github.com/user-attachments/assets/5ed889c3-8d25-4113-8980-866d7e5bebc0)
-lsposed zygist 1.9.2
-lsposed modules:
![Screenshot_20240828_181824_LSPosed](https://github.com/user-attachments/assets/17bf0655-d6bb-42e2-b973-39f3303a6df2)

### Logs

[LSPosed_2024-08-28T18_12_03.853639.zip](https://github.com/user-attachments/files/16786840/LSPosed_2024-08-28T18_12_03.853639.zip)

**Comment by EleoXDA** [comment]
ONLY STOCK PIXEL FIRMWARE IN GOOGLE PIXEL DEVICES ARE SUPPORTED! READ README FILE!
