### ISSUE TITLE
Return Android 12 Google Pixel Beta Colored settings app homepage icons.

### ISSUE THREAD

**Issue by Lixkote** [siavash79/PixelXpert#881]
What's on your mind?
An feature to return colored style settings homepage icons (as present in Google Pixel beta of Android 12 or Android 11) because current pixel one feels too bland
![pixel_a12b_settingsd](https://github.com/user-attachments/assets/9c1b6b37-4f2c-4263-917a-22b6079b5b86)
![pixel_a12b_settingsl](https://github.com/user-attachments/assets/b0dfb312-a091-4d70-8267-45916109b640)
![1_Y38X1qLBXOqO3rnEen0Ckg](https://github.com/user-attachments/assets/4c9ae8ba-6777-4e9e-a2e8-ff74c860de6e)

Is this feature implemented on any other app/mod/rom? please specify

Its not implemented it any new rom or app based on Android 13 / 14 that i know of, but i found a commit where this option was removed from LineageOS Android 12 Beta source (might be helpful in recreating these icons).

[ Redesign homepage IA icon ](https://github.com/LineageOS/android_packages_apps_Settings/commit/7d9dceadb74d678989317ab6a51648f4bbd7deff)

**Comment by EleoXDA** [comment]
No
