### ISSUE TITLE
 unable to install  

### ISSUE THREAD

**Issue by Subhandejoy** [siavash79/PixelXpert#883]
### Describe the issue

[Bug]  volume up key not working when installing this module but volume down key working properly , I am using kernel su

### Steps to reproduce

No

### Expected behavior

I think volume up script not working 

### Your device setup (Please take some time to give correct information here)

[KernelSU_install_log_2024-09-17-13-47-39.log](https://github.com/user-attachments/files/17025017/KernelSU_install_log_2024-09-17-13-47-39.log)

### Logs

No

**Comment by EleoXDA** [comment]
YOU NEED TO READ README FILE WHICH SAYS THIS MOD IS ONLY USABLE IN PIXEL DEVICES ON PIXEL STOCK FIRMWARE!
