### ISSUE TITLE
[Bug] Light/dark QS theme have wrong colors

### ISSUE THREAD

**Issue by sadorowo** [siavash79/PixelXpert#891]
### Describe the issue

Hello, I've enabled two options in Theming menu: "Apply light QS theme when using light mode" and "Enable light/dark themes on power menu". I've also set up automatic theme changing on my phone - dark mode is enabled automatically after sunset and disabled at sunrise. However, this doesn't play well with PixelXpert - i'm getting wrong font and tile colours. It's fixed only after restarting SystemUI - but it is annoying to do after every sunset and sunrise.

Preview:

![Screenshot_20240926-200330](https://github.com/user-attachments/assets/741064db-c061-4893-9468-551f2dfa32ac)

### Steps to reproduce

1. Open Android settings
2. Go to "Display"
3. Go to "Dark theme"
4. Set Schedule to "Turns on from sunset to sunrise"
5. Go to PixelXpert app
6. Go to "Theming" category
7. Enable both "Apply light QS theme when using light mode" and "Enable light/dark themes on power menu"
8. Wait for sunset/sunrise to switch theme

### Expected behavior

There shouldn't be any issues with the colours

### Your device setup (Please take some time to give correct information here)

- Manufacturer: Xiaomi Redmi Note 9 Pro (EEA)
- Android 15 AOSP
- Security update: September 5, 2024
- Kernel version: 4.14.352-openela-YAMK-LA.UM.9.1.r1-16300-SMxxx0.QSSI14.0
Fri Sep 6 13:09:34 UTC 2024
- Magisk version: v27.0
- Root apps:
![Screenshot_20240926-201114](https://github.com/user-attachments/assets/072d03f2-295f-449d-a2e5-43e3bba4fdaf)
- Magisk modules:
![Screenshot_20240926-201140](https://github.com/user-attachments/assets/3d8b41e7-1b34-4f9f-a822-839ea3a09b14)
- LSPosed version: 1.9.3 (using LsPosed_mod from GitHub, it's a fork adapted to new Android versions and some fixes)
- LSPosed modules:
![Screenshot_20240926-201257](https://github.com/user-attachments/assets/ae59f855-fd12-4281-957a-d7ed57e7e235)

### Logs

[LSPosed_2024-09-26T20_14_19.519716.zip](https://github.com/user-attachments/files/17153970/LSPosed_2024-09-26T20_14_19.519716.zip)

**Comment by EleoXDA** [comment]
ONLY STOCK PIXEL FIRMWARE ON PIXEL DEVICES IS SUPPORTED! READ README FILE PLEASE
