### ISSUE TITLE
[Bug] Cannot install the module under KernelSU

### ISSUE THREAD

**Issue by EbonyBirch** [siavash79/PixelXpert#892]
### Describe the issue

Mod seems to ignore the keypress upon asking if it should proceed.

### Steps to reproduce

1. Install & run KernelSu
2. Go to modules
3. Click install, select PixelXpert (doesn't matter if it's a regular version or canary)
4. Upon installation a prompt appears, stating that "unmount modules by default" should be disabled,
5. There's a dialog that's asking to either abort (vol -) or install (vol +). It doesn't register the keypresses.

This is not a problem with the buttons themselves as other modules, that are interactive, register them perfectly fine.

### Expected behavior

Module will register vol-, vol+ keypresses and therefore can be installed

### Your device setup (Please take some time to give correct information here)

Sony Xperia 1 VI (XQ-EC54)
Android 14 stable, August secpatch
KernelSU 11928
Modules installed:
- Anti bootloop 1.3.1 / nedorazrab0
- Play Integrity Fix 17.6 / chiteroman
- Tricky Store 1.2.0 RC2 / 5ec1cff
- Zygisk - LSPosed 1.9.3_mod (7244) / LSPosed Devs
- Shamiko 1.1.1 (357) / LSposed Devs
- Zygisk Next 1.2.0-Preview2 / Nullptr, 5ec1cff
Apps that have root:
- Call recorder / Skvalex
- FV file explorer
- FX
- Revanced Manager
- Foldersync Pro
- AdAway
Lsposed modules:
- MessengerEx 1.0.1 / Cloudburst
- Hide My Applist 3.2 / Nullptr

### Logs

Logs cannot be provided since I can't even install the module. Note however that when using regular Magisk, the module installation went smoothly.

**Comment by EbonyBirch** [comment]
![Screenshot_20240927-121622](https://github.com/user-attachments/assets/e7719b9e-2a3f-4845-8449-6126273a1e85)

**Comment by EleoXDA** [comment]
READ README FILE!! THIS MODULE IS ONLY FOR STOCK PIXEL FIRMWARE ON GOOGLE PIXEL DEVICES!!

**Comment by EbonyBirch** [comment]
@EleoXDA - I appreciate the very _insightful_ comment, you couldn't have expressed it more clearly I suppose.
Note, however, that I'm not whining about the module *not working* partially/at all, but the fact that it cannot be even installed. I had no trouble whatsoever installing and using it previously, when I had been running Magisk, even when not every function worked as intended. It still served its purpose and it wouldn't cross my mind to complain about anything, as I do understand the lack of support for mod itself, not that it cannot be even installed at my own risk.

**Comment by EleoXDA** [comment]
> @EleoXDA - I appreciate the very _insightful_ comment, you couldn't have expressed it more clearly I suppose.
> Note, however, that I'm not whining about the module *not working* partially/at all, but the fact that it cannot be even installed. I had no trouble whatsoever installing and using it previously, when I had been running Magisk, even when not every function worked as intended. It still served its purpose and it wouldn't cross my mind to complain about anything, as I do understand the lack of support for mod itself, not that it cannot be even installed at my own risk.

1. You didn't read README file
2. In pixel firmware on pixel devices THE SAME kernelsu installation goes normally.
3. It ONLY fails to install in Non-pixel firmware and non-pixel devices in kernelsu 

Now you see that you are whining???
