### ISSUE TITLE
settings and phone hooks not working

### ISSUE THREAD

**Issue by nightf0x7** [siavash79/PixelXpert#896]
### Describe the issue

Settings and phone apps hooks not working, everything was working fine but suddenly they stopped working, in logs hooks dont work because of bootloop possibilty, i didnt touch anything in my phone setup just installed ios 18 emoji module and updated colorblendr app to latest version

### Steps to reproduce

Pixel xpert app - hooks - settings & phone apps not connected

### Expected behavior

for example Settings app clone apps settings is not showing up

### Your device setup (Please take some time to give correct information here)

Pixel 6 stock firmware september update
Magisk kitsune 27001
Lsposed 1.9.3 & 1.10.0 

### Logs

[LSPosed_2024-10-01T23_28_43.902114.zip](https://github.com/user-attachments/files/17216216/LSPosed_2024-10-01T23_28_43.902114.zip)
[verboseLSPosed_2024-10-01T23_29_01.306100.zip](https://github.com/user-attachments/files/17216218/verboseLSPosed_2024-10-01T23_29_01.306100.zip)

**Comment by EleoXDA** [comment]
> ### Describe the issue
> Settings and phone apps hooks not working, everything was working fine but suddenly they stopped working, in logs hooks dont work because of bootloop possibilty, i didnt touch anything in my phone setup just installed ios 18 emoji module and updated colorblendr app to latest version
> 
> ### Steps to reproduce
> Pixel xpert app - hooks - settings & phone apps not connected
> 
> ### Expected behavior
> for example Settings app clone apps settings is not showing up
> 
> ### Your device setup (Please take some time to give correct information here)
> Pixel 6 stock firmware september update Magisk kitsune 27001 Lsposed 1.9.3 & 1.10.0
> 
> ### Logs
> [LSPosed_2024-10-01T23_28_43.902114.zip](https://github.com/user-attachments/files/17216216/LSPosed_2024-10-01T23_28_43.902114.zip) [verboseLSPosed_2024-10-01T23_29_01.306100.zip](https://github.com/user-attachments/files/17216218/verboseLSPosed_2024-10-01T23_29_01.306100.zip)

open settings and phone app, then go to recents and open PixelXpert and check hooks

**Comment by siavash79** [comment]
Okay do me a favor: head to PX app, and disable PX shortcut in settings in Misc section (first item). Then try again and let me know.
Also, I noticed that you have many (many) modules installed. Can you please disable them and test again

**Comment by EleoXDA** [comment]
78 MODULES 🙄

**Comment by nightf0x7** [comment]
> Okay do me a favor: head to PX app, and disable PX shortcut in settings in Misc section (first item). Then try again and let me know. Also, I noticed that you have many (many) modules installed. Can you please disable them and test again

I have many lsposed & magisk modules, most of them are disabled (i enable what i need when i need it), everything was working fine until suddenly this happened, last thing is installing 
Updating emoji ios 17.4 to 17.4.1 wich introdue overlayfs then disabled it and installed emoji ios 18 module and updated colorblendr app., tried disabling xpert in settings as stated and restarted the phone but still hooks not working (log shows possibilty of bootloop)

**Comment by EleoXDA** [comment]
> > Okay do me a favor: head to PX app, and disable PX shortcut in settings in Misc section (first item). Then try again and let me know. Also, I noticed that you have many (many) modules installed. Can you please disable them and test again
> 
> I have many lsposed & magisk modules, most of them are disabled (i enable what i need when i need it), everything was working fine until suddenly this happened, last thing is Updating emoji ios 17.4 to 17.4.1 wich introdue overlayfs then disabled it and installed emoji ios 18 module and updated colorblendr app., tried disabling xpert in settings as stated and restarted the phone but still hooks not working (log shows possibilty of bootloop)
> 
> Edit: default clone apps option missing from settings even when pixel xpert is disabled

default clone apps are there only because of pixel xpert. And if you uninstall all modules in lsposed other than pixelxpert and uninstall all modules in magisk and reproduce bug, please send us logs. Otherwise the problem is not with pixelxpert but your setup of conflicting modules. The only way out is you to find what is causing conflict and disable/downgrade/report to the dev of that module. We cannot help you with incompatible modules

**Comment by nightf0x7** [comment]
Isnt clone apps there by default in A14 but not for all apps ? Its not there at all, i dont remember actually, will try disabling all but its a headache and everything was already working with my current setup, anyway thanks

**Comment by EleoXDA** [comment]
> Isnt clone apps there by default in A14 but not for all apps ? Its not there at all, i dont remember actually, will try disabling all but its a headache and everything was already working with my current setup, anyway thanks

In the bug report template that you filled up, it says:

> ```Logs
> !This part is vital for bugreport! Missing logs will most probably lead in dismissal of the bugreport!
> Please attach LSposed Module log if you are able to. (Open LSPosed, go to module logs, press save button and attach to this bug report)
> To give clear logs, before extracting LSposed logs, follow these steps:
> 
> Disable all magisk modules other than PixelXpert and LSposed
> Disable all LSposed modules other than PixelXpert
> Disable all theming apps (e.g. Substratum, Repainter and etc)
> Restart and replicate the issue
> After that extract LSposed logs.
>
