### ISSUE TITLE
[Bug] Ignore camera cutout artifact

### ISSUE THREAD

**Issue by whezzel** [siavash79/PixelXpert#897]
### Describe the issue

On my pixel 9 pro xl, with face unlock enabled and the camera cutout ignored, there is a black circle artifact when the camera is attempting face unlock. Disabling face unlock makes the black circle stop appearing.

### Steps to reproduce

1. Setup Face Unlock to unlock the lockscreen of your phone.
2. Enable the "Ignore the camera cutout" option in PixelXpert.
3. Lock screen
4. Wake up phone

See attached video.

https://github.com/user-attachments/assets/dd3cb1fa-a347-45eb-9771-89d3b5560424

### Expected behavior

The expected behavior is that this black circle doesnt appear when face unlock is scanning for a face..

### Your device setup (Please take some time to give correct information here)

- Google Pixel 9 Pro XL
- Stock Android 14 Sept 2024 security patch
- Magisk 27000

![Screenshot_20241001-182515](https://github.com/user-attachments/assets/d2075467-7f5e-4081-970a-f461ba39c2c2)
![Screenshot_20241001-182504](https://github.com/user-attachments/assets/5a883d2c-a242-495d-ae84-e7170010d015)
![Screenshot_20241001-182332](https://github.com/user-attachments/assets/19142ff7-0ec8-4bda-afd9-3071fc904d84)
![Screenshot_20241001-182327](https://github.com/user-attachments/assets/4ecca006-8f17-45ed-9831-c0743a96c92a)

### Logs

[LSPosed_2024-10-01T18_29_24.194046.zip](https://github.com/user-attachments/files/17217712/LSPosed_2024-10-01T18_29_24.194046.zip)

**Comment by siavash79** [comment]
What you are reporting is correct and known. However, there's no fix planned at the moment
