### ISSUE TITLE
(question) android 15 stable support 

### ISSUE THREAD

**Issue by FurhadTheNerd** [siavash79/PixelXpert#902]
as we don't currently have any modules to get lsposed working on the latest stable build of android 15 is there any workarounds?

**Comment by LuminarySage** [comment]
This has worked for me as a drop in replacement for now
https://github.com/mywalkb/LSPosed_mod/releases

**Comment by FurhadTheNerd** [comment]
its working fine with pixel xpert, but other lsposed modules are giving me error like unsupported environment and zygote crashs, i couldn't care much about them though
thanks for your help!

**Comment by EleoXDA** [comment]
This is not an issue. Just the proof that you did not read ReadMe file @FurhadTheNerd
