### ISSUE TITLE
[Bug] Brightness slider margin too big

### ISSUE THREAD

**Issue by justtlouai** [siavash79/PixelXpert#904]
### Describe the issue

PixelXpert causes the brightness slider in QS and QQS (if activated) to have a bigger margin than usual.

### Steps to reproduce

Booting with PixelXpert installed is enough to trigger the issue. Once uninstalled, the margin returns to normal
![Screenshot_20241016-182408](https://github.com/user-attachments/assets/067a79e5-374a-4652-b0d5-5ba4c032afc4)
![Screenshot_20241016-180807](https://github.com/user-attachments/assets/61026ecc-cf5a-4e4b-91dd-59dd016682d5)
First pic (green theme) PixelXpert installed
Second pic (yellow theme) PixelXpert not installed 
uninstalled, reinstalled, and uninstalled again and same result, issue persists with PixelXpert installed.  

**I'd like to ask if the previous version of pixelxpert would work on android 15 ? i might revert back to the old version.

### Expected behavior

Unchanged margins.

### Your device setup (Please take some time to give correct information here)

- Google Pixel 6 pro
- Android 15 (stable)
- October Android update (AP3A.241005.015)
- 27.0 (27000)
- HEBF Optimizer, zFont 3
- Modules installed:
![Screenshot_20241016-184509](https://github.com/user-attachments/assets/e94a5cfc-d659-4743-baea-5a331ae0e2fc)
![Screenshot_20241016-184513](https://github.com/user-attachments/assets/d62d1564-043e-44c2-b3ff-66e31d04381d)
![Screenshot_20241016-184516](https://github.com/user-attachments/assets/273a5f96-55f3-46aa-a7c8-1fefc1eb7a0d)

- LSPosed 1.9.3_mod (7244) - Zygisk
- Only LSPosed module installed is PixelXpert (4.00)

### Logs

[LSPosed_2024-10-16T18_50_12.213391.zip](https://github.com/user-attachments/files/17400702/LSPosed_2024-10-16T18_50_12.213391.zip)
[LSPosed_2024-10-16T18_50_28.792073.zip](https://github.com/user-attachments/files/17400703/LSPosed_2024-10-16T18_50_28.792073.zip)

**Comment by EleoXDA** [comment]
already fixed in canary versions
