### ISSUE TITLE
Disable taskbar and hide navbar not working over 600dp

### ISSUE THREAD

**Issue by binarny** [siavash79/PixelXpert#906]
### Describe the issue

Disable taskbar and hide navbar not working over 600dp screen resolution 

### Steps to reproduce

1. Choose density over 600dp in developer options in settings 
2. Open pixel expert and choose hide navbar and disable android taskbar in navigation bar options.
3. Navbar and taskbar still exist... After reboot still exist too.

### Your device setup (Please take some time to give correct information here)

- Google Pixel 6 Pro (raven)
- Android 15 Stable 
- 05 October 2024
- Magisk 28.0
- Lsposed - zygisk 1.10.1 by Jing Matrix & LSPosed developers 
![Screenshot_20241017-210559](https://github.com/user-attachments/assets/f45cce44-9f60-4351-be13-d507e46b45e1)
![Screenshot_20241017-210537](https://github.com/user-attachments/assets/45b4eeba-f549-4a42-83ce-53760477d93a)
![Screenshot_20241017-210508](https://github.com/user-attachments/assets/fc4cae6b-9f68-4b33-9dc7-5a17d34849b5)

### Logs

[LSPosed_2024-10-17T21_10_59.045774.zip](https://github.com/user-attachments/files/17421337/LSPosed_2024-10-17T21_10_59.045774.zip)

**Comment by EleoXDA** [comment]
I do not see neither taskbar nor navigation bar in your screenshots. Could you toggle them on one by one and send screenshots?

**Comment by binarny** [comment]
> I do not see neither taskbar nor navigation bar in your screenshots. Could you toggle them on one by one and send screenshots?

I took screenshots below 600dp... I really don't like this taskbar and navbar, so I reduced density to disable it, if you fix bug I'll go back to my daily settings over 600dp, Logs are over 600dp.

**Comment by binarny** [comment]
![Screenshot_20241020-122337.png](https://github.com/user-attachments/assets/866d9074-2467-4944-bafa-4762a2d236d0)

**Comment by siavash79** [comment]
fixed
