### ISSUE TITLE
[Bug] Keyguard Wallpaper dim slider doesn't work on lower levels

### ISSUE THREAD

**Issue by Placeholder6** [siavash79/PixelXpert#907]
### Describe the issue

The slider isn't working properly if set to default/0/1 or any small value, it doesnt work however for extra dim values like for 100% the wallpaper goes fully black, but 0% doesn't go as fully normal. 

### Steps to reproduce

1. Set any user photo as wallpaper 
2. Make sure your power saving or bedtime mode is off
3. Open pixel xpert and change the dim value
4. It doesn't change anything if set to 0 but it does when you set to 100
![Screenshot_20241021-172415](https://github.com/user-attachments/assets/cb6b1ff7-3104-4dee-b6d9-a9f1535045e0)
![Screenshot_20241021-172433](https://github.com/user-attachments/assets/03fe3bf5-b8dd-4c47-a4ef-4eceba9f6944)
![Screenshot_20241021-172409](https://github.com/user-attachments/assets/dc85a3bd-4aad-4ee8-bcf7-0fe2386bd8b3)

### Expected behavior

The slider should dim accordingly, 0% should disable dimming completely 

### Your device setup (Please take some time to give correct information here)

- Google Pixel 8 pro
- Android 15 Stable
- 5 October security path
- Kitsune mask v27001
- Lsposed 1.10.1 mod by JingMatrix
- Modules and root apps:
![Screenshot_20241021-170921](https://github.com/user-attachments/assets/005aa206-f412-4ecd-883c-5470a970b621)
![Screenshot_20241021-170911](https://github.com/user-attachments/assets/03c2b6af-30e3-46e4-b30e-34e7873cab14)
![Screenshot_20241021-170856](https://github.com/user-attachments/assets/4473228d-a5e8-4033-9ae5-899e60453184)

### Logs

[LSPosed_2024-10-21T17_18_07.656475.zip](https://github.com/user-attachments/files/17459814/LSPosed_2024-10-21T17_18_07.656475.zip)
[magisk_log_2024-10-21T17.19.37.log](https://github.com/user-attachments/files/17459818/magisk_log_2024-10-21T17.19.37.log)

**Comment by siavash79** [comment]
I couldn't reproduce the issue
