### ISSUE TITLE
[Bug] KernelSU install not working on Stock Pixel 6 (AP3A.241005.015)

### ISSUE THREAD

**Issue by funiel** [siavash79/PixelXpert#911]
### Describe the issue

I've been using this module since it's release with Magisk and I love it so much, so thanks for your hard work. Finally decided to switch to KernelSU, but the installer gets stuck on the volume-up step from "Unmount modules by default" (which is disabled) 

I know this issue has been made in the past, but none of them were using stock A15 on a Pixel device, so I thought I'd make a new one. I've tried with both flavours, but the issue persists 

### Steps to reproduce

1. Install Module via KSU-Manager
2. Install is stuck at Volume-Up screen 

### Expected behavior

Pressing volume-up to install

### Your device setup (Please take some time to give correct information here)

- Google Pixel 6 (oriole)
- A15
- October 5, 2024
- KernelSU v1.0.1 (11928)
- No apps were granted SU access
- playcurlNEXT, PIF, LSPosed_mod, ZygiskNext (everything is up to date)
-  v1.9.3_mod (2744)

### Logs

```
  _  __                    _ ____  _   _ 
 | |/ /___ _ __ _ __   ___| / ___|| | | |
 | ' // _ \ '__| '_ \ / _ \ \___ \| | | |
 | . \  __/ |  | | | |  __/ |___) | |_| |
 |_|\_\___|_|  |_| |_|\___|_|____/ \___/ 

- Preparing image
- Module size: 7.91 MB
- Mounting image
- Current boot slot: _b
- Device is system-as-root
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: module.prop
*********************
 Pixel Xpert 
 by Pixel Xpert Team 
*********************
*********************
 Powered by KernelSU 
*********************
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/me.weishu.kernelsu/cache/module.zip
  inflating: build.type
  inflating: customize.sh
  inflating: module.prop
  inflating: service.sh
  inflating: sqlite3
   creating: system/
   creating: system/priv-app/
   creating: system/priv-app/PixelXpert/
  inflating: system/priv-app/PixelXpert/PixelXpert.apk
  inflating: system/priv-app/PixelXpert/.placeholder
   creating: system/product/
   creating: system/product/overlay/
   creating: system/product/overlay/AOSPMods_LightQS/
  inflating: system/product/overlay/AOSPMods_LightQS/AOSPModsLightQS.apk

*******************************
KernelSU binaries found!

        CAUTION!:      
Before installation, you MUST disable
"Unmount modules by default"
Otherwise, your device will fall into BOOTLOOP!

Do you wish to continue?
Volume Up: Continue
Volume Down: Abort

```

Edit: Added logs and more info

**Comment by siavash79** [comment]
PX installer monitors /dev/input/event0 for inputs. please check if yours is different

**Comment by siavash79** [comment]
I made some changes in the code. See if it helps

**Comment by funiel** [comment]
> PX installer monitors /dev/input/event0 for inputs. please check if yours is different

Ah yes, seems like on the P6 its /dev/input/event1 instead and event0 is the fingerprint reader

```
getevent -l
add device 1: /dev/input/event3
  name:     "fts"
add device 2: /dev/input/event2
  name:     "STM VL53L1 proximity sensor"
add device 3: /dev/input/event0
  name:     "goodix_fingerprint"
add device 4: /dev/input/event1
  name:     "gpio_keys"
/dev/input/event1: EV_KEY       KEY_VOLUMEUP         DOWN
/dev/input/event1: EV_SYN       SYN_REPORT           00000000
```
