### ISSUE TITLE
Automatically check for updates:  Add option for user to set update check frequency

### ISSUE THREAD

**Issue by leifalbor** [siavash79/PixelXpert#914]
Not much to add here that isn't in the title.  Would it possible to add either an interger field to allow users to specify check for updates every x days, or radio box to check for updates daily or weekly, etc etc - something like that?

**Comment by EleoXDA** [comment]
I believe app already does it

**Comment by leifalbor** [comment]
Thanks for the reply.  I know I can enable or disable auto check for update, but cannot find where I set the update check frequency.  Can you please advise where this is located in the app?

Below is what I can see in app settings.

![Screenshot_20241031-072920](https://github.com/user-attachments/assets/07a47e30-8cdd-4764-a225-9ea23b16929e)

**Comment by siavash79** [comment]
I thought about it when making this option in the app. My conclusion was 12 hours is a good amount of time for keeping up to date and also not spamming the notifications. Plus adding a duration option in the app would clutter the page

**Comment by leifalbor** [comment]
> I thought about it when making this option in the app. My conclusion was 12 hours is a good amount of time for keeping up to date and also not spamming the notifications. Plus adding a duration option in the app would clutter the page

Would it be possible instead to add functionality to "Never remind me for this version again" then?

Here's my use case:
I am using canary-400 on a Pixel 9 Pro XL.  Everything is working as I want it to.
Canary-401 is released.  Changelook shows this version:

- Fixed taskbar not getting disabled on tablets
- Improved installation process on KSU

I don't need to upgrade to 401;  my device is not a tablet and I'm not a KSU user so 401 does not offer me any benefit.  But I cannot skip updating to 401 without getting update notifications twice a day, or disabling update checks entirely.
