### ISSUE TITLE
Iconify OEM Support

### ISSUE THREAD

**Issue by Ali382829** [siavash79/PixelXpert#922]
This Not Support OEM Iconify
Unsupported List
One UI
Miui
Color OS
Oxygen OS
Funtouch OS
XOS/HIOS/iTelOS (May Work Or Not Work)

Images

![Screenshot_20241107_165340_Chrome](https://github.com/user-attachments/assets/f429cfed-660c-42be-9580-32615ac9df1c)

Fix

Install Custom ROM
Install Magisk
Install Iconify

**Comment by EleoXDA** [comment]
You are funny. Start with reading README files. Bye
