### ISSUE TITLE
[Feature request] Force Google Camera to work with another gallery app

### ISSUE THREAD

**Issue by Senliast** [siavash79/PixelXpert#924]
What's on your mind?
Currently, when you want to open gallery / photo preview from Google Camera - it will only work, if you have the Google Photos app. If you have any other gallery app, Google Camera will say that you need Google Photos in order to view photos and will not open the gallery. My suggestion is to change it, so that Google Camera will open any 3rd party gallery app.

![Screenshot_20241108-172533](https://github.com/user-attachments/assets/78bc6fe7-3026-4e44-85a6-0db00b8c97f0)

Is this feature implemented on any other app/mod/rom? please specify
Yes, for example in modded Google Camera (like BSG Gcam, MGC Gcam, available at https://www.celsoazevedo.com/files/android/google-camera/) there is an option to select another gallery app.

![Screenshot_20241108-172558](https://github.com/user-attachments/assets/984aebea-5eec-4645-8946-dfd23ae5ff5d)

**Comment by EleoXDA** [comment]
Use mod gcam.
