### ISSUE TITLE
[Bug] Navbar not switching icons QPR2 Beta1 canary 4.0.4

### ISSUE THREAD

**Issue by Ante0** [siavash79/PixelXpert#926]
### Describe the issue

Canary 404 says to have fixed modded navbar, but it's not working for me. 

### Steps to reproduce

1. Go to navbar settings in Pixel Xpert
2. Change position of back, recent
3. Restarting SystemUI does not change button position

### Expected behavior

Expected behavior is that the buttons will change positions. 

### Your device setup (Please take some time to give correct information here)

Google Pixel 7 Pro
Android 15 QPR2 Beta1
Security update: 2024/11
KernelSU 11986 (1.0.2 Manager)
Added screenshots:
![Screenshot_20241116-160119](https://github.com/user-attachments/assets/d2d6212c-908c-4e67-948b-943526835cf7)
![Screenshot_20241116-160112](https://github.com/user-attachments/assets/0bceac41-3224-4401-8666-8ad57d5c9fc6)
![Screenshot_20241116-160102](https://github.com/user-attachments/assets/5c22bb49-9969-4b97-b348-c07e4aa3d2b7)
![Screenshot_20241116-155616](https://github.com/user-attachments/assets/2546fd8a-a087-4a46-979e-c7592542e460)
![Screenshot_20241116-155605](https://github.com/user-attachments/assets/e97531c9-47e1-4ad2-9a17-912391e38a22)
![Screenshot_20241116-155556](https://github.com/user-attachments/assets/71c7f819-1760-4e30-b2c8-caf377e6dd68)

### Logs

[LSPosed_2024-11-16T16_02_56.614917.zip](https://github.com/user-attachments/files/17786880/LSPosed_2024-11-16T16_02_56.614917.zip)

Setup is the same as in QPR1 Beta3 where it did work.
Only difference now is that kernel is 6.1 instead of 5.10

**Comment by EleoXDA** [comment]
Try different LSPosed zips

**Comment by Ante0** [comment]
> Try different LSPosed zips

Will do and will update accordingly 👍

**Comment by siavash79** [comment]
404 refers to gesture nav mods
