### ISSUE TITLE
[Bug] Bootloop on Android 15 (AP4A.241205.013.B1)

### ISSUE THREAD

**Issue by bbbenji** [siavash79/PixelXpert#929]
### Describe the issue

Bootloop on Android 15 (AP4A.241205.013.B1)

### Steps to reproduce

1. Install APatch, patch and install boot.
2. Install Zygisk LSPosed
3. Install ReZygisk
4. Reboot
5. Install PixelXpert
6. Reboot
7. Bootloop

To recover, boot into APatch safemode, disable PixelXpert, & reboot.

### Expected behavior

No bootloop

### Your device setup (Please take some time to give correct information here)

- Android 15 (AP4A.241205.013.B1)
- APatch v0.11.1 (11010)
- Zygisk LSPosed v1.10.1 (7148) Jing Matrix
- ReZygisk v1.0.0
- PixelXpert v4.0.0 | PixelXpert canary (268c636)

### Logs

No logs in LSPosed.

**Comment by siavash79** [comment]
Apatch isn't tested and thus not supported. Use it at your own risk
