### ISSUE TITLE
[Bug] Double-tap to wake phone breaks AOD

### ISSUE THREAD

**Issue by Kicshikxo** [siavash79/PixelXpert#930]
### Describe the issue

When using Double-tap to wake phone and AOD, double-tapping the locked screen works properly, until the phone goes into AOD mode (lowering the refresh rate of the screen), after which any tap on the screen outside the fingerprint scanner area (which takes the phone out of AOD mode), leads to a complete ignoring of screen taps, including in the fingerprint scanner area, after which the only way to turn on the screen is to press the power button. With AOD turned off, there is no such problem and it wakes up with a double tap.

### Steps to reproduce

0. Enable AOD
1. Enable android tap to check feature
2. Enable PixelXpert Double-tap to wake phone feature
3. Lock the screen
4. Wait a couple of seconds
5. Tap once in the area outside the fingerprint scanner
6. Perfect, now reach for the button, the screen no longer responds to taps

### Expected behavior

Double tapping the screen during AOD should wake up the screen as a single tap without this feature

### Your device setup (Please take some time to give correct information here)

Google Pixel 7a
Android 15 AP3A.241105.007
2024-11-05
Magisk 28.1
LSPosed 1.10.1
The problem is observed with only PixelXpert enabled

### Logs

[modules_2024-12-09T06:36:55.317965.log](https://github.com/user-attachments/files/18056255/modules_2024-12-09T06.36.55.317965.log)

**Comment by EleoXDA** [comment]
Hi. Please do not leave out logs. It is very essential for debugging. And first and foremost disable all other mods in magisk/lsposed before reproducing, then after successful reproduction of the event, share the logs from lsposed app

**Comment by EleoXDA** [comment]
The logs we require are from lsposed app. It is a zip file that contains all that is needed

**Comment by Kicshikxo** [comment]
@EleoXDA Yes, of course, here's the log. It just said that I needed the log of modules, so I found the log of modules among the files. At the time of the logs I had disabled all Magisk and LSPosed modules except PixelXpert and anti bootloop
[LSPosed_2024-12-09T06_38_28.209178.zip](https://github.com/user-attachments/files/18065347/LSPosed_2024-12-09T06_38_28.209178.zip)

**Comment by siavash79** [comment]
Tested. Works as intended. Any tap on aod should be double tap when option is enabled
