### ISSUE TITLE
Re: Issue #935

### ISSUE THREAD

**Issue by frak0d** [siavash79/PixelXpert#936]
continuation of #935
(locking issues is stupid, "close" them instead !!)

> Perfect! You even failed to acknowledge (and read it written in README file clean and wide) that THIS MOD IS ONLY FOR PIXEL DEVICES RUNNING ON STOCK PIXEL FIRMWARE.

I am well aware of that, but this issue isn't device related.

Issue is that the NetworkMonitor code is using `TrafficStats.getTotalTxBytes()` to measure data usage, which according to Android documentation “Counts packets across all network interfaces”. So if a VPN is active, same packets may get counted multiple times.

> I will add a script to brick devices that are not running stock pixel firmware. Maybe that will teach some a lesson.

@EleoXDA The reason I created issue #935 was so  that PixelXpert becomes better for everyone. No need to be a Dick about it.

**You can test this behaviour on a pixel device yourself, if that makes you feel better.**

**Comment by EleoXDA** [comment]
If you have a way to make it better, there are PRs. and don't call names. You are not in school anymore. Grow up!
