### ISSUE TITLE
[FEAT] Fix media "previous" button

### ISSUE THREAD

**Issue by HironTez** [siavash79/PixelXpert#937]
What's on your mind?

My suggestion is to add a setting to change the behaviour of the media "Previous" button to actually switch tracks and not start from the beginning.

The native behaviour is actually quite bad. I usually want to repeat a track after it ends, not before it ends. But with the native behaviour I have to press the button twice. And that's not so bad, until you're wearing earbuds and have to tap on the earbud 3 times and then 3 more times.

Is this feature implemented on any other app/mod/rom? please specify

I've seen this feature on a custom ROM several years ago but can't remember on which one.

**Comment by EleoXDA** [comment]
This probably should be done on app base. systemUI and framework do not control the media buttons anymore. If you can, find the custom ROM that had it, read its source code, find the code related and create a PR. We will check to see if it is viable

**Comment by HironTez** [comment]
@EleoXDA Thanks for your reply. I actually can't remember which ROM it was as it was several years ago when I was changing multiple ROMs every week on my old Xiaomi. If this feature is not related to Xpert's functionality then you can close this issue I guess.
