### ISSUE TITLE
[Bug] Latest Canary 411 messes up Pixel Fold's dock

### ISSUE THREAD

**Issue by Alternative415** [siavash79/PixelXpert#938]
### Describe the issue

When you install Pixel Xpert canary version 411, the leftmost 'Open app drawer' icon disappears in the dock. This does not happen with version 410..

### Steps to reproduce

1. Install Pixel Xpert Canary v411
2. Open dock

### Expected behavior

At the leftmost of dock, 'Open app drawer' icon is visible and can be clicked.

### Your device setup (Please take some time to give correct information here)

Google Pixel Fold (Felix)
Android 15 QPR1 (Build AP4A.241205.013)
Security update: Dec 5th
APatch + LsPosed 1.10.1

### Logs

[LSPosed_2024-12-16T22_31_10.004810.zip](https://github.com/user-attachments/files/18150670/LSPosed_2024-12-16T22_31_10.004810.zip)

**Comment by LovecraftianGodsKiller** [comment]
I'm experiencing the same problem on my Pixel 7. (I use a tablet DPI on my device)

**For my device setup info**  
Google Pixel 7 (panther)  
Android 15 QPR2 (Build AP4A.20241205.013)
Security patch update: Dec 5th
KernelSU + LSPosed 1.10.1 (from JingMatrix)
