### ISSUE TITLE
[Feature request] Option to bypass manual confirmation of biometrics unlock when using face unlock

### ISSUE THREAD

**Issue by guniens** [siavash79/PixelXpert#940]
Please add an option to allow us to skip confirmation of biometrics popup when using face unlock (like Chrome Password Manager and WhatsApp do).
Please add an option to allow us to use the new biometrics popup when using face unlock (like Chrome Password Manager).
Something like [this](https://github.com/rafagale/biometric-bypass).

**Comment by EleoXDA** [comment]
If it is already available, use it
