### ISSUE TITLE
[Feature request] Option to hide GBoard's globe icon on navbar

### ISSUE THREAD

**Issue by guniens** [siavash79/PixelXpert#941]
Please add an option to hide Gboard's globe icon on navbar.
This icon appears when you have multiple languages, problem is that long pressing space bar on Gboard brings to the same result.
Please have a look on r/GooglePixel and search for globe, I think lot of Pixel 8/9 users would be pretty happy with it.

**Comment by EleoXDA** [comment]
Use another keyboard that is customizable

**Comment by guniens** [comment]
Honestly don't know why you work on this as every request, being it a feature request or bug fixes is a simple NO or NOT PLANNED or USE SOMETHING ELSE.

I proved that lots of people hate the globe icon, why should change my keyboard? Gboard is the gold standard on android, why change it?

Navbar mods are already present, @siavash79 please consider adding this.
