### ISSUE TITLE
[Bug] Bootloop after OTA on Pixel 7

### ISSUE THREAD

**Issue by WiIIiamWei** [siavash79/PixelXpert#942]
### Describe the issue

As the title says, a bootloop happened when I upgraded my Pixel 7 via OTA, and it's likely a problem with PixelXpert.

### Steps to reproduce

It's a bit complicated and I cannot determine what's causing the problem, so I'll describe what I have gone through thoroughly:

I received an OTA update last night and decided to apply it. I reinstalled Magisk to another slot and rebooted, but the boot seems ridiculously slow. It boots up eventually but I found all changes by PixelXpert was reverted, however PixelXpert app can launch normally (meaning that Xpert should still have root privilege), but the hook page says only `com.android.settings` is responsive.

I was aware of that but decided a reboot may fix the problem. But this reboot results in a bootloop(1). Luckily I have an anti phone bricking Magisk module installed and it disabled all my Magisk modules after being stuck in loading screen for a minute.

For the next few minutes, I began to enable the Magisk modules little by little and reboot every time to determine what is causing the problem, and bootlooped(2) again when I enabled Xpert, saved again by the anti bricking module.

### Additional information:

The cause of the bootloops (marked (1) (2) above) seems to be different according to the logs of the anti bricking module:

* Bootloop (1): The module detected a stuck in loading screen for 1.2 minutes and could not find system UI process up. All Magisk modules are disabled and the phone starts normally.
* Bootloop (2): The phone **did not** enter loading screen, but rebooted twice in a row automatically. The module tried to clear the package cache and re-enable all disabled system apps, but the phone still fail to enter loading screen. The module then tried to disable SELinux and the phone finally boots up.

### Your device setup (Please take some time to give correct information here)

* Google Pixel 7
* Android 15 Stable (December 2024, AP4A.241205.013)
* Magisk 28.1 (28100)
* [JingMatrix's LSPosed fork 1.10.1](https://github.com/JingMatrix/LSPosed/releases/tag/v1.10.1)

**For the list of modules/apps installed:** I think it's not likely their fault because enabling just LSPosed with all other apps except PixelXpert did not result in a bootloop. However I'll list a few modules and apps that have root access and may be related to the problem just in case:

**These apps are granted superuser rights and could be related to the problem:**
* PixelXpert
* System UI
* Pixel Launcher

**These modules are installed, tested and proven they are fine without Xpert but could be related to the problem:**
* NavTweaks (former Fullscreen/Immersive gestures) (Q-V) 27.5 by DanGLES3

### Logs

Due to the fact it's related to boot problems, Magisk logs are provided instead of LSPosed logs. **This log file was generated after bootloop (2) mentioned above.**

[magisk_log_2024-12-18T23.23.27.txt](https://github.com/user-attachments/files/18193897/magisk_log_2024-12-18T23.23.27.txt)

Due to the fact I'm busy with my own things, I don't have time to test whether it's a module conflict by only enabling PixelXpert. The module is somehow functioning now after re-enabling it (after bootloop(2), all settings are lost and superuser rights were canceled however). I'll use it for now and try not to reboot my device :(

**Comment by EleoXDA** [comment]
Then remove root and try from scratch. You should NEVER update via OTA with edited boot
