### ISSUE TITLE
[Bug] Internet tile option not working

### ISSUE THREAD

**Issue by nhanntt0401** [siavash79/PixelXpert#943]
### Describe the issue

The option to get back separate wifi/data tiles instead of internet not working

### Steps to reproduce

I have enabled the option but no wifi/data tiles showing up in QS when using edit function

### Your device setup (Please take some time to give correct information here)

- Google pixel fold
- Android 15 stable
- Security update: Dec2024
- Magisk 28.1
- List of apps that have been granted root access: iconify, pixelxpert
- List of your magisk modules and versions: iconify, pixelxpert, play intergrity fix, youtube vanced, zygisk-LSposed
- Your LSposed version: 1.10.1 (7115) 
- List of your LSposed modules and versions:  iconify, pixelxpert

**Comment by EleoXDA** [comment]
Already removed. Use BetterInternetTiles app
