### ISSUE TITLE
[Bug] Status bar notification icons not showing after Pixel 7 pro December update

### ISSUE THREAD

**Issue by ranasrule** [siavash79/PixelXpert#944]
### Describe the issue

Status bar notification icons are not showing after Pixel 7 pro December update

### Steps to reproduce

1) Status bar notification icons not visible for any app.

### Expected behavior

Status bar notification icons should be visible.

### Your device setup (Please take some time to give correct information here)

Google Pixel 7 Pro with latest December update and latest version of Magisk, LSposed and PixelXpert

**Comment by EleoXDA** [comment]
Please recreate issue with all the asked information
