### ISSUE TITLE
[Bug] Small hair like curved line appear below the QQS

### ISSUE THREAD

**Issue by guniens** [siavash79/PixelXpert#945]
### Describe the issue

Small hair like curved line appear below the QQS

### Steps to reproduce

With Light QS Panel Enabled.
Small hair like curved line appear below the QQS, above Notifications panel.
I've highlighted with two red circles in the screenshot, please zoom.
![1](https://github.com/user-attachments/assets/9dea2279-b046-4435-a608-b1e4afc19520)

### Your device setup (Please take some time to give correct information here)

- Device: Google Pixel 8
- OS: Stock Android 15.0 (dec 2024 security patch)
- Latest canary

**Comment by EleoXDA** [comment]
It is known and will not be fixed. Blame Google
