### ISSUE TITLE
[Bug] Bugged QS edit panel with Light QS Panel Enabled

### ISSUE THREAD

**Issue by guniens** [siavash79/PixelXpert#946]
### Describe the issue

Bugged QS edit panel with Light QS Panel Enabled

### Steps to reproduce

With Light QS Panel Enabled.
Bugged QS edit panel at top and bottom.
![2](https://github.com/user-attachments/assets/e395b459-98cc-4cd0-9308-cce5d52ec5d1)

### Your device setup (Please take some time to give correct information here)

- Device: Google Pixel 8
- OS: Stock Android 15.0 (dec 2024 security patch)
- Latest canary

**Comment by EleoXDA** [comment]
It is not bugged. Just a graphic glitch. And since person enters this menu not more than twice a year, it is nothing severe

**Comment by guniens** [comment]
A graphic glitch is a bug doesn't matter how you call I'll buy it's a bug and bug should be fixed no matter if people use it a lot or not. 
@siavash79 please consider fixing this.

**Comment by siavash79** [comment]
It's too difficult to fix and too rarely seen to worth it.
