### ISSUE TITLE
Gesture Sensitivity

### ISSUE THREAD

**Issue by taninc** [siavash79/PixelXpert#947]
What's on your mind?
:
I hope there is an option to **increase** and decrease Gesture Sensitivity. Coming from Samsung's one-hand operations, I am frustrated that right and left back gestures are not always 100% performed. I'd say it works about 95% of the time, but that 5% is frustrating enough. It happens more often when you are browsing pictures.

Maybe the sensitivity I am referring to is related to swipe distance (which you can edit on Samsung), but on Samsung, I can visually see that the handle (swipe) action is getting triggered every time. If I do not swipe far enough (as set in the distance setting), the action does not get performed.

Is this feature implemented on any other app/mod/ROM? Please specify.
:
I guess it is unusual that Samsung made "quick action" an option in their app, starting actions before you release your finger from the screen. That could also be a great option.

**Comment by siavash79** [comment]
It's already implemented in gesture settings on Android

**Comment by taninc** [comment]
> It's already implemented in gesture settings on Android

If you are referring to the back sensitivity,
It's not really the same as what I asked.

I already have that setting as high.
Even at high, the gesture is not always triggered.

**Comment by EleoXDA** [comment]
Well, then it is eithet hardware problem on your device or just difference in ROMs

**Comment by taninc** [comment]
> Well, then it is eithet hardware problem on your device or just difference in ROMs

Hi, sorry to bother you again about this.
I’m using the stock ROM, and the hardware on my Pixel 9 Pro is fine.

I think the issue is more about how the gesture is implemented differently between Samsung and Google. On Samsung, you can adjust how far you need to swipe to trigger the gesture.

If that’s not possible to implement, would it be feasible to make the action start before you lift your finger from the screen? I use the back swipe a lot, and that will save so much time.
