### ISSUE TITLE
[Bug] Longpressing QS toggle makes icon go black while on light theme

### ISSUE THREAD

**Issue by guniens** [siavash79/PixelXpert#948]
### Describe the issue

Longpressing QS toggle makes icon go black while on light theme, is not reverted afterwards and doesn't happen in dark mode. Switching themes temporarily fixes it.

### Steps to reproduce

- turn light mode on
- long press QS toggle and see icon is black
- switch to dark mode and back to light to temporarily fix it

### Expected behavior

QS toggle icon should stay white in light mode as it stays black while in dark mode

### Your device setup (Please take some time to give correct information here)

- Pixel 8
- Android 15, Dec 2024 security patch
- Latest canary

**Comment by EleoXDA** [comment]
Please send screenshots togethet with lsposed logs

**Comment by siavash79** [comment]
Thanks. It's under investigation

**Comment by guniens** [comment]
@siavash79 just tried, not fixed

**Comment by siavash79** [comment]
> @siavash79 just tried, not fixed

You gotta try the latest canary

**Comment by guniens** [comment]
![Uploading Screenshot_20241224-083315.png…]()

**Comment by guniens** [comment]
![Screenshot_20241224-083315](https://github.com/user-attachments/assets/85cc2d5d-99b5-480e-9041-6595874faff4)
