### ISSUE TITLE
No notification icons in status bar

### ISSUE THREAD

**Issue by soliviantar** [siavash79/PixelXpert#949]
### Describe the issue

Notifications arrive, a pop-up appears, but no icon in shown in the status bar

### Steps to reproduce

1. Receive a notification from any app
2. No icon appears if the module is active

### Expected behavior

Icons should appear and stay in the status bar whenever an app sends a notification 

### Your device setup (Please take some time to give correct information here)

- Google Pixel 8a 
- A15 
- December update
- Magical 28.1
- Root access: AdAway, Better Internet Tiles, Neo Backup, Solid Explorer, Storage Isolation, Swift Backup 
- Magisk modules: BCR, De-bloater, NavTweaks, PlayIntegrityFix, Shamiko, Systemless Hosts, Zygisk - LSPosed (Jingmatrix's, 1.10.1 7115), Zygisk Assistant, Zygisk-detach
![Screenshot_20241225-110154](https://github.com/user-attachments/assets/dd43075a-3a5c-4200-9476-4fd55f60bac3)
- LSPosed (Jingmatrix's, 1.10.1 7115)
- LSPosed modules: Hide My Applist 3.3

### Logs

[LSPosed_2024-12-25T11_26_29.459998.zip](https://github.com/user-attachments/files/18245465/LSPosed_2024-12-25T11_26_29.459998.zip)

**Comment by aarchangel64** [comment]
I am also having this issue on the Pixel 8 Pro. I am not 100% sure but I think it started happening after the December OTA update.

**Comment by aarchangel64** [comment]
Actually, this was fixed for me by updating from stable to canary-416.

**Comment by soliviantar** [comment]
> Actually, this was fixed for me by updating from stable to canary-416.

that fixed it for me as well, thanks for letting me know!

**Comment by TipsyTheCat** [comment]
it took me a week to figure out this module was the cause TwT, updating to canary
